/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HumanResource.gui;

import HumanResource.Fitur;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.Table;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yestin
 */
public class DaftarFitur extends javax.swing.JFrame {

    Fitur Fit = new Fitur();
    Table Tab = new Table();
    int Left  = SwingConstants.LEFT;
    int Center = SwingConstants.CENTER;
    int Right = SwingConstants.RIGHT;
    /**
     * Creates new form DaftarFitur
     */
    public DaftarFitur() {
        initComponents();
        setTitle("Daftar Fitur");
        Fit.getFitur(tblFitur);
        BackgroundImage BI = new BackgroundImage();
        BI.BackgroundJPanel(this, pnlDaftarFitur);
        Tab.TableAlignment2(tblFitur, Center, Left, Center);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDaftarFitur = new javax.swing.JPanel();
        lblNamaFitur = new javax.swing.JLabel();
        txtNamaFitur = new javax.swing.JTextField();
        scrlFitur = new javax.swing.JScrollPane();
        tblFitur = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNamaFitur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaFitur.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaFitur.setText("Nama Fitur :");

        txtNamaFitur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaFitur.setForeground(new java.awt.Color(0, 0, 255));
        txtNamaFitur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaFiturKeyPressed(evt);
            }
        });

        tblFitur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblFitur.setForeground(new java.awt.Color(0, 0, 255));
        scrlFitur.setViewportView(tblFitur);

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDaftarFiturLayout = new javax.swing.GroupLayout(pnlDaftarFitur);
        pnlDaftarFitur.setLayout(pnlDaftarFiturLayout);
        pnlDaftarFiturLayout.setHorizontalGroup(
            pnlDaftarFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarFiturLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblNamaFitur)
                .addGap(54, 54, 54)
                .addComponent(txtNamaFitur, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addComponent(scrlFitur)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDaftarFiturLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(37, 37, 37)
                .addComponent(btnEdit)
                .addGap(28, 28, 28)
                .addComponent(btnTutup)
                .addGap(47, 47, 47))
        );
        pnlDaftarFiturLayout.setVerticalGroup(
            pnlDaftarFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarFiturLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlDaftarFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaFitur)
                    .addComponent(txtNamaFitur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(scrlFitur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlDaftarFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTutup)
                    .addComponent(btnEdit)
                    .addComponent(btnRefresh))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDaftarFitur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDaftarFitur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaFiturKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaFiturKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_A || evt.getKeyCode()==KeyEvent.VK_B || evt.getKeyCode()==KeyEvent.VK_C ||
                evt.getKeyCode()==KeyEvent.VK_D || evt.getKeyCode()==KeyEvent.VK_E || evt.getKeyCode()==KeyEvent.VK_F ||
                evt.getKeyCode()==KeyEvent.VK_G || evt.getKeyCode()==KeyEvent.VK_H || evt.getKeyCode()==KeyEvent.VK_I ||
                evt.getKeyCode()==KeyEvent.VK_J || evt.getKeyCode()==KeyEvent.VK_K || evt.getKeyCode()==KeyEvent.VK_L ||
                evt.getKeyCode()==KeyEvent.VK_M || evt.getKeyCode()==KeyEvent.VK_N || evt.getKeyCode()==KeyEvent.VK_O ||
                evt.getKeyCode()==KeyEvent.VK_P || evt.getKeyCode()==KeyEvent.VK_Q || evt.getKeyCode()==KeyEvent.VK_R ||
                evt.getKeyCode()==KeyEvent.VK_S || evt.getKeyCode()==KeyEvent.VK_T || evt.getKeyCode()==KeyEvent.VK_U ||
                evt.getKeyCode()==KeyEvent.VK_V || evt.getKeyCode()==KeyEvent.VK_W || evt.getKeyCode()==KeyEvent.VK_X ||
                evt.getKeyCode()==KeyEvent.VK_Y || evt.getKeyCode()==KeyEvent.VK_Z || evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode()==KeyEvent.VK_SPACE || evt.getKeyCode()==KeyEvent.VK_0 || evt.getKeyCode()==KeyEvent.VK_1 ||
                evt.getKeyCode()==KeyEvent.VK_2 || evt.getKeyCode()==KeyEvent.VK_3 || evt.getKeyCode()==KeyEvent.VK_4 ||
                evt.getKeyCode()==KeyEvent.VK_5 || evt.getKeyCode()==KeyEvent.VK_6 || evt.getKeyCode()==KeyEvent.VK_7 ||
                evt.getKeyCode()==KeyEvent.VK_8 || evt.getKeyCode()==KeyEvent.VK_9){
            String NamaFitur = (((String)txtNamaFitur.getText().trim()).toString());
            Fit.getFitur(tblFitur, NamaFitur);
            Tab.TableAlignment2(tblFitur, Center, Left, Center);
        }
    }//GEN-LAST:event_txtNamaFiturKeyPressed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        EditFitur EF = new EditFitur();
        
        DefaultTableModel dtm = (DefaultTableModel)tblFitur.getModel();
        int row = tblFitur.getSelectedRow();
        Integer KodeFitur = (((Integer)dtm.getValueAt(row, 0)));
        EF.ftxtKodeFitur.setValue(new Integer(KodeFitur));
        String NamaFitur = Fit.getNamaFitur(KodeFitur);
        EF.txtNamaFitur.setText(new String(NamaFitur));
        
        EF.setLocationRelativeTo(this);
        EF.setVisible(true);
        
        if(txtNamaFitur.getText().trim().length()>0){
            String NmFitur = (((String)txtNamaFitur.getText().trim()).toString());
            Fit.getFitur(tblFitur, NmFitur);
            Tab.TableAlignment2(tblFitur, Center, Left, Center);
        }
        else if(txtNamaFitur.getText().trim().length()==0){
            Fit.getFitur(tblFitur);
            Tab.TableAlignment2(tblFitur, Center, Left, Center);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        if(txtNamaFitur.getText().trim().length()>0){
            String NmFitur = (((String)txtNamaFitur.getText().trim()).toString());
            Fit.getFitur(tblFitur, NmFitur);
            Tab.TableAlignment2(tblFitur, Center, Left, Center);
        }
        else if(txtNamaFitur.getText().trim().length()==0){
            Fit.getFitur(tblFitur);
            Tab.TableAlignment2(tblFitur, Center, Left, Center);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel lblNamaFitur;
    private javax.swing.JPanel pnlDaftarFitur;
    private javax.swing.JScrollPane scrlFitur;
    private javax.swing.JTable tblFitur;
    private javax.swing.JTextField txtNamaFitur;
    // End of variables declaration//GEN-END:variables
}
