/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HumanResource.gui;

import HumanResource.Sift;
import Transaksi.gui.DataTransaksi;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.Table;
import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yestin
 */
public class DaftarSift extends javax.swing.JFrame {

    Sift Sift = new Sift();
    Table Tab = new Table();
    BackgroundImage BI = new BackgroundImage();
    
    int Left = SwingConstants.LEFT;
    int Center = SwingConstants.CENTER;
    int Right = SwingConstants.RIGHT;
    /**
     * Creates new form DaftarSift
     */
    public DaftarSift() {
        initComponents();
        setTitle("Daftar Sift");
        Sift.getSift(tblSift);
        Tab.TableAlignment4(tblSift, Center, Center, Center, Center, Center);
        BI.BackgroundJPanel(this, pnlDaftarSift);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDaftarSift = new javax.swing.JPanel();
        scrlSift = new javax.swing.JScrollPane();
        tblSift = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();
        btnEdti = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblSift.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblSift.setForeground(new java.awt.Color(0, 0, 255));
        scrlSift.setViewportView(tblSift);

        btnTutup.setBackground(new java.awt.Color(255, 255, 255));
        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        btnEdti.setBackground(new java.awt.Color(255, 255, 255));
        btnEdti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btnEdti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdtiActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDaftarSiftLayout = new javax.swing.GroupLayout(pnlDaftarSift);
        pnlDaftarSift.setLayout(pnlDaftarSiftLayout);
        pnlDaftarSiftLayout.setHorizontalGroup(
            pnlDaftarSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlSift, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDaftarSiftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(47, 47, 47)
                .addComponent(btnEdti)
                .addGap(44, 44, 44)
                .addComponent(btnTutup)
                .addGap(49, 49, 49))
        );
        pnlDaftarSiftLayout.setVerticalGroup(
            pnlDaftarSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarSiftLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(scrlSift, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnlDaftarSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDaftarSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEdti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnRefresh))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDaftarSift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDaftarSift, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEdtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdtiActionPerformed
        // TODO add your handling code here:
        EditSift ES = new EditSift();
        
        int row = tblSift.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel)tblSift.getModel();
        
        int KodeSift = (((Integer)dtm.getValueAt(row, 0)).intValue());
        int Sft = Sift.getSift(KodeSift);
        ES.ftxtSift.setValue(new Integer(Sft));
        String WaktuMulai = Sift.getWaktuMulai(KodeSift);
        ES.txtWaktuMulai.setText(new String(WaktuMulai));
        String WaktuSelesai = Sift.getWaktuSelesai(KodeSift);
        ES.txtWaktuSelesai.setText(new String(WaktuSelesai));
        
        ES.setLocationRelativeTo(this);
        ES.setVisible(true);
        
        Sift.getSift(tblSift);
        Tab.TableAlignment4(tblSift, Center, Center, Center, Center, Center);
    }//GEN-LAST:event_btnEdtiActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        Sift.getSift(tblSift);
        Tab.TableAlignment4(tblSift, Center, Center, Center, Center, Center);
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdti;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTutup;
    private javax.swing.JPanel pnlDaftarSift;
    private javax.swing.JScrollPane scrlSift;
    private javax.swing.JTable tblSift;
    // End of variables declaration//GEN-END:variables
}
