/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HumanResource.gui;

import HumanResource.JenisIdentitas;
import Util.BackgroundImage;
import Util.Table;
import java.awt.event.KeyEvent;
import javax.swing.SwingConstants;

/**
 *
 * @author Yestin
 */
public class DaftarJenisIdentitas extends javax.swing.JDialog {

    BackgroundImage BI = new BackgroundImage();
    JenisIdentitas JI = new JenisIdentitas();
    Table Tab = new Table();
    int Left = SwingConstants.LEFT;
    int Center = SwingConstants.CENTER;
    int Right = SwingConstants.RIGHT;
    /**
     * Creates new form DaftarJenisIdentitas
     */
    public DaftarJenisIdentitas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Daftar Identitas");
        BI.BackgroundJPanel(this, pnlDaftarJenisIdentitas);
        JI.getJenisIdentitas(tblJenisIdentitas);
        Tab.TableAlignment2(tblJenisIdentitas, Center, Center, Center);
        txtNamaJenis.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJenisIdentitas = new javax.swing.ButtonGroup();
        pnlDaftarJenisIdentitas = new javax.swing.JPanel();
        scrlJenisIdentitas = new javax.swing.JScrollPane();
        tblJenisIdentitas = new javax.swing.JTable();
        rbNamaJenis = new javax.swing.JRadioButton();
        txtNamaJenis = new javax.swing.JTextField();
        rbSemua = new javax.swing.JRadioButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblJenisIdentitas.setForeground(new java.awt.Color(0, 0, 255));
        scrlJenisIdentitas.setViewportView(tblJenisIdentitas);

        bgJenisIdentitas.add(rbNamaJenis);
        rbNamaJenis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbNamaJenis.setForeground(new java.awt.Color(0, 0, 255));
        rbNamaJenis.setText("Nama Jenis :");
        rbNamaJenis.setOpaque(false);
        rbNamaJenis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbNamaJenisItemStateChanged(evt);
            }
        });

        txtNamaJenis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaJenis.setForeground(new java.awt.Color(0, 0, 255));
        txtNamaJenis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaJenisKeyPressed(evt);
            }
        });

        bgJenisIdentitas.add(rbSemua);
        rbSemua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbSemua.setForeground(new java.awt.Color(0, 0, 255));
        rbSemua.setSelected(true);
        rbSemua.setText("Semua");
        rbSemua.setOpaque(false);
        rbSemua.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSemuaItemStateChanged(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDaftarJenisIdentitasLayout = new javax.swing.GroupLayout(pnlDaftarJenisIdentitas);
        pnlDaftarJenisIdentitas.setLayout(pnlDaftarJenisIdentitasLayout);
        pnlDaftarJenisIdentitasLayout.setHorizontalGroup(
            pnlDaftarJenisIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlJenisIdentitas)
            .addGroup(pnlDaftarJenisIdentitasLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(pnlDaftarJenisIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSemua)
                    .addGroup(pnlDaftarJenisIdentitasLayout.createSequentialGroup()
                        .addComponent(rbNamaJenis)
                        .addGap(33, 33, 33)
                        .addComponent(txtNamaJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDaftarJenisIdentitasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTutup)
                .addGap(47, 47, 47))
        );
        pnlDaftarJenisIdentitasLayout.setVerticalGroup(
            pnlDaftarJenisIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarJenisIdentitasLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlDaftarJenisIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNamaJenis)
                    .addComponent(txtNamaJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rbSemua)
                .addGap(57, 57, 57)
                .addComponent(scrlJenisIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnTutup)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDaftarJenisIdentitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDaftarJenisIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSemuaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSemuaItemStateChanged
        // TODO add your handling code here:
        txtNamaJenis.setEnabled(false);
        JI.getJenisIdentitas(tblJenisIdentitas);
        Tab.TableAlignment2(tblJenisIdentitas, Center, Center, Center);
    }//GEN-LAST:event_rbSemuaItemStateChanged

    private void rbNamaJenisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbNamaJenisItemStateChanged
        // TODO add your handling code here:
        txtNamaJenis.setEnabled(true);
    }//GEN-LAST:event_rbNamaJenisItemStateChanged

    private void txtNamaJenisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaJenisKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_A || evt.getKeyCode()==KeyEvent.VK_B || evt.getKeyCode()==KeyEvent.VK_C ||
                evt.getKeyCode()==KeyEvent.VK_D || evt.getKeyCode()==KeyEvent.VK_E || evt.getKeyCode()==KeyEvent.VK_F ||
                evt.getKeyCode()==KeyEvent.VK_G || evt.getKeyCode()==KeyEvent.VK_H || evt.getKeyCode()==KeyEvent.VK_I ||
                evt.getKeyCode()==KeyEvent.VK_J || evt.getKeyCode()==KeyEvent.VK_K || evt.getKeyCode()==KeyEvent.VK_L ||
                evt.getKeyCode()==KeyEvent.VK_M || evt.getKeyCode()==KeyEvent.VK_N || evt.getKeyCode()==KeyEvent.VK_O ||
                evt.getKeyCode()==KeyEvent.VK_P || evt.getKeyCode()==KeyEvent.VK_Q || evt.getKeyCode()==KeyEvent.VK_R ||
                evt.getKeyCode()==KeyEvent.VK_S || evt.getKeyCode()==KeyEvent.VK_T || evt.getKeyCode()==KeyEvent.VK_U ||
                evt.getKeyCode()==KeyEvent.VK_V || evt.getKeyCode()==KeyEvent.VK_W || evt.getKeyCode()==KeyEvent.VK_X ||
                evt.getKeyCode()==KeyEvent.VK_Y || evt.getKeyCode()==KeyEvent.VK_Z || evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode()==KeyEvent.VK_SPACE || evt.getKeyCode()==KeyEvent.VK_0 || evt.getKeyCode()==KeyEvent.VK_1 ||
                evt.getKeyCode()==KeyEvent.VK_2 || evt.getKeyCode()==KeyEvent.VK_3 || evt.getKeyCode()==KeyEvent.VK_4 ||
                evt.getKeyCode()==KeyEvent.VK_5 || evt.getKeyCode()==KeyEvent.VK_6 || evt.getKeyCode()==KeyEvent.VK_7 ||
                evt.getKeyCode()==KeyEvent.VK_8 || evt.getKeyCode()==KeyEvent.VK_9){
            String NamaJenis = (((String)txtNamaJenis.getText().trim()).toString());
            JI.getJenisIdentitas(tblJenisIdentitas, NamaJenis);
            Tab.TableAlignment2(tblJenisIdentitas, Center, Center, Center);
        }
    }//GEN-LAST:event_txtNamaJenisKeyPressed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgJenisIdentitas;
    private javax.swing.JButton btnTutup;
    private javax.swing.JPanel pnlDaftarJenisIdentitas;
    private javax.swing.JRadioButton rbNamaJenis;
    private javax.swing.JRadioButton rbSemua;
    private javax.swing.JScrollPane scrlJenisIdentitas;
    private javax.swing.JTable tblJenisIdentitas;
    private javax.swing.JTextField txtNamaJenis;
    // End of variables declaration//GEN-END:variables
}
