/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HumanResource.gui;

import App.Outlet;
import HumanResource.Identitas;
import HumanResource.JenisPekerjaan;
import HumanResource.Pekerjaan;
import HumanResource.User;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DoubleFormatTableAlignment;
import Util.NumberFormatTableAlignment;
import Util.Table;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yestin
 */
public class DataPekerjaan extends javax.swing.JFrame {

    Pekerjaan Job = new Pekerjaan();
    Identitas Id = new Identitas();
    JenisPekerjaan JP = new JenisPekerjaan();
    User Usr = new User();
    Outlet Outlet = new Outlet();
    Table Tab = new Table();
    BackgroundImage BI = new BackgroundImage();
    
    int Left = SwingConstants.LEFT;
    int Center = SwingConstants.CENTER;
    int Right = SwingConstants.RIGHT;
    /**
     * Creates new form DataPekerjaan
     */
    public DataPekerjaan() {
        initComponents();
        setTitle("Data Pekerjaan Pegawai");
        BI.BackgroundJPanel(this, pnlDataPekerjaan);
        Job.getPekerjaan(tblPekerjaan);
        JP.getJenisPekerjaan(cboJenisPekerjaan);
        Outlet.getOutlet(cboOutlet);
        Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
        
        NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
        tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPekerjaan = new javax.swing.ButtonGroup();
        pnlDataPekerjaan = new javax.swing.JPanel();
        txtNamaPegawai = new javax.swing.JTextField();
        rbNamaPegawai = new javax.swing.JRadioButton();
        rbJenisPekerjaan = new javax.swing.JRadioButton();
        cboJenisPekerjaan = new javax.swing.JComboBox<>();
        rbSemua = new javax.swing.JRadioButton();
        scrlPekerjaan = new javax.swing.JScrollPane();
        tblPekerjaan = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();
        ftxtKodeJenis = new javax.swing.JFormattedTextField();
        btnEdit = new javax.swing.JButton();
        rbOutlet = new javax.swing.JRadioButton();
        cboOutlet = new javax.swing.JComboBox<>();
        ftxtKodeOutlet = new javax.swing.JFormattedTextField();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNamaPegawai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaPegawai.setForeground(new java.awt.Color(0, 0, 255));
        txtNamaPegawai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaPegawaiKeyPressed(evt);
            }
        });

        rbNamaPegawai.setBackground(new java.awt.Color(255, 255, 255));
        bgPekerjaan.add(rbNamaPegawai);
        rbNamaPegawai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbNamaPegawai.setForeground(new java.awt.Color(0, 0, 255));
        rbNamaPegawai.setText("Nama Pegawai :");
        rbNamaPegawai.setOpaque(false);
        rbNamaPegawai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbNamaPegawaiItemStateChanged(evt);
            }
        });

        rbJenisPekerjaan.setBackground(new java.awt.Color(255, 255, 255));
        bgPekerjaan.add(rbJenisPekerjaan);
        rbJenisPekerjaan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbJenisPekerjaan.setForeground(new java.awt.Color(0, 0, 255));
        rbJenisPekerjaan.setText("Jenis Pekerjaan :");
        rbJenisPekerjaan.setOpaque(false);
        rbJenisPekerjaan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbJenisPekerjaanItemStateChanged(evt);
            }
        });

        cboJenisPekerjaan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboJenisPekerjaan.setForeground(new java.awt.Color(0, 0, 255));
        cboJenisPekerjaan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboJenisPekerjaanItemStateChanged(evt);
            }
        });

        rbSemua.setBackground(new java.awt.Color(255, 255, 255));
        bgPekerjaan.add(rbSemua);
        rbSemua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbSemua.setForeground(new java.awt.Color(0, 0, 255));
        rbSemua.setSelected(true);
        rbSemua.setText("Semua");
        rbSemua.setOpaque(false);
        rbSemua.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSemuaItemStateChanged(evt);
            }
        });

        tblPekerjaan.setForeground(new java.awt.Color(0, 0, 255));
        scrlPekerjaan.setViewportView(tblPekerjaan);

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        ftxtKodeJenis.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeJenis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        rbOutlet.setBackground(new java.awt.Color(255, 255, 255));
        bgPekerjaan.add(rbOutlet);
        rbOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbOutlet.setForeground(new java.awt.Color(0, 0, 255));
        rbOutlet.setText("Outlet :");
        rbOutlet.setOpaque(false);
        rbOutlet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbOutletItemStateChanged(evt);
            }
        });

        cboOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboOutlet.setForeground(new java.awt.Color(0, 0, 255));
        cboOutlet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboOutletItemStateChanged(evt);
            }
        });

        ftxtKodeOutlet.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnRefresh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDataPekerjaanLayout = new javax.swing.GroupLayout(pnlDataPekerjaan);
        pnlDataPekerjaan.setLayout(pnlDataPekerjaanLayout);
        pnlDataPekerjaanLayout.setHorizontalGroup(
            pnlDataPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDataPekerjaanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(38, 38, 38)
                .addComponent(btnEdit)
                .addGap(38, 38, 38)
                .addComponent(btnTutup)
                .addGap(76, 76, 76))
            .addGroup(pnlDataPekerjaanLayout.createSequentialGroup()
                .addComponent(scrlPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlDataPekerjaanLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(pnlDataPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbNamaPegawai)
                    .addComponent(rbJenisPekerjaan)
                    .addComponent(rbSemua)
                    .addComponent(rbOutlet))
                .addGap(136, 136, 136)
                .addGroup(pnlDataPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNamaPegawai)
                    .addComponent(cboJenisPekerjaan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDataPekerjaanLayout.createSequentialGroup()
                        .addComponent(ftxtKodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftxtKodeOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboOutlet, 0, 406, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDataPekerjaanLayout.setVerticalGroup(
            pnlDataPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataPekerjaanLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlDataPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbNamaPegawai))
                .addGap(18, 18, 18)
                .addGroup(pnlDataPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJenisPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboJenisPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDataPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOutlet)
                    .addComponent(cboOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlDataPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSemua)
                    .addGroup(pnlDataPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftxtKodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftxtKodeOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(scrlPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(pnlDataPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDataPekerjaanLayout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(pnlDataPekerjaanLayout.createSequentialGroup()
                        .addGroup(pnlDataPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTutup)
                            .addComponent(btnRefresh))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDataPekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDataPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbNamaPegawaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbNamaPegawaiItemStateChanged
        // TODO add your handling code here:
        txtNamaPegawai.setEnabled(true);
        cboJenisPekerjaan.setEnabled(false);
        cboOutlet.setEnabled(false);
    }//GEN-LAST:event_rbNamaPegawaiItemStateChanged

    private void rbJenisPekerjaanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbJenisPekerjaanItemStateChanged
        // TODO add your handling code here:
        txtNamaPegawai.setEnabled(false);
        cboJenisPekerjaan.setEnabled(true);
        cboOutlet.setEnabled(false);
    }//GEN-LAST:event_rbJenisPekerjaanItemStateChanged

    private void rbSemuaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSemuaItemStateChanged
        // TODO add your handling code here:
        txtNamaPegawai.setEnabled(false);
        cboJenisPekerjaan.setEnabled(false);
        cboOutlet.setEnabled(false);
        
        Job.getPekerjaan(tblPekerjaan);
        Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
    }//GEN-LAST:event_rbSemuaItemStateChanged

    private void txtNamaPegawaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaPegawaiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_A || evt.getKeyCode()==KeyEvent.VK_B || evt.getKeyCode()==KeyEvent.VK_C ||
                evt.getKeyCode()==KeyEvent.VK_D || evt.getKeyCode()==KeyEvent.VK_E || evt.getKeyCode()==KeyEvent.VK_F ||
                evt.getKeyCode()==KeyEvent.VK_G || evt.getKeyCode()==KeyEvent.VK_H || evt.getKeyCode()==KeyEvent.VK_I ||
                evt.getKeyCode()==KeyEvent.VK_J || evt.getKeyCode()==KeyEvent.VK_K || evt.getKeyCode()==KeyEvent.VK_L ||
                evt.getKeyCode()==KeyEvent.VK_M || evt.getKeyCode()==KeyEvent.VK_N || evt.getKeyCode()==KeyEvent.VK_O ||
                evt.getKeyCode()==KeyEvent.VK_P || evt.getKeyCode()==KeyEvent.VK_Q || evt.getKeyCode()==KeyEvent.VK_R ||
                evt.getKeyCode()==KeyEvent.VK_S || evt.getKeyCode()==KeyEvent.VK_T || evt.getKeyCode()==KeyEvent.VK_U ||
                evt.getKeyCode()==KeyEvent.VK_V || evt.getKeyCode()==KeyEvent.VK_W || evt.getKeyCode()==KeyEvent.VK_X ||
                evt.getKeyCode()==KeyEvent.VK_Y || evt.getKeyCode()==KeyEvent.VK_Z || evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode()==KeyEvent.VK_SPACE || evt.getKeyCode()==KeyEvent.VK_0 || evt.getKeyCode()==KeyEvent.VK_1 ||
                evt.getKeyCode()==KeyEvent.VK_2 || evt.getKeyCode()==KeyEvent.VK_3 || evt.getKeyCode()==KeyEvent.VK_4 ||
                evt.getKeyCode()==KeyEvent.VK_5 || evt.getKeyCode()==KeyEvent.VK_6 || evt.getKeyCode()==KeyEvent.VK_7 ||
                evt.getKeyCode()==KeyEvent.VK_8 || evt.getKeyCode()==KeyEvent.VK_9){
            String NamaPegawai = (((String)txtNamaPegawai.getText().trim()).toString());
            Job.getPekerjaan(tblPekerjaan, NamaPegawai);
            Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
            NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
            tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
        }
    }//GEN-LAST:event_txtNamaPegawaiKeyPressed

    private void cboJenisPekerjaanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboJenisPekerjaanItemStateChanged
        // TODO add your handling code here:
        if(cboJenisPekerjaan.getSelectedIndex()==0){
            ftxtKodeJenis.setValue(new Integer(0));
            
            tblPekerjaan.removeAll();
        }
        else{
            String Pekerjaan = ((String)cboJenisPekerjaan.getSelectedItem()).toString();
            int Kode = Pekerjaan.indexOf(' ');
            String KodeJob = Pekerjaan.substring(0, Kode);
            int KodeKerja = Integer.valueOf(KodeJob);
            ftxtKodeJenis.setValue(new Integer(KodeKerja));
            
            Job.getPekerjaan(tblPekerjaan, KodeKerja);
            Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
            NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
            tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
        }
    }//GEN-LAST:event_cboJenisPekerjaanItemStateChanged

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        EditPekerjaan EP = new EditPekerjaan();
        
        int row = tblPekerjaan.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel)tblPekerjaan.getModel();
        
        int KodeKerja = (((Integer)dtm.getValueAt(row, 0)).intValue());
        EP.ftxtKodeKerja.setValue(new Integer(KodeKerja));
        String NoIdentitas = Job.getNoIdentitas(KodeKerja);
        EP.txtNoIdentitas.setText(new String(NoIdentitas));
        String NamaLengkap = Id.getNamaLengkap(NoIdentitas);
        EP.txtNamaLengkap.setText(new String(NamaLengkap));
        int KodeJob = Job.getKodeJob(KodeKerja);
        String NamaJob = JP.getNamaPekerjaan(KodeJob);
        EP.cboPekerjaan.setSelectedItem(String.valueOf(KodeJob+" "+NamaJob));
        EP.ftxtKodeJob.setValue(KodeJob);
        int KodeOutlet = Job.getKodeOutlet(KodeKerja);
        String NamaOutlet = Outlet.getNamaOutlet(KodeOutlet);
        EP.cboOutlet.setSelectedItem(String.valueOf(KodeOutlet+" "+NamaOutlet));
        EP.ftxtKodeOutlet.setValue(new Integer(KodeOutlet));
        Double Gaji = Job.getGaji(KodeKerja);
        EP.ftxtGaji.setValue(new Double(Gaji));
        
        EP.setLocationRelativeTo(this);
        EP.setVisible(true);
        
        if(rbOutlet.isSelected()){
            int KodeCabang = (((Integer)ftxtKodeOutlet.getValue()).intValue());
            Job.getOpportunity(tblPekerjaan, KodeCabang);
            Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
            NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
            tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
        }
        else if(rbJenisPekerjaan.isSelected()){
            int KodeJenis = (((Integer)ftxtKodeJenis.getValue()).intValue());
            Job.getPekerjaan(tblPekerjaan, KodeJenis);
            Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
            NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
            tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
        }
        else if(rbNamaPegawai.isSelected()){
            String Nama = (((String)txtNamaPegawai.getText().trim()).toString());
            Job.getPekerjaan(tblPekerjaan, Nama);
            Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
            NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
            tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
        }
        else if(rbSemua.isSelected()){
            Job.getPekerjaan(tblPekerjaan);
            Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
            NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
            tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void cboOutletItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboOutletItemStateChanged
        // TODO add your handling code here:
        if(cboOutlet.getSelectedIndex()==0){
            ftxtKodeOutlet.setValue(new Integer(0));
            
            tblPekerjaan.removeAll();
        }
        else{
            String Outlet = ((String)cboOutlet.getSelectedItem()).toString();
            int Kode = Outlet.indexOf(' ');
            String KodeOutlet = Outlet.substring(0, Kode);
            int KodeCabang = Integer.valueOf(KodeOutlet);
            ftxtKodeOutlet.setValue(new Integer(KodeCabang));
            
            Job.getOpportunity(tblPekerjaan, KodeCabang);
            Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
            NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
            tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
        }
    }//GEN-LAST:event_cboOutletItemStateChanged

    private void rbOutletItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbOutletItemStateChanged
        // TODO add your handling code here:
        txtNamaPegawai.setEnabled(false);
        cboJenisPekerjaan.setEnabled(false);
        cboOutlet.setEnabled(true);
    }//GEN-LAST:event_rbOutletItemStateChanged

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        if(rbOutlet.isSelected()){
            int KodeCabang = (((Integer)ftxtKodeOutlet.getValue()).intValue());
            Job.getOpportunity(tblPekerjaan, KodeCabang);
            Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
            NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
            tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
        }
        else if(rbJenisPekerjaan.isSelected()){
            int KodeJenis = (((Integer)ftxtKodeJenis.getValue()).intValue());
            Job.getPekerjaan(tblPekerjaan, KodeJenis);
            Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
            NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
            tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
        }
        else if(rbNamaPegawai.isSelected()){
            String Nama = (((String)txtNamaPegawai.getText().trim()).toString());
            Job.getPekerjaan(tblPekerjaan, Nama);
            Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
            NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
            tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
        }
        else if(rbSemua.isSelected()){
            Job.getPekerjaan(tblPekerjaan);
            Tab.TableAlignment7(tblPekerjaan, Center, Center, Left, Center, Center, Center, Right, Center);
            NumberFormatTableAlignment NFTA = new NumberFormatTableAlignment();
            tblPekerjaan.getColumnModel().getColumn(6).setCellRenderer(NFTA);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPekerjaan;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTutup;
    private javax.swing.JComboBox<String> cboJenisPekerjaan;
    private javax.swing.JComboBox<String> cboOutlet;
    private javax.swing.JFormattedTextField ftxtKodeJenis;
    private javax.swing.JFormattedTextField ftxtKodeOutlet;
    private javax.swing.JPanel pnlDataPekerjaan;
    private javax.swing.JRadioButton rbJenisPekerjaan;
    private javax.swing.JRadioButton rbNamaPegawai;
    private javax.swing.JRadioButton rbOutlet;
    private javax.swing.JRadioButton rbSemua;
    private javax.swing.JScrollPane scrlPekerjaan;
    private javax.swing.JTable tblPekerjaan;
    private javax.swing.JTextField txtNamaPegawai;
    // End of variables declaration//GEN-END:variables
}
