/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HumanResource.gui;

import HumanResource.Fitur;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Yestin
 */
public class EditFitur extends javax.swing.JFrame {

    Fitur Fit = new Fitur();
    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form EditFitur
     */
    public EditFitur() {
        initComponents();
        setTitle("Edit Fitur");
        BI.BackgroundJPanel(this, pnlEditFitur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEditFitur = new javax.swing.JPanel();
        lblNamaFitur = new javax.swing.JLabel();
        txtNamaFitur = new javax.swing.JTextField();
        ftxtKodeFitur = new javax.swing.JFormattedTextField();
        btnUpdate = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNamaFitur.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaFitur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaFitur.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaFitur.setText("Nama Fitur :");

        txtNamaFitur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaFitur.setForeground(new java.awt.Color(0, 0, 255));

        ftxtKodeFitur.setEditable(false);
        ftxtKodeFitur.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeFitur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Update.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnTutup.setBackground(new java.awt.Color(255, 255, 255));
        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditFiturLayout = new javax.swing.GroupLayout(pnlEditFitur);
        pnlEditFitur.setLayout(pnlEditFiturLayout);
        pnlEditFiturLayout.setHorizontalGroup(
            pnlEditFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditFiturLayout.createSequentialGroup()
                .addGroup(pnlEditFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditFiturLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(pnlEditFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ftxtKodeFitur, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlEditFiturLayout.createSequentialGroup()
                                .addComponent(lblNamaFitur)
                                .addGap(34, 34, 34)
                                .addComponent(txtNamaFitur, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlEditFiturLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnUpdate)
                        .addGap(43, 43, 43)
                        .addComponent(btnTutup)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pnlEditFiturLayout.setVerticalGroup(
            pnlEditFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditFiturLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ftxtKodeFitur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(pnlEditFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaFitur)
                    .addComponent(txtNamaFitur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(pnlEditFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditFitur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditFitur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(txtNamaFitur.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Nama FItur Belum Diisi");
            return;
        }
        
        Integer KodeFitur = (((Integer)ftxtKodeFitur.getValue()).intValue());
        String NamaFitur = (((String)txtNamaFitur.getText().trim()).toString());
        
        try {
            Fit.UpdateNamaFitur(KodeFitur, NamaFitur);
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Memperbarui Data : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTutup;
    private javax.swing.JButton btnUpdate;
    public javax.swing.JFormattedTextField ftxtKodeFitur;
    private javax.swing.JLabel lblNamaFitur;
    private javax.swing.JPanel pnlEditFitur;
    public javax.swing.JTextField txtNamaFitur;
    // End of variables declaration//GEN-END:variables
}
