/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HumanResource.gui;

import App.Outlet;
import HumanResource.Akses;
import HumanResource.Fitur;
import HumanResource.Identitas;
import HumanResource.JenisPekerjaan;
import HumanResource.Pekerjaan;
import HumanResource.User;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Yestin
 */
public class PekerjaanAkses extends javax.swing.JFrame {

    User Usr = new User();
    Identitas Id = new Identitas();
    Outlet Cab = new Outlet();
    Fitur Fit = new Fitur();
    JenisPekerjaan JP = new JenisPekerjaan();
    BackgroundImage BI = new BackgroundImage();
    Pekerjaan Kerja = new Pekerjaan();
    Akses Akses = new Akses();
    Akses Access[];
    /**
     * Creates new form UsernamePassword
     */
    public PekerjaanAkses() {
        initComponents();
        setTitle("Pemberian Pekerjaan");
        
        BI.BackgroundJPanel(this, pnlUsernamePassword);
        
        txtNoIdentitas.setText(new String());
        txtNoIdentitas.setText(null);
        txtNamaLengkap.setText(new String());
        txtNamaLengkap.setText(null);
        txtUsername.setText(new String());
        txtUsername.setText(null);
        txtPassword.setText(new String());
        txtPassword.setText(null);
        ftxtKodeOutlet.setValue(new Integer(0));
        ftxtGaji.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                    new DecimalFormat("#,##0"))));
        ftxtGaji.setValue(new Double(0.00));
        Cab.getOutlet(cboOutlet);
        Fit.getFitur(tblFitur);
        JP.getJenisPekerjaan(cboJenisPekerjaan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUsernamePassword = new javax.swing.JPanel();
        lblNamaLengkap = new javax.swing.JLabel();
        txtNamaLengkap = new javax.swing.JTextField();
        lblOutlet = new javax.swing.JLabel();
        cboOutlet = new javax.swing.JComboBox<>();
        lblNoIdentitas = new javax.swing.JLabel();
        txtNoIdentitas = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        ftxtKodeOutlet = new javax.swing.JFormattedTextField();
        scrlFitur = new javax.swing.JScrollPane();
        tblFitur = new javax.swing.JTable();
        lblSebagai = new javax.swing.JLabel();
        cboJenisPekerjaan = new javax.swing.JComboBox<>();
        ftxtKodeJenis = new javax.swing.JFormattedTextField();
        lblGaji = new javax.swing.JLabel();
        ftxtGaji = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNamaLengkap.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaLengkap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaLengkap.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaLengkap.setText("Nama Lengkap :");
        lblNamaLengkap.setOpaque(true);

        txtNamaLengkap.setEditable(false);
        txtNamaLengkap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaLengkap.setForeground(new java.awt.Color(0, 0, 255));

        lblOutlet.setBackground(new java.awt.Color(255, 255, 255));
        lblOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblOutlet.setForeground(new java.awt.Color(0, 0, 255));
        lblOutlet.setText("Outlet :");
        lblOutlet.setOpaque(true);

        cboOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboOutlet.setForeground(new java.awt.Color(0, 0, 255));
        cboOutlet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboOutletItemStateChanged(evt);
            }
        });

        lblNoIdentitas.setBackground(new java.awt.Color(255, 255, 255));
        lblNoIdentitas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNoIdentitas.setForeground(new java.awt.Color(0, 0, 255));
        lblNoIdentitas.setText("No Identitas :");
        lblNoIdentitas.setOpaque(true);

        txtNoIdentitas.setEditable(false);
        txtNoIdentitas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoIdentitas.setForeground(new java.awt.Color(0, 0, 255));

        lblUsername.setBackground(new java.awt.Color(255, 255, 255));
        lblUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 0, 255));
        lblUsername.setText("Username :");
        lblUsername.setOpaque(true);

        txtUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 0, 255));

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 0, 255));
        lblPassword.setText("Password :");
        lblPassword.setOpaque(true);

        txtPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 255));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Berikut.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        ftxtKodeOutlet.setEditable(false);
        ftxtKodeOutlet.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tblFitur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblFitur.setForeground(new java.awt.Color(0, 0, 255));
        scrlFitur.setViewportView(tblFitur);

        lblSebagai.setBackground(new java.awt.Color(255, 255, 255));
        lblSebagai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSebagai.setForeground(new java.awt.Color(0, 0, 255));
        lblSebagai.setText("Sebagai :");
        lblSebagai.setOpaque(true);

        cboJenisPekerjaan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboJenisPekerjaan.setForeground(new java.awt.Color(0, 0, 255));
        cboJenisPekerjaan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboJenisPekerjaanItemStateChanged(evt);
            }
        });

        ftxtKodeJenis.setEditable(false);
        ftxtKodeJenis.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeJenis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblGaji.setBackground(new java.awt.Color(255, 255, 255));
        lblGaji.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGaji.setForeground(new java.awt.Color(0, 0, 255));
        lblGaji.setText("Gaji :");
        lblGaji.setOpaque(true);

        ftxtGaji.setForeground(new java.awt.Color(0, 0, 255));
        ftxtGaji.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlUsernamePasswordLayout = new javax.swing.GroupLayout(pnlUsernamePassword);
        pnlUsernamePassword.setLayout(pnlUsernamePasswordLayout);
        pnlUsernamePasswordLayout.setHorizontalGroup(
            pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsernamePasswordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(pnlUsernamePasswordLayout.createSequentialGroup()
                .addComponent(scrlFitur, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlUsernamePasswordLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsernamePasswordLayout.createSequentialGroup()
                        .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(94, 94, 94)
                        .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                            .addComponent(txtPassword)))
                    .addGroup(pnlUsernamePasswordLayout.createSequentialGroup()
                        .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaLengkap)
                            .addComponent(lblOutlet)
                            .addComponent(lblNoIdentitas)
                            .addComponent(lblSebagai)
                            .addComponent(lblGaji))
                        .addGap(63, 63, 63)
                        .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaLengkap)
                            .addComponent(cboOutlet, 0, 372, Short.MAX_VALUE)
                            .addComponent(txtNoIdentitas)
                            .addComponent(cboJenisPekerjaan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ftxtGaji))
                        .addGap(18, 18, 18)
                        .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftxtKodeOutlet, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(ftxtKodeJenis))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUsernamePasswordLayout.setVerticalGroup(
            pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsernamePasswordLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoIdentitas)
                    .addComponent(txtNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaLengkap)
                    .addComponent(txtNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutlet)
                    .addComponent(cboOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtKodeOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSebagai)
                    .addComponent(cboJenisPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtKodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGaji)
                    .addComponent(ftxtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUsernamePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(scrlFitur, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNext)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUsernamePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUsernamePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboOutletItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboOutletItemStateChanged
        // TODO add your handling code here:

            String Outlet = ((String)cboOutlet.getSelectedItem()).toString();
            int Kode = Outlet.indexOf(' ');
            String KodeOutlet = Outlet.substring(0, Kode);
            int KodeCab = Integer.valueOf(KodeOutlet);
            ftxtKodeOutlet.setValue(new Integer(KodeCab));
        
    }//GEN-LAST:event_cboOutletItemStateChanged

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if((((Integer)ftxtKodeOutlet.getValue()).intValue()==0) || ftxtKodeOutlet.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Outlet Belum Dipilih");
            return;
        }
        if(txtUsername.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Username Belum Diisi");
            return;
        }
        if(txtPassword.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Password Belum Diisi");
            return;
        }
        
        String NoIdentitas = (((String)txtNoIdentitas.getText().trim()).toString());
        Usr.setNoIdentitas(NoIdentitas);
        Integer KodeOutlet = (((Integer)ftxtKodeOutlet.getValue()).intValue());
        Usr.setKodeOutlet(KodeOutlet);
        String Username = (((String)txtUsername.getText().trim()).toString());
        Usr.setUsername(Username);
        String Password = (((String)txtPassword.getText().trim()).toString());
        Usr.setPassword(Password);
        
        try {
            Usr.SimpanSHA2();
            DBConnector.getConnection().commit();
            int KodeUsr = Usr.getKodeUser();
            
            DefaultTableModel dtm = (DefaultTableModel)tblFitur.getModel();
            Access = new Akses[dtm.getRowCount()];
            for(int i=0;i<Access.length;i++){
                Access[i] = new Akses();
                
                Access[i].setKodeUser(KodeUsr);
                String NamaFitur = (((String)dtm.getValueAt(i, 1)).toString());
                Access[i].SetNamaFitur(NamaFitur);
                int Akses = 2;
                Access[i].setAkses(Akses);
                
                Access[i].Simpan(KodeUsr, NamaFitur, Akses);
                DBConnector.getConnection().commit();
            }
            
            int KodeJenis = (((Integer)ftxtKodeJenis.getValue()).intValue());
            if(ftxtGaji.getValue() instanceof Double){
                Double Gaji = (((Double)ftxtGaji.getValue()).doubleValue());
                Kerja.Simpan(NoIdentitas, KodeJenis, KodeOutlet, 0, Gaji);
                DBConnector.getConnection().commit();
            }
            else if(ftxtGaji.getValue() instanceof Long){
                Double Gaji = (((Long)ftxtGaji.getValue()).doubleValue());
                Kerja.Simpan(NoIdentitas, KodeJenis, KodeOutlet, 0, Gaji);
                DBConnector.getConnection().commit();
            }
            
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            
            PemberianAksesFitur SAF = new PemberianAksesFitur();
            
            SAF.ftxtKodeUser.setValue(new Integer(KodeUsr));
            String NoId = Usr.getNoIdentitas(KodeUsr);
            String NamaLengkap = Id.getNamaLengkap(NoId);
            SAF.txtNamaLengkap.setText(new String(NamaLengkap));
            int KodeCab = Usr.getKodeOutlet(KodeUsr);
            String NamaOutlet = Cab.getNamaOutlet(new Integer(KodeCab));
            SAF.txtOutlet.setText(NamaOutlet);
            
            Akses.getAkses(SAF.tblAksesFitur, KodeUsr);
            
            SAF.setLocationRelativeTo(this);
            SAF.setVisible(true);
            
            setVisible(false);
            dispose();
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Menyimpan Username, Password, Akses : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void cboJenisPekerjaanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboJenisPekerjaanItemStateChanged
        // TODO add your handling code here:
        if(cboJenisPekerjaan.getSelectedIndex()==0){
            ftxtKodeJenis.setValue(new Integer(0));
        }
        else{
            String Pekerjaan = ((String)cboJenisPekerjaan.getSelectedItem()).toString();
            int Kode = Pekerjaan.indexOf(' ');
            String KodeJob = Pekerjaan.substring(0, Kode);
            int KodeKerja = Integer.valueOf(KodeJob);
            ftxtKodeJenis.setValue(new Integer(KodeKerja));
        }
    }//GEN-LAST:event_cboJenisPekerjaanItemStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cboJenisPekerjaan;
    public javax.swing.JComboBox<String> cboOutlet;
    private javax.swing.JFormattedTextField ftxtGaji;
    private javax.swing.JFormattedTextField ftxtKodeJenis;
    private javax.swing.JFormattedTextField ftxtKodeOutlet;
    private javax.swing.JLabel lblGaji;
    private javax.swing.JLabel lblNamaLengkap;
    private javax.swing.JLabel lblNoIdentitas;
    private javax.swing.JLabel lblOutlet;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSebagai;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlUsernamePassword;
    private javax.swing.JScrollPane scrlFitur;
    public javax.swing.JTable tblFitur;
    public javax.swing.JTextField txtNamaLengkap;
    public javax.swing.JTextField txtNoIdentitas;
    public javax.swing.JTextField txtPassword;
    public javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
