/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HumanResource.gui;

import HumanResource.Akses;
import HumanResource.Fitur;
import HumanResource.User;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import Util.Table;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yestin
 */
public class RegistrasiFitur extends javax.swing.JFrame {

    Fitur Fit = new Fitur();
    User Usr = new User();
    BackgroundImage BI = new BackgroundImage();
    User User[];
    Akses Aks = new Akses();
    Akses Akses[];
    Table Table = new Table();
    /**
     * Creates new form RegistrasiFitur
     */
    public RegistrasiFitur() {
        initComponents();
        setTitle("Registrasi Fitur");
        txtNamaFitur.setText(new String());
        txtNamaFitur.setText(null);
        
        int Left = SwingConstants.LEFT;
        int Center = SwingConstants.CENTER;
        int Right = SwingConstants.RIGHT;
        
        BI.BackgroundJPanel(this, pnlRegistrasiFitur);
        
        Usr.getUser(tblUser);
        Table.TableAlignment5(tblUser, Center, Left, Left, Left, Left, Center);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlUser = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        pnlRegistrasiFitur = new javax.swing.JPanel();
        lblNamaFitur = new javax.swing.JLabel();
        txtNamaFitur = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        tblUser.setForeground(new java.awt.Color(0, 0, 255));
        scrlUser.setViewportView(tblUser);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        lblNamaFitur.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaFitur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaFitur.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaFitur.setText("Nama Fitur :");
        lblNamaFitur.setOpaque(true);

        txtNamaFitur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaFitur.setForeground(new java.awt.Color(0, 0, 255));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrasiFiturLayout = new javax.swing.GroupLayout(pnlRegistrasiFitur);
        pnlRegistrasiFitur.setLayout(pnlRegistrasiFiturLayout);
        pnlRegistrasiFiturLayout.setHorizontalGroup(
            pnlRegistrasiFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiFiturLayout.createSequentialGroup()
                .addGroup(pnlRegistrasiFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrasiFiturLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblNamaFitur)
                        .addGap(51, 51, 51)
                        .addComponent(txtNamaFitur, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistrasiFiturLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnSimpan)
                        .addGap(75, 75, 75)
                        .addComponent(btnTutup)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnlRegistrasiFiturLayout.setVerticalGroup(
            pnlRegistrasiFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiFiturLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnlRegistrasiFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaFitur)
                    .addComponent(txtNamaFitur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(pnlRegistrasiFiturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiFitur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegistrasiFitur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNamaFitur.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Nama Fitur Belum Diisi");
            return;
        }
        
        String NamaFitur = (((String)txtNamaFitur.getText().trim()).toString());
        Fit.setNamaFitur(NamaFitur);
        
        try {
            Fit.Simpan(NamaFitur);
            
            DefaultTableModel dtm = (DefaultTableModel)tblUser.getModel();
            
            Akses = new Akses[dtm.getRowCount()];
            for(int i=0;i<Akses.length;i++){
                Akses[i] = new Akses();
                
                int KodeUser = (((Integer)dtm.getValueAt(i, 0)).intValue());
                Akses[i].Simpan(KodeUser, NamaFitur, 2);
            }
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            
            txtNamaFitur.setText(null);
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Registrasi Fitur : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel lblNamaFitur;
    private javax.swing.JPanel pnlRegistrasiFitur;
    private javax.swing.JScrollPane scrlUser;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtNamaFitur;
    // End of variables declaration//GEN-END:variables
}
