/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HumanResource.gui;

import HumanResource.JenisPekerjaan;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Yestin
 */
public class RegistrasiJenisPekerjaan extends javax.swing.JFrame {

    JenisPekerjaan JP = new JenisPekerjaan();
    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form RegistrasiJenisPekerjaan
     */
    public RegistrasiJenisPekerjaan() {
        initComponents();
        BI.BackgroundJPanel(this, pnlRegistrasiJenisPekerjaan);
        setTitle("Registrasi Jenis Pekerjaan");
        try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlRegistrasiJenisPekerjaan.setOpaque(false);
            Background.add(pnlRegistrasiJenisPekerjaan,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        } 
        catch (IOException ex) {
            Logger.getLogger(RegistrasiKategori.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNamaPekerjaan.setText(new String());
        txtNamaPekerjaan.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistrasiJenisPekerjaan = new javax.swing.JPanel();
        lblNamaPekerjaan = new javax.swing.JLabel();
        txtNamaPekerjaan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNamaPekerjaan.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaPekerjaan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaPekerjaan.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaPekerjaan.setText("Nama Pekerjaan :");
        lblNamaPekerjaan.setOpaque(true);

        txtNamaPekerjaan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaPekerjaan.setForeground(new java.awt.Color(0, 0, 255));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrasiJenisPekerjaanLayout = new javax.swing.GroupLayout(pnlRegistrasiJenisPekerjaan);
        pnlRegistrasiJenisPekerjaan.setLayout(pnlRegistrasiJenisPekerjaanLayout);
        pnlRegistrasiJenisPekerjaanLayout.setHorizontalGroup(
            pnlRegistrasiJenisPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiJenisPekerjaanLayout.createSequentialGroup()
                .addGroup(pnlRegistrasiJenisPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrasiJenisPekerjaanLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblNamaPekerjaan)
                        .addGap(58, 58, 58)
                        .addComponent(txtNamaPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistrasiJenisPekerjaanLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnSimpan)
                        .addGap(69, 69, 69)
                        .addComponent(btnTutup)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pnlRegistrasiJenisPekerjaanLayout.setVerticalGroup(
            pnlRegistrasiJenisPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiJenisPekerjaanLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(pnlRegistrasiJenisPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaPekerjaan)
                    .addComponent(txtNamaPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(pnlRegistrasiJenisPekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiJenisPekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiJenisPekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNamaPekerjaan.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Nama Pekerjaan Belum Diisi");
            return;
        }
        
        String NamaPekerjaan = (((String)txtNamaPekerjaan.getText().trim()).toString());
        
        try {
            JP.Simpan(NamaPekerjaan);
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            
            txtNamaPekerjaan.setText(null);
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Registrasi Jenis Pekerjaan : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel lblNamaPekerjaan;
    private javax.swing.JPanel pnlRegistrasiJenisPekerjaan;
    private javax.swing.JTextField txtNamaPekerjaan;
    // End of variables declaration//GEN-END:variables
}
