/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HumanResource.gui;

import HumanResource.Sift;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import Util.DateTimeConverter;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
/**
 *
 * @author Yestin
 */
public class TambahSift extends javax.swing.JFrame {

    Sift Sift = new Sift();
    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form PengaturanSift
     */
    public TambahSift() {
        initComponents();
        setTitle("Tambah Sift");
        BI.BackgroundJPanel(this, pnlTambahSift);
//        Component ComJamMulai = spnJamMulai.getEditor().getComponent(0);
//        ComJamMulai.setForeground(Color.BLUE);
//        Component ComMenitMulai = spnMenitMulai.getEditor().getComponent(0);
//        ComMenitMulai.setForeground(Color.BLUE);
//        Component ComDetikMulai = spnDetikMulai.getEditor().getComponent(0);
//        ComDetikMulai.setForeground(Color.BLUE);
//        
//        Component ComJamSelesai = spnJamSelesai.getEditor().getComponent(0);
//        ComJamSelesai.setForeground(Color.BLUE);
//        Component ComMenitSelesai = spnMenitSelesai.getEditor().getComponent(0);
//        ComJamSelesai.setForeground(Color.BLUE);
//        Component ComDetikSelesai = spnDetikSelesai.getEditor().getComponent(0);
//        ComDetikSelesai.setForeground(Color.BLUE);
        
        int Sft = Sift.getLastSift();
        ftxtSift.setValue(new Integer(Sft+1));
        
//        java.util.Date Tanggal = new java.util.Date();
//        SpinnerDateModel SH = new SpinnerDateModel(Tanggal, null, null, Calendar.HOUR);
//        spnJamMulai = new JSpinner(SH);
//        JSpinner.DateEditor DeJam = new JSpinner.DateEditor(spnJamMulai,"hh aa");
//        spnJamMulai.setEditor(DeJam);
        
        String StartTime = "13:00:00";
        String JamMulai = DateTimeConverter.ConvertToTime(StartTime);
        txtWaktuMulai.setText(JamMulai);
        
        String EndTime = "13:00:00";
        String JamSelesai = DateTimeConverter.ConvertToTime(EndTime);
        txtWaktuSelesai.setText(JamSelesai);
        
        try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlTambahSift.setOpaque(false);
            Background.add(pnlTambahSift,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        } 
        catch (IOException ex) {
            Logger.getLogger(RegistrasiKategori.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        pnlTambahSift = new javax.swing.JPanel();
        lblSift = new javax.swing.JLabel();
        ftxtSift = new javax.swing.JFormattedTextField();
        lblWaktuMulai = new javax.swing.JLabel();
        lblWaktuSelesai = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        txtWaktuMulai = new javax.swing.JTextField();
        txtWaktuSelesai = new javax.swing.JTextField();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSift.setBackground(new java.awt.Color(255, 255, 255));
        lblSift.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSift.setForeground(new java.awt.Color(0, 0, 255));
        lblSift.setText("Sift :");
        lblSift.setOpaque(true);

        ftxtSift.setEditable(false);
        ftxtSift.setForeground(new java.awt.Color(0, 0, 255));
        ftxtSift.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblWaktuMulai.setBackground(new java.awt.Color(255, 255, 255));
        lblWaktuMulai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblWaktuMulai.setForeground(new java.awt.Color(0, 0, 255));
        lblWaktuMulai.setText("Waktu Mulai :");
        lblWaktuMulai.setOpaque(true);

        lblWaktuSelesai.setBackground(new java.awt.Color(255, 255, 255));
        lblWaktuSelesai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblWaktuSelesai.setForeground(new java.awt.Color(0, 0, 255));
        lblWaktuSelesai.setText("Waktu Selesai :");
        lblWaktuSelesai.setOpaque(true);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        txtWaktuMulai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtWaktuMulai.setForeground(new java.awt.Color(0, 0, 255));

        txtWaktuSelesai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtWaktuSelesai.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlTambahSiftLayout = new javax.swing.GroupLayout(pnlTambahSift);
        pnlTambahSift.setLayout(pnlTambahSiftLayout);
        pnlTambahSiftLayout.setHorizontalGroup(
            pnlTambahSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTambahSiftLayout.createSequentialGroup()
                .addGroup(pnlTambahSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTambahSiftLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnSimpan)
                        .addGap(71, 71, 71)
                        .addComponent(btnTutup))
                    .addGroup(pnlTambahSiftLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(pnlTambahSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSift)
                            .addComponent(lblWaktuMulai)
                            .addComponent(lblWaktuSelesai))
                        .addGap(52, 52, 52)
                        .addGroup(pnlTambahSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftxtSift, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWaktuMulai)
                            .addComponent(txtWaktuSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))))
                .addGap(0, 99, Short.MAX_VALUE))
        );
        pnlTambahSiftLayout.setVerticalGroup(
            pnlTambahSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTambahSiftLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlTambahSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSift)
                    .addComponent(ftxtSift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlTambahSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWaktuMulai)
                    .addComponent(txtWaktuMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlTambahSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWaktuSelesai)
                    .addComponent(txtWaktuSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(pnlTambahSiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTambahSift, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTambahSift, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        int Sft = (((Integer)ftxtSift.getValue()).intValue());
        
        String WaktuMulai = (((String)txtWaktuMulai.getText().trim()).toString());
        String WaktuSelesai = (((String)txtWaktuSelesai.getText().trim()).toString());
        
        try {
            Sift.Simpan(Sft, WaktuMulai, WaktuSelesai);
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            
            int LastSift = Sift.getLastSift();
            ftxtSift.setValue(new Integer(LastSift+1));
            
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Menyimpan Sift : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    public javax.swing.JFormattedTextField ftxtSift;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblSift;
    private javax.swing.JLabel lblWaktuMulai;
    private javax.swing.JLabel lblWaktuSelesai;
    private javax.swing.JPanel pnlTambahSift;
    private javax.swing.JTextField txtWaktuMulai;
    private javax.swing.JTextField txtWaktuSelesai;
    // End of variables declaration//GEN-END:variables
}
