/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi.gui;

import Transaksi.Poin;
import Transaksi.RincianTransaksi;
import Transaksi.Transaksi;
import Util.BackgroundImage;
import Util.DBConnector;
import Util.Table;
import java.awt.Dialog;
import java.io.File;
import java.net.URL;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.type.OrientationEnum;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Yestin
 */
public class DetailTransaksi extends javax.swing.JDialog {

    Table Tab = new Table();
    BackgroundImage BI = new BackgroundImage();
    RincianTransaksi RT = new RincianTransaksi();
    Transaksi trans = new Transaksi();
    Poin Poin = new Poin();
    /**
     * Creates new form RincianTransaksi
     */
    public DetailTransaksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Rincian Transaksi");
        BI.BackgroundJPanel(this, pnlRincianTransaksi);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRincianTransaksi = new javax.swing.JPanel();
        dchTglTransaksi = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtNamaBC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ftxtNoNota = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOutlet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtJenisTransaksi = new javax.swing.JTextField();
        lblJenisPembayaran = new javax.swing.JLabel();
        txtJenisPembayaran = new javax.swing.JTextField();
        scrlNota = new javax.swing.JScrollPane();
        tblNota = new javax.swing.JTable();
        ftxtSubTotal = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ftxtPPN = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        ftxtDiskon = new javax.swing.JFormattedTextField();
        ftxtGrandTotal = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ftxtTotalPoin = new javax.swing.JFormattedTextField();
        txtNamaUser = new javax.swing.JTextField();
        txtNamaBisnis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Nama Business Contact :");

        txtNamaBC.setEditable(false);
        txtNamaBC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaBC.setForeground(new java.awt.Color(0, 0, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("No Nota :");

        ftxtNoNota.setEditable(false);
        ftxtNoNota.setForeground(new java.awt.Color(0, 0, 255));
        ftxtNoNota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Outlet :");

        txtOutlet.setEditable(false);
        txtOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtOutlet.setForeground(new java.awt.Color(0, 0, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Jenis Transaksi :");

        txtJenisTransaksi.setEditable(false);
        txtJenisTransaksi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtJenisTransaksi.setForeground(new java.awt.Color(0, 0, 255));

        lblJenisPembayaran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblJenisPembayaran.setForeground(new java.awt.Color(0, 0, 255));
        lblJenisPembayaran.setText("Jenis Pembayaran :");

        txtJenisPembayaran.setEditable(false);
        txtJenisPembayaran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtJenisPembayaran.setForeground(new java.awt.Color(0, 0, 255));

        scrlNota.setViewportView(tblNota);

        ftxtSubTotal.setEditable(false);
        ftxtSubTotal.setForeground(new java.awt.Color(0, 0, 255));
        ftxtSubTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Sub Total :");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("PPN 11% :");

        ftxtPPN.setEditable(false);
        ftxtPPN.setForeground(new java.awt.Color(0, 0, 255));
        ftxtPPN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Diskon(%) :");

        ftxtDiskon.setEditable(false);
        ftxtDiskon.setForeground(new java.awt.Color(0, 0, 204));
        ftxtDiskon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        ftxtGrandTotal.setEditable(false);
        ftxtGrandTotal.setForeground(new java.awt.Color(0, 0, 255));
        ftxtGrandTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Grand Total :");

        btnCetak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cetak.png"))); // NOI18N
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Total Poin :");

        ftxtTotalPoin.setEditable(false);
        ftxtTotalPoin.setForeground(new java.awt.Color(0, 0, 255));
        ftxtTotalPoin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtNamaUser.setEditable(false);
        txtNamaUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtNamaBisnis.setEditable(false);
        txtNamaBisnis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaBisnis.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlRincianTransaksiLayout = new javax.swing.GroupLayout(pnlRincianTransaksi);
        pnlRincianTransaksi.setLayout(pnlRincianTransaksiLayout);
        pnlRincianTransaksiLayout.setHorizontalGroup(
            pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlNota)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRincianTransaksiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ftxtGrandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(ftxtPPN, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftxtSubTotal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftxtDiskon, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
            .addGroup(pnlRincianTransaksiLayout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(btnCetak)
                .addGap(67, 67, 67)
                .addComponent(btnTutup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRincianTransaksiLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRincianTransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 704, Short.MAX_VALUE)
                        .addComponent(dchTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(pnlRincianTransaksiLayout.createSequentialGroup()
                        .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(lblJenisPembayaran)
                            .addComponent(jLabel9))
                        .addGap(68, 68, 68)
                        .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaBC)
                            .addComponent(txtOutlet, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                            .addComponent(txtJenisTransaksi)
                            .addComponent(txtJenisPembayaran)
                            .addComponent(ftxtTotalPoin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRincianTransaksiLayout.createSequentialGroup()
                                .addComponent(txtNamaUser)
                                .addGap(172, 172, 172))
                            .addGroup(pnlRincianTransaksiLayout.createSequentialGroup()
                                .addComponent(txtNamaBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        pnlRincianTransaksiLayout.setVerticalGroup(
            pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRincianTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchTglTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(ftxtNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamaBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJenisTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJenisPembayaran)
                    .addComponent(txtJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtTotalPoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addComponent(scrlNota, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftxtPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftxtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRincianTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCetak)
                    .addComponent(btnTutup))
                .addGap(177, 177, 177))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRincianTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRincianTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        if(ftxtNoNota.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "No Nota Belum Ada");
            return;
        }
        int NoNota = (((Integer)ftxtNoNota.getValue()).intValue());
        int KodeBC = trans.getNoNota(NoNota);
        Calendar TglTransaksi = dchTglTransaksi.getCalendar();
        String NamaUser = txtNamaUser.getText().trim();
        String NamaBisnis = txtNamaBisnis.getText().trim();
        Double PPN = (((Double)ftxtPPN.getValue()).doubleValue());
        Double Diskon = (((Double)ftxtDiskon.getValue()).doubleValue());
        JasperPrint JP = null;
        String ReportPath = "Report/";
        String ReportFileName = null;
        URL Resource = this.getClass().getResource(ReportPath);
        try {
            java.util.Map<String, Object> params = new java.util.HashMap<String, Object>();
//            java.util.Map<String, Object> paramsUser = new java.util.HashMap<String, Object>();
//            java.util.Map<String, Object> paramsNamaBisnis = new java.util.HashMap<String, Object>();
//            java.util.Map<String, Object> paramsNamaItem = new java.util.HashMap<String, Object>();
//            java.util.Map<String, Object> paramsNamaSatuan = new java.util.HashMap<String, Object>();
//            java.util.Map<String, Object> paramsKuantias = new java.util.HashMap<String, Object>();
//            java.util.Map<String, Object> paramsHarga = new java.util.HashMap<String, Object>();
            
            
            params.put("NoNota", Integer.valueOf(NoNota));
//            params.put("TglTransaksi", String.valueOf(TglTransaksi));
//            params.put("NamaUser", String.valueOf(NamaUser));
//            params.put("NamaBisnis", String.valueOf(NamaBisnis));
//            
//            DefaultTableModel dtm = (DefaultTableModel)tblNota.getModel();
//            
            int rowcount = RT.getRowCount(NoNota);
//            
//            for(int i=0;i<dtm.getRowCount();i++){
//                String NamaItem = (((String)dtm.getValueAt(i, 1)).toString());
//                params.put("NamaItem", String.valueOf(NamaItem));
//                String Satuan = (((String)dtm.getValueAt(i, 2)).toString());
//                params.put("NamaSatuan", String.valueOf(Satuan));
//                Double Kuantitas= (((Double)dtm.getValueAt(i, 3)).doubleValue());
//                params.put("Kuantitas", Double.valueOf(Kuantitas));
//                Double Harga = (((Double)dtm.getValueAt(i, 4)).doubleValue());
//                params.put("Harga", Double.valueOf(Harga));
////                Double Total = (((Double)dtm.getValueAt(i, 5)).doubleValue());
////                params.put("Total", Double.valueOf(Total));
//            }
            ReportFileName = ReportPath + "StrukPenjualan";
            if(Poin.getTotalPoin(NoNota)>0){
                ReportFileName = ReportFileName + "Poin";
            }
            if(PPN > 0){
                ReportFileName = ReportFileName + "PPN";
            }
            if(Diskon > 0){
                ReportFileName = ReportFileName + "Diskon";
            }
            ReportFileName = ReportFileName+".jrxml";
            int padd = rowcount < 3 ? 0 : 35*(rowcount-2);
            int pageHeight = 315+padd;
            
            File file = new File(ReportFileName);
            JasperDesign jasperDesign = JRXmlLoader.load(file);
            JasperReport report = JasperCompileManager.compileReport(jasperDesign);
            JP = JasperFillManager.fillReport(report, params, DBConnector.getConnection());
            JP.setOrientation(OrientationEnum.PORTRAIT);
            JP.setPageHeight(pageHeight);
            
            JP.setOrientation(OrientationEnum.PORTRAIT);
            JasperViewer JV = new JasperViewer(JP, true);
            JV.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
            JV.setVisible(true);
            JV.setFitPageZoomRatio();
        } 
        catch (JRException e) {
            e.printStackTrace();
            return;
        }
        catch (Exception e){
            e.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTutup;
    public com.toedter.calendar.JDateChooser dchTglTransaksi;
    public javax.swing.JFormattedTextField ftxtDiskon;
    public javax.swing.JFormattedTextField ftxtGrandTotal;
    public javax.swing.JFormattedTextField ftxtNoNota;
    public javax.swing.JFormattedTextField ftxtPPN;
    public javax.swing.JFormattedTextField ftxtSubTotal;
    private javax.swing.JFormattedTextField ftxtTotalPoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblJenisPembayaran;
    private javax.swing.JPanel pnlRincianTransaksi;
    private javax.swing.JScrollPane scrlNota;
    public javax.swing.JTable tblNota;
    public javax.swing.JTextField txtJenisPembayaran;
    public javax.swing.JTextField txtJenisTransaksi;
    public javax.swing.JTextField txtNamaBC;
    public javax.swing.JTextField txtNamaBisnis;
    public javax.swing.JTextField txtNamaUser;
    public javax.swing.JTextField txtOutlet;
    // End of variables declaration//GEN-END:variables
}
