/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi.gui;

import Inventori.gui.RegistrasiKategori;
import Transaksi.BusinessContact;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Yestin
 */
public class EditSupplier extends javax.swing.JDialog {

    BusinessContact BC = new BusinessContact();
    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form EditSupplier
     */
    public EditSupplier(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Edit Supplier");
        BI.BackgroundJPanel(this, pnlEditSupplier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEditSupplier = new javax.swing.JPanel();
        ftxtKodeBC = new javax.swing.JFormattedTextField();
        lblNamaSupplier = new javax.swing.JLabel();
        txtNamaSupplier = new javax.swing.JTextField();
        lblAlamat = new javax.swing.JLabel();
        scrlAlamat = new javax.swing.JScrollPane();
        txaAlamat = new javax.swing.JTextArea();
        txtKelurahan = new javax.swing.JTextField();
        lblKelurahan = new javax.swing.JLabel();
        lblKecamatan = new javax.swing.JLabel();
        txtKecamatan = new javax.swing.JTextField();
        lblKota = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        lblTelpon = new javax.swing.JLabel();
        txtTelpon1 = new javax.swing.JTextField();
        txtTelpon2 = new javax.swing.JTextField();
        lblNoHP = new javax.swing.JLabel();
        txtNoHP1 = new javax.swing.JTextField();
        txtNoHP2 = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ftxtKodeBC.setEditable(false);
        ftxtKodeBC.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeBC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblNamaSupplier.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaSupplier.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaSupplier.setText("Nama Supplier :");

        txtNamaSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaSupplier.setForeground(new java.awt.Color(0, 0, 255));

        lblAlamat.setBackground(new java.awt.Color(255, 255, 255));
        lblAlamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(0, 0, 255));
        lblAlamat.setText("Alamat :");

        scrlAlamat.setForeground(new java.awt.Color(0, 0, 255));

        txaAlamat.setColumns(20);
        txaAlamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txaAlamat.setForeground(new java.awt.Color(0, 0, 255));
        txaAlamat.setRows(5);
        scrlAlamat.setViewportView(txaAlamat);

        txtKelurahan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKelurahan.setForeground(new java.awt.Color(0, 0, 255));

        lblKelurahan.setBackground(new java.awt.Color(255, 255, 255));
        lblKelurahan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKelurahan.setForeground(new java.awt.Color(0, 0, 255));
        lblKelurahan.setText("Kelurahan/Desa :");

        lblKecamatan.setBackground(new java.awt.Color(255, 255, 255));
        lblKecamatan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKecamatan.setForeground(new java.awt.Color(0, 0, 255));
        lblKecamatan.setText("Kecamatan :");

        txtKecamatan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKecamatan.setForeground(new java.awt.Color(0, 0, 255));

        lblKota.setBackground(new java.awt.Color(255, 255, 255));
        lblKota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKota.setForeground(new java.awt.Color(0, 0, 255));
        lblKota.setText("Kabupaten/Kota :");

        txtKota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKota.setForeground(new java.awt.Color(0, 0, 255));

        lblTelpon.setBackground(new java.awt.Color(255, 255, 255));
        lblTelpon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTelpon.setForeground(new java.awt.Color(0, 0, 255));
        lblTelpon.setText("Telpon :");

        txtTelpon1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelpon1.setForeground(new java.awt.Color(0, 0, 255));

        txtTelpon2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelpon2.setForeground(new java.awt.Color(0, 0, 255));

        lblNoHP.setBackground(new java.awt.Color(255, 255, 255));
        lblNoHP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNoHP.setForeground(new java.awt.Color(0, 0, 255));
        lblNoHP.setText("No HP/WA :");

        txtNoHP1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoHP1.setForeground(new java.awt.Color(0, 0, 255));

        txtNoHP2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoHP2.setForeground(new java.awt.Color(0, 0, 255));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditSupplierLayout = new javax.swing.GroupLayout(pnlEditSupplier);
        pnlEditSupplier.setLayout(pnlEditSupplierLayout);
        pnlEditSupplierLayout.setHorizontalGroup(
            pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditSupplierLayout.createSequentialGroup()
                .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditSupplierLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ftxtKodeBC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlEditSupplierLayout.createSequentialGroup()
                                .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditSupplierLayout.createSequentialGroup()
                                        .addComponent(lblNamaSupplier)
                                        .addGap(66, 66, 66))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditSupplierLayout.createSequentialGroup()
                                        .addComponent(lblAlamat)
                                        .addGap(115, 115, 115))
                                    .addGroup(pnlEditSupplierLayout.createSequentialGroup()
                                        .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblKelurahan)
                                            .addComponent(lblKecamatan)
                                            .addComponent(lblKota)
                                            .addComponent(lblNoHP)
                                            .addComponent(lblTelpon))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamaSupplier)
                                    .addComponent(scrlAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                                    .addComponent(txtKelurahan)
                                    .addComponent(txtKecamatan)
                                    .addComponent(txtKota)
                                    .addGroup(pnlEditSupplierLayout.createSequentialGroup()
                                        .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNoHP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(txtTelpon1, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelpon2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNoHP2)))))))
                    .addGroup(pnlEditSupplierLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnSimpan)
                        .addGap(42, 42, 42)
                        .addComponent(btnTutup)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnlEditSupplierLayout.setVerticalGroup(
            pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ftxtKodeBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaSupplier)
                    .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlamat)
                    .addComponent(scrlAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKelurahan))
                .addGap(18, 18, 18)
                .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKecamatan)
                    .addComponent(txtKecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKota)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelpon)
                    .addComponent(txtTelpon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelpon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoHP)
                    .addComponent(txtNoHP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoHP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(pnlEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnTutup))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNamaSupplier.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Nama Supplier Harus Diisi");
            return;
        }
        if(txaAlamat.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Alamat Harus Diisi");
            return;
        }
        if(txtKelurahan.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Kelurahan/Desa Harus Diisi");
            return;
        }
        if(txtKecamatan.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Kecamatan Harus Diisi");
            return;
        }
        if(txtKota.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Kabupatan/Kota Harus Diisi");
            return;
        }
        
        int KodeBC = (((Integer)ftxtKodeBC.getValue()).intValue());
        String NamaSupplier = (((String)txtNamaSupplier.getText().trim()).toString());
        String Alamat = (((String)txaAlamat.getText().trim()).toString());
        String Kelurahan = (((String)txtKelurahan.getText().trim()).toString());
        String Kecamatan = (((String)txtKecamatan.getText().trim()).toString());
        String Kota = (((String)txtKota.getText().trim()).toString());
        String Telpon1 = (((String)txtTelpon1.getText().trim()).toString());
        String Telpon2 = (((String)txtTelpon2.getText().trim()).toString());
        String NoHP1 = (((String)txtNoHP1.getText().trim()).toString());
        String NoHP2 = (((String)txtNoHP2.getText().trim()).toString());
        
        try {
            BC.UpdateNamaBC(KodeBC, NamaSupplier);
            BC.UpdateAlamat(KodeBC, Alamat);
            BC.UpdateKelurahan(KodeBC, Kelurahan);
            BC.UpdateKecamatan(KodeBC, Kecamatan);
            BC.UpdateKota(KodeBC, Kota);
            if(Telpon1!=null || txtTelpon1.getText().trim().length()>0){
                BC.UpdateTelpon1(KodeBC, Telpon1);
            }
            if(Telpon2!=null || txtTelpon2.getText().trim().length()>0){
                BC.UpdateTelpon2(KodeBC, Telpon2);
            }
            if(NoHP1!=null || txtNoHP1.getText().trim().length()>0){
                BC.UpdateNoHP1(KodeBC, NoHP1);
            }
            if(NoHP2!=null || txtNoHP2.getText().trim().length()>0){
                BC.UpdateNoHP2(KodeBC, NoHP2);
            }
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Memperbarui Data : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    public javax.swing.JFormattedTextField ftxtKodeBC;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblKecamatan;
    private javax.swing.JLabel lblKelurahan;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblNamaSupplier;
    private javax.swing.JLabel lblNoHP;
    private javax.swing.JLabel lblTelpon;
    private javax.swing.JPanel pnlEditSupplier;
    private javax.swing.JScrollPane scrlAlamat;
    public javax.swing.JTextArea txaAlamat;
    public javax.swing.JTextField txtKecamatan;
    public javax.swing.JTextField txtKelurahan;
    public javax.swing.JTextField txtKota;
    public javax.swing.JTextField txtNamaSupplier;
    public javax.swing.JTextField txtNoHP1;
    public javax.swing.JTextField txtNoHP2;
    public javax.swing.JTextField txtTelpon1;
    public javax.swing.JTextField txtTelpon2;
    // End of variables declaration//GEN-END:variables
}
