/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi.gui;

import Financial.Penyimpanan;
import Inventori.gui.RegistrasiKategori;
import Transaksi.JenisPembayaran;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Yestin
 */
public class EditJenisPembayaran extends javax.swing.JDialog {

    JenisPembayaran JP = new JenisPembayaran();
    Penyimpanan Penyimpanan = new Penyimpanan();
    BackgroundImage BI = new BackgroundImage();
    /**
     * 
     * Creates new form EditJenisPembayaran
     */
    public EditJenisPembayaran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Edit JenisPembayaran");
        BI.BackgroundJPanel(this, pnlEditJenisPembayaran);
        Penyimpanan.getPenyimpanan(cboPenyimpanan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEditJenisPembayaran = new javax.swing.JPanel();
        lblJenisPembayaran = new javax.swing.JLabel();
        txtJenisPembayaran = new javax.swing.JTextField();
        ftxtKodeJenis = new javax.swing.JFormattedTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        lblPenyimpanan = new javax.swing.JLabel();
        cboPenyimpanan = new javax.swing.JComboBox<>();
        ftxtKodePenyimpanan = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblJenisPembayaran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblJenisPembayaran.setForeground(new java.awt.Color(0, 0, 255));
        lblJenisPembayaran.setText("Jenis Pembayaran :");

        txtJenisPembayaran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtJenisPembayaran.setForeground(new java.awt.Color(0, 0, 255));

        ftxtKodeJenis.setEditable(false);
        ftxtKodeJenis.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeJenis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        lblPenyimpanan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPenyimpanan.setForeground(new java.awt.Color(0, 0, 255));
        lblPenyimpanan.setText("Penyimpanan :");

        cboPenyimpanan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboPenyimpanan.setForeground(new java.awt.Color(0, 0, 255));
        cboPenyimpanan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPenyimpananItemStateChanged(evt);
            }
        });

        ftxtKodePenyimpanan.setEditable(false);
        ftxtKodePenyimpanan.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodePenyimpanan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlEditJenisPembayaranLayout = new javax.swing.GroupLayout(pnlEditJenisPembayaran);
        pnlEditJenisPembayaran.setLayout(pnlEditJenisPembayaranLayout);
        pnlEditJenisPembayaranLayout.setHorizontalGroup(
            pnlEditJenisPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditJenisPembayaranLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(75, 75, 75)
                .addComponent(btnTutup)
                .addGap(165, 165, 165))
            .addGroup(pnlEditJenisPembayaranLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlEditJenisPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEditJenisPembayaranLayout.createSequentialGroup()
                        .addComponent(ftxtKodePenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ftxtKodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEditJenisPembayaranLayout.createSequentialGroup()
                        .addGroup(pnlEditJenisPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditJenisPembayaranLayout.createSequentialGroup()
                                .addComponent(lblJenisPembayaran)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditJenisPembayaranLayout.createSequentialGroup()
                                .addComponent(lblPenyimpanan)
                                .addGap(87, 87, 87)))
                        .addGroup(pnlEditJenisPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJenisPembayaran)
                            .addComponent(cboPenyimpanan, 0, 383, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlEditJenisPembayaranLayout.setVerticalGroup(
            pnlEditJenisPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditJenisPembayaranLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlEditJenisPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftxtKodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtKodePenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnlEditJenisPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJenisPembayaran)
                    .addComponent(txtJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlEditJenisPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPenyimpanan)
                    .addComponent(cboPenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(pnlEditJenisPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditJenisPembayaranLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan))
                    .addGroup(pnlEditJenisPembayaranLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTutup)))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditJenisPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditJenisPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtJenisPembayaran.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Jenis Pembayaran Harus Diisi");
            return;
        }
        
        int KodeJenis = (((Integer)ftxtKodeJenis.getValue()).intValue());
        int KodePenyimpanan = (((Integer)ftxtKodePenyimpanan.getValue()).intValue());
        String JenisPembayaran = (((String)txtJenisPembayaran.getText().trim()).toString());
        
        try {
            JP.UpdateKodePenyimpanan(KodeJenis, KodePenyimpanan);
            JP.UpdateNamaJenis(KodeJenis, JenisPembayaran);
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Memperbarui Data : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cboPenyimpananItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPenyimpananItemStateChanged
        // TODO add your handling code here:
        String NoPenyimpanan = (((String)cboPenyimpanan.getSelectedItem()).toString());
        int Simpan = NoPenyimpanan.indexOf(' ');
        String Nomor = NoPenyimpanan.substring(0, Simpan);
        String NamaPenyimpanan = NoPenyimpanan.substring(1, Simpan);
        int KodePenyimpanan = Penyimpanan.getKodePenyimpanan(Nomor);
        ftxtKodePenyimpanan.setValue(new Integer(KodePenyimpanan));
    }//GEN-LAST:event_cboPenyimpananItemStateChanged

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JComboBox<String> cboPenyimpanan;
    public javax.swing.JFormattedTextField ftxtKodeJenis;
    private javax.swing.JFormattedTextField ftxtKodePenyimpanan;
    private javax.swing.JLabel lblJenisPembayaran;
    private javax.swing.JLabel lblPenyimpanan;
    private javax.swing.JPanel pnlEditJenisPembayaran;
    public javax.swing.JTextField txtJenisPembayaran;
    // End of variables declaration//GEN-END:variables
}
