/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi.gui;

import App.Outlet;
import Transaksi.JenisPembayaran;
import Transaksi.LabaBulanan;
import Transaksi.LabaHarian;
import Transaksi.LabaItem;
import Transaksi.LabaMingguan;
import Transaksi.LabaTahunan;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.Table;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Yestin
 */
public class Laba extends javax.swing.JFrame {

    LabaItem LI = new LabaItem();
    LabaHarian LH = new LabaHarian();
    LabaMingguan LM = new LabaMingguan();
    LabaBulanan LB = new LabaBulanan();
    LabaTahunan LT = new LabaTahunan();
    BackgroundImage BI = new BackgroundImage();
    Table Tab = new Table();
    JenisPembayaran JP = new JenisPembayaran();
    Outlet Outlet = new Outlet();
    /**
     * Creates new form Laba
     */
    public Laba() {
        initComponents();
        setTitle("Laba");
        BI.BackgroundJPanel(this, pnlLaba);
        
        dchTanggal.setDateFormatString("dd-MM-yyyy");
        ((JTextFieldDateEditor)dchTanggal.getDateEditor()).setForeground(Color.BLUE);
        dchTglAwal.setDateFormatString("dd-MM-yyyy");
        ((JTextFieldDateEditor)dchTglAwal.getDateEditor()).setForeground(Color.BLUE);
        dchTglAkhir.setDateFormatString("dd-MM-yyyy");
        ((JTextFieldDateEditor)dchTglAkhir.getDateEditor()).setForeground(Color.BLUE);
        JP.getJenisPembayaran(cboJenisPembayaran);
        Outlet.getOutlet(cboOutlet);
        ftxtTotalTunai.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                        new DecimalFormat("#,##0"))));
        ftxtTotalTunai.setValue(new Double(0.00));
        ftxtTotalTunai.setVisible(false);
//        lblTotalTunai.setVisible(false);
//        lblRp4.setVisible(false);
        ftxtTotalVariance.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                        new DecimalFormat("#,##0"))));
        ftxtTotalVariance.setValue(new Double(0.00));
        ftxtTotalPenjualan.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                        new DecimalFormat("#,##0"))));
        ftxtTotalPenjualan.setValue(new Double(0.00));
        ftxtTotalModal.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                        new DecimalFormat("#,##0"))));
        ftxtTotalModal.setValue(new Double(0.00));
        ftxtTotalDiskon.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                        new DecimalFormat("#,##0"))));
        ftxtTotalDiskon.setValue(new Double(0.00));
        ftxtLaba.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                        new DecimalFormat("#,##0"))));
        ftxtLaba.setValue(new Double(0.00));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPeriode = new javax.swing.ButtonGroup();
        bgSebulan = new javax.swing.ButtonGroup();
        pnlLaba = new javax.swing.JPanel();
        rbLabaSehari = new javax.swing.JRadioButton();
        dchTanggal = new com.toedter.calendar.JDateChooser();
        rbLabaPerTanggal = new javax.swing.JRadioButton();
        dchTglAwal = new com.toedter.calendar.JDateChooser();
        lblSD1 = new javax.swing.JLabel();
        dchTglAkhir = new com.toedter.calendar.JDateChooser();
        rbLabaSebulan = new javax.swing.JRadioButton();
        rbPerMinggu = new javax.swing.JRadioButton();
        mchSebulan = new com.toedter.calendar.JMonthChooser();
        ychSebulan = new com.toedter.calendar.JYearChooser();
        rbPerTanggal = new javax.swing.JRadioButton();
        rbLabaSetahun = new javax.swing.JRadioButton();
        ychSetahun = new com.toedter.calendar.JYearChooser();
        rbLabaTahunan = new javax.swing.JRadioButton();
        ychThnAwal = new com.toedter.calendar.JYearChooser();
        lblSD2 = new javax.swing.JLabel();
        ychThnAkhir = new com.toedter.calendar.JYearChooser();
        scrlLaba = new javax.swing.JScrollPane();
        tblLaba = new javax.swing.JTable();
        ftxtTotalPenjualan = new javax.swing.JFormattedTextField();
        lblRp1 = new javax.swing.JLabel();
        lblTotalPenjualan = new javax.swing.JLabel();
        ftxtTotalModal = new javax.swing.JFormattedTextField();
        lblRp2 = new javax.swing.JLabel();
        lblTotalTunai = new javax.swing.JLabel();
        ftxtTotalDiskon = new javax.swing.JFormattedTextField();
        lblRp3 = new javax.swing.JLabel();
        lblTotalDiskon = new javax.swing.JLabel();
        ftxtTotalTunai = new javax.swing.JFormattedTextField();
        lblRp4 = new javax.swing.JLabel();
        lblTotalModal = new javax.swing.JLabel();
        ftxtTotalVariance = new javax.swing.JFormattedTextField();
        lblRp5 = new javax.swing.JLabel();
        lblTotalVariance = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        cboJenisPembayaran = new javax.swing.JComboBox<>();
        cbSemuaPembayaran = new javax.swing.JCheckBox();
        btnTampilkan = new javax.swing.JButton();
        ftxtLaba = new javax.swing.JFormattedTextField();
        lblRp6 = new javax.swing.JLabel();
        lblLaba = new javax.swing.JLabel();
        ftxtKodeJenis = new javax.swing.JFormattedTextField();
        cbJenisPembayaran = new javax.swing.JCheckBox();
        cbOutlet = new javax.swing.JCheckBox();
        cbSemuaOutlet = new javax.swing.JCheckBox();
        cboOutlet = new javax.swing.JComboBox<>();
        ftxtKodeOutlet = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bgPeriode.add(rbLabaSehari);
        rbLabaSehari.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbLabaSehari.setForeground(new java.awt.Color(0, 0, 255));
        rbLabaSehari.setSelected(true);
        rbLabaSehari.setText("Laba Sehari :");
        rbLabaSehari.setOpaque(false);
        rbLabaSehari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbLabaSehariItemStateChanged(evt);
            }
        });

        dchTanggal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        bgPeriode.add(rbLabaPerTanggal);
        rbLabaPerTanggal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbLabaPerTanggal.setForeground(new java.awt.Color(0, 0, 255));
        rbLabaPerTanggal.setText("Laba Per Tanggal :");
        rbLabaPerTanggal.setOpaque(false);
        rbLabaPerTanggal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbLabaPerTanggalItemStateChanged(evt);
            }
        });

        dchTglAwal.setEnabled(false);
        dchTglAwal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblSD1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSD1.setForeground(new java.awt.Color(0, 0, 255));
        lblSD1.setText("s/d");

        dchTglAkhir.setEnabled(false);
        dchTglAkhir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        bgPeriode.add(rbLabaSebulan);
        rbLabaSebulan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbLabaSebulan.setForeground(new java.awt.Color(51, 0, 255));
        rbLabaSebulan.setText("Laba Sebulan :");
        rbLabaSebulan.setOpaque(false);
        rbLabaSebulan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbLabaSebulanItemStateChanged(evt);
            }
        });

        bgSebulan.add(rbPerMinggu);
        rbPerMinggu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbPerMinggu.setForeground(new java.awt.Color(0, 0, 255));
        rbPerMinggu.setText("Per Minggu");
        rbPerMinggu.setEnabled(false);
        rbPerMinggu.setOpaque(false);

        mchSebulan.setEnabled(false);
        mchSebulan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        ychSebulan.setEnabled(false);

        bgSebulan.add(rbPerTanggal);
        rbPerTanggal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbPerTanggal.setForeground(new java.awt.Color(0, 0, 255));
        rbPerTanggal.setText("Per Tanggal");
        rbPerTanggal.setEnabled(false);
        rbPerTanggal.setOpaque(false);

        bgPeriode.add(rbLabaSetahun);
        rbLabaSetahun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbLabaSetahun.setForeground(new java.awt.Color(0, 0, 255));
        rbLabaSetahun.setText("Laba Setahun :");
        rbLabaSetahun.setOpaque(false);
        rbLabaSetahun.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbLabaSetahunItemStateChanged(evt);
            }
        });

        ychSetahun.setEnabled(false);

        bgPeriode.add(rbLabaTahunan);
        rbLabaTahunan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbLabaTahunan.setForeground(new java.awt.Color(0, 0, 255));
        rbLabaTahunan.setText("Laba Tahunan :");
        rbLabaTahunan.setOpaque(false);
        rbLabaTahunan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbLabaTahunanItemStateChanged(evt);
            }
        });

        ychThnAwal.setEnabled(false);

        lblSD2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSD2.setForeground(new java.awt.Color(0, 0, 255));
        lblSD2.setText("s/d");

        ychThnAkhir.setEnabled(false);

        scrlLaba.setForeground(new java.awt.Color(0, 0, 255));
        scrlLaba.setViewportView(tblLaba);

        ftxtTotalPenjualan.setEditable(false);
        ftxtTotalPenjualan.setForeground(new java.awt.Color(0, 0, 255));
        ftxtTotalPenjualan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtTotalPenjualan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblRp1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRp1.setForeground(new java.awt.Color(0, 0, 255));
        lblRp1.setText("Rp");

        lblTotalPenjualan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalPenjualan.setForeground(new java.awt.Color(0, 0, 255));
        lblTotalPenjualan.setText("Total Penjualan :");

        ftxtTotalModal.setEditable(false);
        ftxtTotalModal.setForeground(new java.awt.Color(0, 0, 255));
        ftxtTotalModal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtTotalModal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblRp2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRp2.setForeground(new java.awt.Color(0, 0, 255));
        lblRp2.setText("Rp");

        lblTotalTunai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalTunai.setForeground(new java.awt.Color(0, 0, 255));
        lblTotalTunai.setText("Total Tunai :");

        ftxtTotalDiskon.setEditable(false);
        ftxtTotalDiskon.setForeground(new java.awt.Color(0, 0, 255));
        ftxtTotalDiskon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtTotalDiskon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblRp3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRp3.setForeground(new java.awt.Color(0, 0, 255));
        lblRp3.setText("Rp");

        lblTotalDiskon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalDiskon.setForeground(new java.awt.Color(51, 0, 255));
        lblTotalDiskon.setText("Total Diskon :");

        ftxtTotalTunai.setEditable(false);
        ftxtTotalTunai.setForeground(new java.awt.Color(0, 0, 255));
        ftxtTotalTunai.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtTotalTunai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblRp4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRp4.setForeground(new java.awt.Color(0, 0, 255));
        lblRp4.setText("Rp");

        lblTotalModal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalModal.setForeground(new java.awt.Color(0, 0, 255));
        lblTotalModal.setText("Total Modal :");

        ftxtTotalVariance.setEditable(false);
        ftxtTotalVariance.setForeground(new java.awt.Color(0, 0, 255));
        ftxtTotalVariance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtTotalVariance.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblRp5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRp5.setForeground(new java.awt.Color(0, 0, 255));
        lblRp5.setText("Rp");

        lblTotalVariance.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalVariance.setForeground(new java.awt.Color(0, 0, 255));
        lblTotalVariance.setText("Total Variance :");

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cetak.png"))); // NOI18N

        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ExportKeExcel.png"))); // NOI18N
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        cboJenisPembayaran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboJenisPembayaran.setForeground(new java.awt.Color(0, 0, 255));
        cboJenisPembayaran.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboJenisPembayaranItemStateChanged(evt);
            }
        });

        cbSemuaPembayaran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbSemuaPembayaran.setForeground(new java.awt.Color(0, 0, 255));
        cbSemuaPembayaran.setText("Semua");
        cbSemuaPembayaran.setOpaque(false);
        cbSemuaPembayaran.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSemuaPembayaranItemStateChanged(evt);
            }
        });

        btnTampilkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tampilkan.png"))); // NOI18N
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        ftxtLaba.setEditable(false);
        ftxtLaba.setForeground(new java.awt.Color(0, 0, 255));
        ftxtLaba.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtLaba.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblRp6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRp6.setForeground(new java.awt.Color(0, 0, 255));
        lblRp6.setText("Rp");

        lblLaba.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblLaba.setForeground(new java.awt.Color(0, 0, 255));
        lblLaba.setText("Laba :");

        ftxtKodeJenis.setEditable(false);
        ftxtKodeJenis.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeJenis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cbJenisPembayaran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbJenisPembayaran.setForeground(new java.awt.Color(0, 0, 255));
        cbJenisPembayaran.setText("JenisPembayaran :");
        cbJenisPembayaran.setOpaque(false);

        cbOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbOutlet.setForeground(new java.awt.Color(0, 0, 255));
        cbOutlet.setText("Outlet :");
        cbOutlet.setOpaque(false);
        cbOutlet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOutletItemStateChanged(evt);
            }
        });

        cbSemuaOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbSemuaOutlet.setForeground(new java.awt.Color(0, 0, 255));
        cbSemuaOutlet.setText("Semua");
        cbSemuaOutlet.setOpaque(false);
        cbSemuaOutlet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSemuaOutletItemStateChanged(evt);
            }
        });

        cboOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboOutlet.setForeground(new java.awt.Color(0, 0, 255));
        cboOutlet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboOutletItemStateChanged(evt);
            }
        });

        ftxtKodeOutlet.setEditable(false);
        ftxtKodeOutlet.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlLabaLayout = new javax.swing.GroupLayout(pnlLaba);
        pnlLaba.setLayout(pnlLabaLayout);
        pnlLabaLayout.setHorizontalGroup(
            pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabaLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLabaLayout.createSequentialGroup()
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLabaLayout.createSequentialGroup()
                                .addComponent(rbLabaTahunan)
                                .addGap(78, 78, 78)
                                .addComponent(ychThnAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSD2))
                            .addGroup(pnlLabaLayout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(ychSetahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ychThnAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlLabaLayout.createSequentialGroup()
                                .addComponent(ftxtKodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtKodeOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98)
                        .addComponent(btnTampilkan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabaLayout.createSequentialGroup()
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLabaLayout.createSequentialGroup()
                                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbLabaSehari)
                                    .addComponent(rbLabaSebulan)
                                    .addComponent(rbLabaSetahun))
                                .addGap(82, 82, 82)
                                .addComponent(mchSebulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ychSebulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbPerMinggu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbPerTanggal))
                            .addGroup(pnlLabaLayout.createSequentialGroup()
                                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dchTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlLabaLayout.createSequentialGroup()
                                        .addComponent(rbLabaPerTanggal)
                                        .addGap(56, 56, 56)
                                        .addComponent(dchTglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSD1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dchTglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbJenisPembayaran)
                            .addComponent(cbOutlet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlLabaLayout.createSequentialGroup()
                                .addComponent(cbSemuaPembayaran)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLabaLayout.createSequentialGroup()
                                .addComponent(cbSemuaOutlet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboOutlet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(74, 74, 74))
            .addComponent(scrlLaba)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabaLayout.createSequentialGroup()
                        .addComponent(lblTotalDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRp3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtTotalDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabaLayout.createSequentialGroup()
                        .addComponent(lblTotalVariance, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRp5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtTotalVariance, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabaLayout.createSequentialGroup()
                        .addComponent(lblTotalTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRp4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtTotalTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlLabaLayout.createSequentialGroup()
                        .addComponent(lblLaba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRp6))
                    .addGroup(pnlLabaLayout.createSequentialGroup()
                        .addComponent(lblTotalPenjualan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRp1))
                    .addGroup(pnlLabaLayout.createSequentialGroup()
                        .addComponent(lblTotalModal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRp2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ftxtLaba, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(ftxtTotalModal)
                    .addComponent(ftxtTotalPenjualan))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnExport)
                .addGap(69, 69, 69)
                .addComponent(btnCetak)
                .addGap(60, 60, 60)
                .addComponent(btnTutup)
                .addGap(89, 89, 89))
        );
        pnlLabaLayout.setVerticalGroup(
            pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rbLabaSehari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dchTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbOutlet)
                        .addComponent(cbSemuaOutlet)
                        .addComponent(cboOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchTglAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dchTglAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbLabaPerTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbPerMinggu)
                        .addComponent(rbPerTanggal)
                        .addComponent(cboJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbSemuaPembayaran)
                        .addComponent(cbJenisPembayaran))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rbLabaSebulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mchSebulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ychSebulan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTampilkan)
                    .addGroup(pnlLabaLayout.createSequentialGroup()
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbLabaSetahun)
                            .addComponent(ychSetahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ftxtKodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ftxtKodeOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbLabaTahunan)
                            .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ychThnAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSD2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ychThnAwal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(scrlLaba, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRp4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftxtTotalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRp1)
                        .addComponent(lblTotalPenjualan)
                        .addComponent(ftxtTotalTunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotalTunai)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLabaLayout.createSequentialGroup()
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtTotalModal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRp2)
                            .addComponent(lblTotalModal))
                        .addGap(18, 18, 18)
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtLaba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRp6)
                            .addComponent(lblLaba))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCetak, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTutup, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExport, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(39, 39, 39))
                    .addGroup(pnlLabaLayout.createSequentialGroup()
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtTotalVariance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRp5)
                            .addComponent(lblTotalVariance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtTotalDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRp3)
                            .addComponent(lblTotalDiskon))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLaba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLaba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbLabaSehariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbLabaSehariItemStateChanged
        // TODO add your handling code here:
        dchTanggal.setEnabled(true);
        dchTglAwal.setEnabled(false);
        dchTglAkhir.setEnabled(false);
        mchSebulan.setEnabled(false);
        ychSebulan.setEnabled(false);
        rbPerMinggu.setEnabled(false);
        rbPerTanggal.setEnabled(false);
        ychSetahun.setEnabled(false);
        ychThnAwal.setEnabled(false);
        ychThnAkhir.setEnabled(false);
    }//GEN-LAST:event_rbLabaSehariItemStateChanged

    private void rbLabaPerTanggalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbLabaPerTanggalItemStateChanged
        // TODO add your handling code here:
        dchTanggal.setEnabled(false);
        dchTglAwal.setEnabled(true);
        dchTglAkhir.setEnabled(true);
        mchSebulan.setEnabled(false);
        ychSebulan.setEnabled(false);
        rbPerMinggu.setEnabled(false);
        rbPerTanggal.setEnabled(false);
        ychSetahun.setEnabled(false);
        ychThnAwal.setEnabled(false);
        ychThnAkhir.setEnabled(false);
    }//GEN-LAST:event_rbLabaPerTanggalItemStateChanged

    private void rbLabaSebulanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbLabaSebulanItemStateChanged
        // TODO add your handling code here:
        dchTanggal.setEnabled(false);
        dchTglAwal.setEnabled(false);
        dchTglAkhir.setEnabled(false);
        mchSebulan.setEnabled(true);
        ychSebulan.setEnabled(true);
        rbPerMinggu.setEnabled(true);
        rbPerTanggal.setEnabled(true);
        ychSetahun.setEnabled(false);
        ychThnAwal.setEnabled(false);
        ychThnAkhir.setEnabled(false);
    }//GEN-LAST:event_rbLabaSebulanItemStateChanged

    private void rbLabaSetahunItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbLabaSetahunItemStateChanged
        // TODO add your handling code here:
        dchTanggal.setEnabled(false);
        dchTglAwal.setEnabled(false);
        dchTglAkhir.setEnabled(false);
        mchSebulan.setEnabled(false);
        ychSebulan.setEnabled(false);
        rbPerMinggu.setEnabled(false);
        rbPerTanggal.setEnabled(false);
        ychSetahun.setEnabled(true);
        ychThnAwal.setEnabled(false);
        ychThnAkhir.setEnabled(false);
    }//GEN-LAST:event_rbLabaSetahunItemStateChanged

    private void rbLabaTahunanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbLabaTahunanItemStateChanged
        // TODO add your handling code here:
        dchTanggal.setEnabled(false);
        dchTglAwal.setEnabled(false);
        dchTglAkhir.setEnabled(false);
        mchSebulan.setEnabled(false);
        ychSebulan.setEnabled(false);
        rbPerMinggu.setEnabled(false);
        rbPerTanggal.setEnabled(false);
        ychSetahun.setEnabled(false);
        ychThnAwal.setEnabled(true);
        ychThnAkhir.setEnabled(true);
    }//GEN-LAST:event_rbLabaTahunanItemStateChanged

    private void cboJenisPembayaranItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboJenisPembayaranItemStateChanged
        // TODO add your handling code here:
        String JnsPembayaran = (((String)cboJenisPembayaran.getSelectedItem()).toString());
        int Kode = JnsPembayaran.indexOf(' ');
        String KodeJenis = JnsPembayaran.substring(0, Kode);
        if(cboJenisPembayaran.getSelectedIndex()==0){
            ftxtKodeJenis.setValue(new Integer(0));
        }
        else{
            int KodeJns = Integer.valueOf(KodeJenis);
            ftxtKodeJenis.setValue(new Integer(KodeJns));
        }
    }//GEN-LAST:event_cboJenisPembayaranItemStateChanged

    private void cbSemuaPembayaranItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSemuaPembayaranItemStateChanged
        // TODO add your handling code here:
        if(cbSemuaPembayaran.isSelected()==true){
            cboJenisPembayaran.setEnabled(false);
        }
        else if(cbSemuaPembayaran.isSelected()==false){
            cboJenisPembayaran.setEnabled(true);
        }
    }//GEN-LAST:event_cbSemuaPembayaranItemStateChanged

    private void cboOutletItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboOutletItemStateChanged
        // TODO add your handling code here:
        String Outlet = (((String)cboOutlet.getSelectedItem()).toString());
        int Kode = Outlet.indexOf(' ');
        String KodeCabang = Outlet.substring(0, Kode);
            int KodeOutlet = Integer.valueOf(KodeCabang);
            ftxtKodeOutlet.setValue(new Integer(KodeOutlet));
        
    }//GEN-LAST:event_cboOutletItemStateChanged

    private void cbOutletItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOutletItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbOutletItemStateChanged

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here:
        int KodeJenis = (((Integer)ftxtKodeJenis.getValue()).intValue());
        int KodeOutlet = (((Integer)ftxtKodeOutlet.getValue()).intValue());
        if(rbLabaSehari.isSelected()){
            Calendar Tanggal = dchTanggal.getCalendar();
            int Tgl = dchTanggal.getCalendar().getTime().getDate();
            int Bln = dchTanggal.getCalendar().getTime().getMonth()+1;
            int Thn = dchTanggal.getCalendar().getTime().getYear()+1900;
            LI.getLabaItem(tblLaba, Tanggal);
            HitungLabaSehari();
        }
        else if(rbLabaPerTanggal.isSelected()){
            int TglAwal = dchTglAwal.getCalendar().getTime().getDate();
            int BlnAwal = dchTglAwal.getCalendar().getTime().getMonth()+1;
            int ThnAwal = dchTglAwal.getCalendar().getTime().getYear()+1900;
            int TglAkhir = dchTglAkhir.getCalendar().getTime().getDate();
            int BlnAkhir = dchTglAkhir.getCalendar().getTime().getMonth()+1;
            int ThnAkhir = dchTglAkhir.getCalendar().getTime().getYear()+1900;
            
            if(cbSemuaPembayaran.isSelected()==true && cbSemuaOutlet.isSelected()==true){
                LH.getLabaHarian(tblLaba, TglAwal, TglAkhir, BlnAwal, BlnAkhir, ThnAwal, ThnAkhir);
            }
            else if(cbSemuaPembayaran.isSelected()==true && cbSemuaOutlet.isSelected()==false){
                LH.getLabaHarian1(tblLaba, KodeOutlet, TglAwal, TglAkhir, BlnAwal, BlnAkhir, ThnAwal, ThnAkhir);
            }
            else if(cbSemuaPembayaran.isSelected()==false && cbSemuaOutlet.isSelected()==true){
                LH.getLabaHarian3(tblLaba, KodeJenis, TglAwal, TglAkhir, BlnAwal, BlnAkhir, ThnAwal, ThnAkhir);
            }
            else if(cbSemuaPembayaran.isSelected()==false && cbSemuaOutlet.isSelected()==false){
                LH.getLabaHarian6(tblLaba, KodeOutlet, KodeJenis, TglAwal, BlnAwal, ThnAwal, TglAkhir, BlnAkhir, ThnAkhir);
            }
            HitungLabaPerTanggal();
        }
        else if(rbLabaSebulan.isSelected()){
            int Bulan = mchSebulan.getMonth()+1;
            int Tahun = ychSebulan.getYear();
            if(rbPerMinggu.isSelected()){
                if(cbSemuaPembayaran.isSelected()==true && cbSemuaOutlet.isSelected()==true){
                    LM.getLabaMingguan(tblLaba, Bulan, Tahun);
                }
                else if(cbSemuaPembayaran.isSelected()==true && cbSemuaOutlet.isSelected()==false){
                    LM.getLabaMingguan1(tblLaba, KodeOutlet, Bulan, Tahun);
                }
                else if(cbSemuaPembayaran.isSelected()==false && cbSemuaOutlet.isSelected()==true){
                    LM.getLabaMingguan2(tblLaba, KodeJenis, Bulan, Tahun);
                }
                else if(cbSemuaPembayaran.isSelected()==false && cbSemuaOutlet.isSelected()==false){
                    LM.getLabaMingguan4(tblLaba, KodeOutlet, KodeJenis, Bulan, Tahun);
                }
                HitungLabaSebulanMingguan();
            }
            else if(rbPerTanggal.isSelected()){
                if(cbSemuaPembayaran.isSelected()==true && cbSemuaOutlet.isSelected()==true){
                    LH.getLabaHarian(tblLaba, Bulan, Tahun);
                }
                else if(cbSemuaPembayaran.isSelected()==true && cbSemuaOutlet.isSelected()==false){
                    LH.getLabaHarian1(tblLaba, KodeOutlet, Bulan, Tahun);
                }
                else if(cbSemuaPembayaran.isSelected()==false && cbSemuaOutlet.isSelected()==true){
                    LH.getLabaHarian3(tblLaba, KodeJenis, Bulan, Tahun);
                }
                else if(cbSemuaPembayaran.isSelected()==false && cbSemuaOutlet.isSelected()==false){
                    LH.getLabaHarian6(tblLaba, KodeOutlet, KodeJenis, Bulan, Tahun);
                }
                HitungLabaSebulanHarian();
            }
        }
        else if(rbLabaSetahun.isSelected()){
            int Tahun = ychSetahun.getYear();
            if(cbSemuaPembayaran.isSelected()==true && cbSemuaOutlet.isSelected()==true){
                LB.getLabaBulanan(tblLaba, Tahun);
            }
            else if(cbSemuaPembayaran.isSelected()==true && cbSemuaOutlet.isSelected()==false){
                LB.getLabaBulanan1(tblLaba, KodeOutlet, Tahun);
            }
            else if(cbSemuaPembayaran.isSelected()==false && cbSemuaOutlet.isSelected()==true){
                LB.getLabaBulanan2(tblLaba, KodeJenis, Tahun);
            }
            else if(cbSemuaPembayaran.isSelected()==false && cbSemuaOutlet.isSelected()==false){
                LB.getLabaBulanan4(tblLaba, KodeOutlet, KodeJenis, Tahun);
            }
            HitungLabaSetahun();
        }
        else if(rbLabaTahunan.isSelected()){
            int ThnAwal = ychThnAwal.getYear();
            int ThnAkhir = ychThnAkhir.getYear();
            if(cbSemuaPembayaran.isSelected()==true && cbSemuaOutlet.isSelected()==true){
                LT.getLabaTahunan(tblLaba, ThnAwal, ThnAkhir);
            }
            else if(cbSemuaPembayaran.isSelected()==true && cbSemuaOutlet.isSelected()==false){
                LT.getLabaTahunan1(tblLaba, KodeOutlet, ThnAwal, ThnAkhir);
            }
            else if(cbSemuaPembayaran.isSelected()==false && cbSemuaOutlet.isSelected()==true){
                LT.getLabaTahunan2(tblLaba, KodeJenis, ThnAwal, ThnAkhir);
            }
            else if(cbSemuaPembayaran.isSelected()==false && cbSemuaOutlet.isSelected()==false){
                LT.getLabaTahunan4(tblLaba, KodeOutlet, KodeJenis, ThnAwal, ThnAkhir);
            }
            HitungLabaTahunan();
        }
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void cbSemuaOutletItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSemuaOutletItemStateChanged
        // TODO add your handling code here:
        if(cbSemuaOutlet.isSelected()==true){
            cboOutlet.setEnabled(false);
        }
        else if(cbSemuaOutlet.isSelected()==false){
            cboOutlet.setEnabled(true);
        }
    }//GEN-LAST:event_cbSemuaOutletItemStateChanged

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnExportActionPerformed

    private void HitungLabaSehari(){
        int KodeJenis = (((Integer)ftxtKodeJenis.getValue()).intValue());
        int KodeOutlet= (((Integer)ftxtKodeOutlet.getValue()).intValue());
        DefaultTableModel dtm = (DefaultTableModel)tblLaba.getModel();
        Double GrandTotalModal = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalModal = ((Double)dtm.getValueAt(i, 8)).doubleValue();
            GrandTotalModal += TotalModal;
        }
        ftxtTotalModal.setValue(new Double(GrandTotalModal));
        
        Double GrandTotalPenjualan = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalPenjualan = ((Double)dtm.getValueAt(i, 10)).doubleValue();
            GrandTotalPenjualan += TotalPenjualan;
        }
        ftxtTotalPenjualan.setValue(new Double(GrandTotalPenjualan));
        
        int Tgl = dchTanggal.getCalendar().getTime().getDate();
        int Bln = dchTanggal.getCalendar().getTime().getMonth()+1;
        int Thn = dchTanggal.getCalendar().getTime().getYear()+1900;
        if(cbSemuaOutlet.isSelected()==true && cbSemuaPembayaran.isSelected()==true){
            Double TotalVariance = LH.getGrandTotalVariance(Tgl, Bln, Thn);
            ftxtTotalVariance.setValue(new Double(TotalVariance));
        }
        else if(cbSemuaOutlet.isSelected()==true && cbSemuaPembayaran.isSelected()==false){
            Double TotalVariance = LH.getGrandTotalVariance2(KodeJenis, Tgl, Bln, Thn);
            ftxtTotalVariance.setValue(new Double(TotalVariance));
        }
        else if(cbSemuaOutlet.isSelected()==false && cbSemuaPembayaran.isSelected()==true){
            Double TotalVariance = LH.getGrandTotalVariance1(KodeOutlet, Tgl, Bln, Thn);
            ftxtTotalVariance.setValue(new Double(TotalVariance));
        }
        else if(cbSemuaOutlet.isSelected()==false && cbSemuaPembayaran.isSelected()==false){
            Double TotalVariance = LH.getGrandTotalVariance3(KodeOutlet, KodeJenis, Tgl, Bln, Thn);
            ftxtTotalVariance.setValue(new Double(TotalVariance));
        }
        
        Double GrandTotalDiskon=0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalDiskon = (((Double)dtm.getValueAt(i, 12)).doubleValue());
            GrandTotalDiskon += TotalDiskon;
        }
        ftxtTotalDiskon.setValue(new Double(GrandTotalDiskon));
        
        Double TotModal = (((Double)ftxtTotalModal.getValue()).doubleValue());
        Double TotPenjualan = (((Double)ftxtTotalPenjualan.getValue()).doubleValue());
        Double Laba = TotPenjualan - TotModal;
        ftxtLaba.setValue(new Double(Laba));
    }
    private void HitungLabaPerTanggal(){
        DefaultTableModel dtm = (DefaultTableModel)tblLaba.getModel();
        Double GrandTotalModal = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalModal = ((Double)dtm.getValueAt(i, 5)).doubleValue();
            GrandTotalModal += TotalModal;
        }
        ftxtTotalModal.setValue(new Double(GrandTotalModal));
        
        Double GrandTotalPenjualan = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalPenjualan = ((Double)dtm.getValueAt(i, 6)).doubleValue();
            GrandTotalPenjualan += TotalPenjualan;
        }
        ftxtTotalPenjualan.setValue(new Double(GrandTotalPenjualan));
        
        Double TotalModal = (((Double)ftxtTotalModal.getValue()).doubleValue());
        Double TotalJual = (((Double)ftxtTotalPenjualan.getValue()).doubleValue());
        Double Laba = TotalJual - TotalModal;
        
        Double GrandTotalDiskon = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalDiskon = ((Double)dtm.getValueAt(i, 8)).doubleValue();
            GrandTotalDiskon += TotalDiskon;
        }
        ftxtTotalModal.setValue(new Double(GrandTotalDiskon));
        
        Double GrandTotalTunai = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalTunai = ((Double)dtm.getValueAt(i, 9)).doubleValue();
            GrandTotalTunai += TotalTunai;
        }
        ftxtTotalModal.setValue(new Double(GrandTotalTunai));
    }
    
    private void HitungLabaSebulanHarian(){
        DefaultTableModel dtm = (DefaultTableModel)tblLaba.getModel();
        Double GrandTotalModal = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalModal = ((Double)dtm.getValueAt(i, 5)).doubleValue();
            GrandTotalModal += TotalModal;
        }
        ftxtTotalModal.setValue(new Double(GrandTotalModal));
        
        Double GrandTotalPenjualan = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalPenjualan = ((Double)dtm.getValueAt(i, 6)).doubleValue();
            GrandTotalPenjualan += TotalPenjualan;
        }
        ftxtTotalPenjualan.setValue(new Double(GrandTotalPenjualan));
        
        Double TotalModal = (((Double)ftxtTotalModal.getValue()).doubleValue());
        Double TotalJual = (((Double)ftxtTotalPenjualan.getValue()).doubleValue());
        Double Laba = TotalJual - TotalModal;
        
        Double GrandTotalDiskon = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalDiskon = ((Double)dtm.getValueAt(i, 8)).doubleValue();
            GrandTotalDiskon += TotalDiskon;
        }
        ftxtTotalDiskon.setValue(new Double(GrandTotalDiskon));
        
        
        Double GrandTotalTunai = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalTunai = ((Double)dtm.getValueAt(i, 9)).doubleValue();
            GrandTotalTunai += TotalTunai;
        }
        ftxtTotalVariance.setValue(new Double(GrandTotalTunai));
    }
    private void HitungLabaSebulanMingguan(){
        DefaultTableModel dtm = (DefaultTableModel)tblLaba.getModel();
        Double GrandTotalModal = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalModal = ((Double)dtm.getValueAt(i, 5)).doubleValue();
            GrandTotalModal += TotalModal;
        }
        ftxtTotalModal.setValue(new Double(GrandTotalModal));
        
        Double GrandTotalPenjualan = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalPenjualan = ((Double)dtm.getValueAt(i, 6)).doubleValue();
            GrandTotalPenjualan += TotalPenjualan;
        }
        ftxtTotalPenjualan.setValue(new Double(GrandTotalPenjualan));
        
        Double TotalModal = (((Double)ftxtTotalModal.getValue()).doubleValue());
        Double TotalJual = (((Double)ftxtTotalPenjualan.getValue()).doubleValue());
        Double Laba = TotalJual - TotalModal;
        
        Double GrandTotalDiskon = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalDiskon = ((Double)dtm.getValueAt(i, 8)).doubleValue();
            GrandTotalDiskon += TotalDiskon;
        }
        ftxtTotalModal.setValue(new Double(GrandTotalDiskon));
        
        Double GrandTotalTunai = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalTunai = ((Double)dtm.getValueAt(i, 9)).doubleValue();
            GrandTotalTunai += TotalTunai;
        }
        ftxtTotalVariance.setValue(new Double(GrandTotalTunai));
    }
    
    private void HitungLabaSetahun(){
        DefaultTableModel dtm = (DefaultTableModel)tblLaba.getModel();
        Double GrandTotalModal = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalModal = ((Double)dtm.getValueAt(i, 4)).doubleValue();
            GrandTotalModal += TotalModal;
        }
        ftxtTotalModal.setValue(new Double(GrandTotalModal));
        
        Double GrandTotalPenjualan = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalPenjualan = ((Double)dtm.getValueAt(i, 5)).doubleValue();
            GrandTotalPenjualan += TotalPenjualan;
        }
        ftxtTotalPenjualan.setValue(new Double(GrandTotalPenjualan));
        
        Double TotalModal = (((Double)ftxtTotalModal.getValue()).doubleValue());
        Double TotalJual = (((Double)ftxtTotalPenjualan.getValue()).doubleValue());
        Double Laba = TotalJual - TotalModal;
        
        Double GrandTotalDiskon = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalDiskon = ((Double)dtm.getValueAt(i, 7)).doubleValue();
            GrandTotalDiskon += TotalDiskon;
        }
        ftxtTotalVariance.setValue(new Double(GrandTotalDiskon));
        
        Double GrandTotalTunai = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double TotalTunai = ((Double)dtm.getValueAt(i, 8)).doubleValue();
            GrandTotalTunai += TotalTunai;
        }
        ftxtTotalTunai.setValue(new Double(GrandTotalTunai));
    }
    private void HitungLabaTahunan(){
        
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPeriode;
    private javax.swing.ButtonGroup bgSebulan;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JCheckBox cbJenisPembayaran;
    private javax.swing.JCheckBox cbOutlet;
    private javax.swing.JCheckBox cbSemuaOutlet;
    private javax.swing.JCheckBox cbSemuaPembayaran;
    private javax.swing.JComboBox<String> cboJenisPembayaran;
    private javax.swing.JComboBox<String> cboOutlet;
    private com.toedter.calendar.JDateChooser dchTanggal;
    private com.toedter.calendar.JDateChooser dchTglAkhir;
    private com.toedter.calendar.JDateChooser dchTglAwal;
    private javax.swing.JFormattedTextField ftxtKodeJenis;
    private javax.swing.JFormattedTextField ftxtKodeOutlet;
    private javax.swing.JFormattedTextField ftxtLaba;
    private javax.swing.JFormattedTextField ftxtTotalDiskon;
    private javax.swing.JFormattedTextField ftxtTotalModal;
    private javax.swing.JFormattedTextField ftxtTotalPenjualan;
    private javax.swing.JFormattedTextField ftxtTotalTunai;
    private javax.swing.JFormattedTextField ftxtTotalVariance;
    private javax.swing.JLabel lblLaba;
    private javax.swing.JLabel lblRp1;
    private javax.swing.JLabel lblRp2;
    private javax.swing.JLabel lblRp3;
    private javax.swing.JLabel lblRp4;
    private javax.swing.JLabel lblRp5;
    private javax.swing.JLabel lblRp6;
    private javax.swing.JLabel lblSD1;
    private javax.swing.JLabel lblSD2;
    private javax.swing.JLabel lblTotalDiskon;
    private javax.swing.JLabel lblTotalModal;
    private javax.swing.JLabel lblTotalPenjualan;
    private javax.swing.JLabel lblTotalTunai;
    private javax.swing.JLabel lblTotalVariance;
    private com.toedter.calendar.JMonthChooser mchSebulan;
    private javax.swing.JPanel pnlLaba;
    private javax.swing.JRadioButton rbLabaPerTanggal;
    private javax.swing.JRadioButton rbLabaSebulan;
    private javax.swing.JRadioButton rbLabaSehari;
    private javax.swing.JRadioButton rbLabaSetahun;
    private javax.swing.JRadioButton rbLabaTahunan;
    private javax.swing.JRadioButton rbPerMinggu;
    private javax.swing.JRadioButton rbPerTanggal;
    private javax.swing.JScrollPane scrlLaba;
    private javax.swing.JTable tblLaba;
    private com.toedter.calendar.JYearChooser ychSebulan;
    private com.toedter.calendar.JYearChooser ychSetahun;
    private com.toedter.calendar.JYearChooser ychThnAkhir;
    private com.toedter.calendar.JYearChooser ychThnAwal;
    // End of variables declaration//GEN-END:variables
}
