/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi.gui;

import Transaksi.*;
import Inventori.*;
import Util.BackgroundImage;
import Util.DBConnector;
import Util.Table;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
/**
 *
 * @author Yestin
 */
public class Pelunasan extends javax.swing.JFrame {

    Transaksi trans = new Transaksi();
    RincianTransaksi RT = new RincianTransaksi();
    BusinessContact BC = new BusinessContact();
    JenisPembayaran JP = new JenisPembayaran();
    Items Item = new Items();
    StokItem SI = new StokItem();
    BackgroundImage BI = new BackgroundImage();
    Table Tab = new Table();
    static int LEFT = SwingConstants.LEFT;
    static int CENTER = SwingConstants.CENTER;
    static int RIGHT = SwingConstants.RIGHT;
    
    /**
     * Creates new form Pelunasan
     */
    public Pelunasan() {
        initComponents();
        setTitle("Pelunasan");
        InitTableFaktur();
        JP.getJenisPembayaran(cboJenisPembayaran);
        BI.BackgroundJPanel(this, pnlPelunasan);
        ftxtNoNota.setValue(new Integer(0));
        ftxtNoNota.setValue(null);
        dchTglTransaksi.getCalendarButton().setVisible(false);
        dchTglTransaksi.setDateFormatString("dd-MM-yyyy");
        ((JTextFieldDateEditor)dchTglTransaksi.getDateEditor()).setForeground(Color.BLUE);
        ((JTextFieldDateEditor)dchTglTransaksi.getDateEditor()).setEditable(false);
        ftxtSubTotal.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                     new DecimalFormat("#,##0"))));
        ftxtSubTotal.setValue(new Double(0.00));
        ftxtPPN.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                    new DecimalFormat("#,##0"))));
        ftxtPPN.setValue(new Double(0.00));
        ftxtGrandTotal.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                    new DecimalFormat("#,##0"))));
        ftxtGrandTotal.setValue(new Double(0.00));
        ftxtJmlhLunas.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                    new DecimalFormat("#,##0"))));
        ftxtJmlhLunas.setValue(new Double(0.00));
        ftxtBayar.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                        new DecimalFormat("#,##0"))));
        ftxtBayar.setValue(new Double(0.00));
        ftxtSisaPembayaran.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                    new DecimalFormat("#,##0"))));
        ftxtSisaPembayaran.setValue(new Double(0.00));
        ftxtKembali.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                    new DecimalFormat("#,##0"))));
        ftxtKembali.setValue(new Double(0.00));
        Tab.TableAlignment7(tblFaktur, LEFT, LEFT, CENTER, CENTER, RIGHT, CENTER, RIGHT, CENTER);
    }
    public void InitTableFaktur(){
        tblFaktur.setModel(new DefaultTableModel(){
                String ColName[] = {"Barcode","Nama Item","Satuan","Kuantitas","Harga","Diskon","Total"};
                Class ColType[] = {String.class,String.class,String.class,Double.class,Double.class,Double.class,Double.class};
                
                @Override
                public Class<?> getColumnClass(int ColIndex){
                    return ColType[ColIndex];
                }
                @Override
                public String getColumnName(int ColIndex){
                    return ColName[ColIndex];
                }
                @Override
                public int getColumnCount(){
                    return 7;
                }
        });
        
        tblFaktur.getColumnModel().getColumn(0).setPreferredWidth(75);
        tblFaktur.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblFaktur.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblFaktur.getColumnModel().getColumn(3).setPreferredWidth(75);
        tblFaktur.getColumnModel().getColumn(4).setPreferredWidth(75);
        tblFaktur.getColumnModel().getColumn(5).setPreferredWidth(50);
        tblFaktur.getColumnModel().getColumn(6).setPreferredWidth(75);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPelunasan = new javax.swing.JPanel();
        lblNoNota = new javax.swing.JLabel();
        ftxtNoNota = new javax.swing.JFormattedTextField();
        lblTglTransaksi = new javax.swing.JLabel();
        dchTglTransaksi = new com.toedter.calendar.JDateChooser();
        txtNoFaktur = new javax.swing.JTextField();
        lblNoFaktur = new javax.swing.JLabel();
        lblNamaSupplier = new javax.swing.JLabel();
        txtNamaSupplier = new javax.swing.JTextField();
        lblAlamat = new javax.swing.JLabel();
        scrlAlamat = new javax.swing.JScrollPane();
        txaAlamat = new javax.swing.JTextArea();
        scrlFaktur = new javax.swing.JScrollPane();
        tblFaktur = new javax.swing.JTable();
        ftxtSubTotal = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        ftxtPPN = new javax.swing.JFormattedTextField();
        lblPPN = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ftxtGrandTotal = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ftxtBayar = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        ftxtSisaPembayaran = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        ftxtJmlhLunas = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        ftxtKembali = new javax.swing.JFormattedTextField();
        btnCetak = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        ftxtKodeBC = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPembayaran = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboJenisPembayaran = new javax.swing.JComboBox<>();
        ftxtKodeJenis = new javax.swing.JFormattedTextField();
        ftxtKodeOutlet = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtStatusPelunasan = new javax.swing.JTextField();
        txtJenisTransaksi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNoNota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNoNota.setForeground(new java.awt.Color(0, 0, 255));
        lblNoNota.setText("No Nota :");

        ftxtNoNota.setForeground(new java.awt.Color(0, 0, 255));
        ftxtNoNota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ftxtNoNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftxtNoNotaKeyPressed(evt);
            }
        });

        lblTglTransaksi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTglTransaksi.setForeground(new java.awt.Color(0, 0, 255));
        lblTglTransaksi.setText("Tanggal Transaksi :");

        dchTglTransaksi.setForeground(new java.awt.Color(0, 0, 255));

        txtNoFaktur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoFaktur.setForeground(new java.awt.Color(0, 0, 255));
        txtNoFaktur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoFakturKeyPressed(evt);
            }
        });

        lblNoFaktur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNoFaktur.setForeground(new java.awt.Color(0, 0, 255));
        lblNoFaktur.setText("No Faktur :");

        lblNamaSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaSupplier.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaSupplier.setText("Nama Supplier :");

        txtNamaSupplier.setEditable(false);
        txtNamaSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaSupplier.setForeground(new java.awt.Color(0, 0, 255));

        lblAlamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(0, 0, 255));
        lblAlamat.setText("Alamat :");

        txaAlamat.setEditable(false);
        txaAlamat.setColumns(20);
        txaAlamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txaAlamat.setForeground(new java.awt.Color(0, 0, 255));
        txaAlamat.setRows(5);
        scrlAlamat.setViewportView(txaAlamat);

        tblFaktur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblFaktur.setForeground(new java.awt.Color(51, 0, 255));
        scrlFaktur.setViewportView(tblFaktur);

        ftxtSubTotal.setEditable(false);
        ftxtSubTotal.setForeground(new java.awt.Color(0, 0, 255));
        ftxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtSubTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Rp");

        lblSubTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(0, 0, 255));
        lblSubTotal.setText("Sub Total :");

        ftxtPPN.setEditable(false);
        ftxtPPN.setForeground(new java.awt.Color(0, 0, 255));
        ftxtPPN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtPPN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblPPN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPPN.setForeground(new java.awt.Color(0, 51, 255));
        lblPPN.setText("PPN (11%) :");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Rp");

        ftxtGrandTotal.setEditable(false);
        ftxtGrandTotal.setForeground(new java.awt.Color(0, 0, 255));
        ftxtGrandTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtGrandTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Rp");

        lblGrandTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(0, 0, 255));
        lblGrandTotal.setText("Grand Total :");

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Bayar :");

        ftxtBayar.setForeground(new java.awt.Color(0, 0, 255));
        ftxtBayar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ftxtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftxtBayarKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Sisa Pembayaran :");

        ftxtSisaPembayaran.setEditable(false);
        ftxtSisaPembayaran.setForeground(new java.awt.Color(0, 0, 255));
        ftxtSisaPembayaran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Jumlah Lunas :");

        ftxtJmlhLunas.setEditable(false);
        ftxtJmlhLunas.setForeground(new java.awt.Color(0, 0, 255));
        ftxtJmlhLunas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Kembali :");

        ftxtKembali.setEditable(false);
        ftxtKembali.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKembali.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cetak.png"))); // NOI18N
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnTutup.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        ftxtKodeBC.setEditable(false);
        ftxtKodeBC.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeBC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Pembayaran :");

        txtPembayaran.setEditable(false);
        txtPembayaran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPembayaran.setForeground(new java.awt.Color(0, 0, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Jenis Pembayaran :");

        cboJenisPembayaran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboJenisPembayaran.setForeground(new java.awt.Color(0, 0, 255));
        cboJenisPembayaran.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboJenisPembayaranItemStateChanged(evt);
            }
        });

        ftxtKodeJenis.setEditable(false);
        ftxtKodeJenis.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeJenis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        ftxtKodeOutlet.setEditable(false);
        ftxtKodeOutlet.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Status Pelunasan :");

        txtStatusPelunasan.setEditable(false);
        txtStatusPelunasan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtStatusPelunasan.setForeground(new java.awt.Color(0, 0, 255));

        txtJenisTransaksi.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtJenisTransaksi.setForeground(new java.awt.Color(0, 0, 255));
        txtJenisTransaksi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJenisTransaksi.setBorder(null);
        txtJenisTransaksi.setOpaque(false);

        javax.swing.GroupLayout pnlPelunasanLayout = new javax.swing.GroupLayout(pnlPelunasan);
        pnlPelunasan.setLayout(pnlPelunasanLayout);
        pnlPelunasanLayout.setHorizontalGroup(
            pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPelunasanLayout.createSequentialGroup()
                .addComponent(scrlFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlPelunasanLayout.createSequentialGroup()
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPelunasanLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPelunasanLayout.createSequentialGroup()
                                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNamaSupplier)
                                    .addComponent(lblNoFaktur)
                                    .addComponent(lblAlamat))
                                .addGap(101, 101, 101)
                                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamaSupplier)
                                    .addComponent(txtNoFaktur)
                                    .addComponent(scrlAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ftxtKodeBC, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(ftxtKodeJenis)
                                    .addComponent(ftxtKodeOutlet))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlPelunasanLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblNoNota)
                                .addGap(18, 18, 18)
                                .addComponent(ftxtNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRefresh)
                                .addGap(18, 18, 18)
                                .addComponent(txtJenisTransaksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTglTransaksi)
                                .addGap(18, 18, 18)
                                .addComponent(dchTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlPelunasanLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnSimpan)
                        .addGap(63, 63, 63)
                        .addComponent(btnCetak)
                        .addGap(57, 57, 57)
                        .addComponent(btnTutup))
                    .addGroup(pnlPelunasanLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPelunasanLayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(ftxtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPelunasanLayout.createSequentialGroup()
                                    .addGap(157, 157, 157)
                                    .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ftxtBayar)
                                        .addComponent(ftxtSisaPembayaran)
                                        .addComponent(ftxtJmlhLunas, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlPelunasanLayout.createSequentialGroup()
                                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(33, 33, 33)
                                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPelunasanLayout.createSequentialGroup()
                                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSubTotal)
                                    .addComponent(lblPPN)
                                    .addComponent(lblGrandTotal))
                                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPelunasanLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPelunasanLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ftxtSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(ftxtPPN)
                            .addComponent(ftxtGrandTotal)
                            .addComponent(txtStatusPelunasan))))
                .addContainerGap())
        );
        pnlPelunasanLayout.setVerticalGroup(
            pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPelunasanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPelunasanLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNoNota)
                            .addComponent(ftxtNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPelunasanLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTglTransaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dchTglTransaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRefresh)
                    .addComponent(txtJenisTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoFaktur)
                    .addComponent(txtNoFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtKodeBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaSupplier)
                    .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtKodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlamat)
                    .addComponent(scrlAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtKodeOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrlFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblSubTotal)
                    .addComponent(jLabel8)
                    .addComponent(txtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPPN)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(cboJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblGrandTotal)
                    .addComponent(jLabel6)
                    .addComponent(ftxtJmlhLunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ftxtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtStatusPelunasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftxtSisaPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftxtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pnlPelunasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTutup)
                    .addComponent(btnCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPelunasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPelunasan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftxtNoNotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtNoNotaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String NmrNota = ftxtNoNota.getText().trim();
            int NoNota = Integer.valueOf(NmrNota);
            
            int JenisTransaksi = trans.getJenisTransaksi(NoNota);
            if(JenisTransaksi==1){
                txtJenisTransaksi.setText("Pembelian");
            }
            else if(JenisTransaksi==2){
                txtJenisTransaksi.setText("Penjualan");
            }
            Calendar TglTransaksi = trans.getTglTransaksi(NoNota);
            dchTglTransaksi.setCalendar(TglTransaksi);
            ((JTextFieldDateEditor)dchTglTransaksi.getDateEditor()).setForeground(Color.BLUE);
            String NoFaktur = trans.getNoFaktur(NoNota);
            txtNoFaktur.setText(NoFaktur);
            int KodeBC = trans.getKodeBC(NoNota);
            ftxtKodeBC.setValue(new Integer(KodeBC));
            String NamaSupplier = BC.getNamaBC(KodeBC);
            txtNamaSupplier.setText(new String(NamaSupplier));
            String Alamat = BC.getAlamat(KodeBC);
            txaAlamat.setText(Alamat);
            
            RT.getRincianTransaksi(tblFaktur, NoNota);
            Tab.TableAlignment7(tblFaktur, LEFT, LEFT, CENTER, CENTER, RIGHT, CENTER, RIGHT, CENTER);
            
            int KodeJenis = trans.getKodeJenis(NoNota);
            String NamaJenis = JP.getNamaJenis(KodeJenis);
            txtPembayaran.setText(NamaJenis);
            Double SubTotal = trans.getSubTotal(NoNota);
            ftxtSubTotal.setValue(new Double(SubTotal));
            Double PPN = trans.getPPN(NoNota);
            ftxtPPN.setValue(new Double(PPN));
            Double GrandTotal = trans.getGrandTotal(NoNota);
            ftxtGrandTotal.setValue(new Double(GrandTotal));
            Double JmlhPembayaran = trans.getJmlhPembayaran(NoNota);
            ftxtJmlhLunas.setValue(new Double(JmlhPembayaran));
            Double SisaPembayaran = GrandTotal - JmlhPembayaran;
            ftxtSisaPembayaran.setValue(new Double(SisaPembayaran));
            int StatusPelunasan = trans.getStatusPelunasan(NoNota);
            if(StatusPelunasan==1){
                txtStatusPelunasan.setText(new String("Lunas"));
            }
            else if(StatusPelunasan==2){
                txtStatusPelunasan.setText(new String("Belum Lunas"));
            }
        }
    }//GEN-LAST:event_ftxtNoNotaKeyPressed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
            String NmrNota = ftxtNoNota.getText().trim();
            int NoNota = Integer.valueOf(NmrNota);
            
            int JenisTransaksi = trans.getJenisTransaksi(NoNota);
            if(JenisTransaksi==1){
                txtJenisTransaksi.setText("Pembelian");
            }
            else if(JenisTransaksi==2){
                txtJenisTransaksi.setText("Penjualan");
            }
            Calendar TglTransaksi = trans.getTglTransaksi(NoNota);
            dchTglTransaksi.setCalendar(TglTransaksi);
            ((JTextFieldDateEditor)dchTglTransaksi.getDateEditor()).setForeground(Color.BLUE);
            String NoFaktur = trans.getNoFaktur(NoNota);
            txtNoFaktur.setText(NoFaktur);
            int KodeBC = trans.getKodeBC(NoNota);
            ftxtKodeBC.setValue(new Integer(KodeBC));
            String NamaSupplier = BC.getNamaBC(KodeBC);
            txtNamaSupplier.setText(new String(NamaSupplier));
            String Alamat = BC.getAlamat(KodeBC);
            txaAlamat.setText(Alamat);
            
            RT.getRincianTransaksi(tblFaktur, NoNota);
            Tab.TableAlignment7(tblFaktur, LEFT, LEFT, CENTER, CENTER, RIGHT, CENTER, RIGHT, CENTER);
            
            int KodeJenis = trans.getKodeJenis(NoNota);
            String NamaJenis = JP.getNamaJenis(KodeJenis);
            txtPembayaran.setText(NamaJenis);
            Double SubTotal = trans.getSubTotal(NoNota);
            ftxtSubTotal.setValue(new Double(SubTotal));
            Double PPN = trans.getPPN(NoNota);
            ftxtPPN.setValue(new Double(PPN));
            Double GrandTotal = trans.getGrandTotal(NoNota);
            ftxtGrandTotal.setValue(new Double(GrandTotal));
            Double JmlhPembayaran = trans.getJmlhPembayaran(NoNota);
            ftxtJmlhLunas.setValue(new Double(JmlhPembayaran));
            Double SisaPembayaran = GrandTotal - JmlhPembayaran;
            ftxtSisaPembayaran.setValue(new Double(SisaPembayaran));
            int StatusPelunasan = trans.getStatusPelunasan(NoNota);
            if(StatusPelunasan==1){
                txtStatusPelunasan.setText(new String("Lunas"));
            }
            else if(StatusPelunasan==2){
                txtStatusPelunasan.setText(new String("Belum Lunas"));
            }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void ftxtBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtBayarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Double GrandTotal = (((Double)ftxtGrandTotal.getValue()).doubleValue());
            String Bayar = ftxtBayar.getText().trim();
            Double JmlhPembayaran = Double.valueOf(Bayar);
            Double SisaPembayaran = ((Double)ftxtSisaPembayaran.getValue()).doubleValue();
            ftxtBayar.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                        new DecimalFormat("#,##0"))));
            ftxtBayar.setValue(new Double(JmlhPembayaran));
            if(JmlhPembayaran>=SisaPembayaran){
                
                Double Kembali = JmlhPembayaran - SisaPembayaran;
                ftxtKembali.setValue(new Double(Kembali));
                Double Sisa = JmlhPembayaran - (SisaPembayaran+Kembali);
                ftxtSisaPembayaran.setValue(new Double(Sisa));
                txtStatusPelunasan.setText("Lunas");
            }
            else if(JmlhPembayaran<SisaPembayaran){
                Double Sisa = SisaPembayaran - JmlhPembayaran;
                ftxtKembali.setValue(new Double(0.00));
                ftxtSisaPembayaran.setValue(new Double(Sisa));
                txtStatusPelunasan.setText("Belum Lunas");
            }
        }
    }//GEN-LAST:event_ftxtBayarKeyPressed

    private void txtNoFakturKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoFakturKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String NoFaktur = txtNoFaktur.getText().trim();
//            int NmrNota = trans.getNoNota(NoFaktur);
            int NoNota = trans.getNoNota(NoFaktur);
            ftxtNoNota.setValue(new Integer(NoNota));
            int JenisTransaksi = trans.getJenisTransaksi(NoNota);
            if(JenisTransaksi==1){
                txtJenisTransaksi.setText("Pembelian");
            }
            else if(JenisTransaksi==2){
                txtJenisTransaksi.setText("Penjualan");
            }
            Calendar TglTransaksi = trans.getTglTransaksi(NoNota);
            dchTglTransaksi.setCalendar(TglTransaksi);
            ((JTextFieldDateEditor)dchTglTransaksi.getDateEditor()).setForeground(Color.BLUE);
            //String NoFaktur = trans.getNoFaktur(NoNota);
            //txtNoFaktur.setText(NmrNota);
            int KodeBC = trans.getKodeBC(NoNota);
            ftxtKodeBC.setValue(new Integer(KodeBC));
            String NamaSupplier = BC.getNamaBC(KodeBC);
            txtNamaSupplier.setText(new String(NamaSupplier));
            String Alamat = BC.getAlamat(KodeBC);
            txaAlamat.setText(Alamat);
            
            RT.getRincianTransaksi(tblFaktur, NoNota);
            Tab.TableAlignment7(tblFaktur, LEFT, LEFT, CENTER, CENTER, RIGHT, CENTER, RIGHT, CENTER);
            
            int KodeJenis = trans.getKodeJenis(NoNota);
            String NamaJenis = JP.getNamaJenis(KodeJenis);
            txtPembayaran.setText(NamaJenis);
            Double SubTotal = trans.getSubTotal(NoNota);
            ftxtSubTotal.setValue(new Double(SubTotal));
            Double PPN = trans.getPPN(NoNota);
            ftxtPPN.setValue(new Double(PPN));
            Double GrandTotal = trans.getGrandTotal(NoNota);
            ftxtGrandTotal.setValue(new Double(GrandTotal));
            Double JmlhPembayaran = trans.getJmlhPembayaran(NoNota);
            ftxtJmlhLunas.setValue(new Double(JmlhPembayaran));
            Double SisaPembayaran = GrandTotal - JmlhPembayaran;
            ftxtSisaPembayaran.setValue(new Double(SisaPembayaran));
            int StatusPelunasan = trans.getStatusPelunasan(NoNota);
            if(StatusPelunasan==1){
                txtStatusPelunasan.setText(new String("Lunas"));
            }
            else if(StatusPelunasan==2){
                txtStatusPelunasan.setText(new String("Belum Lunas"));
            }
        }
    }//GEN-LAST:event_txtNoFakturKeyPressed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(ftxtNoNota.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "No Nota Belum Diisi!");
            return;
        }
        if(tblFaktur.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Nota/Faktur Belum Direfresh!");
            return;
        }
        
        int NoNota = (((Integer)ftxtNoNota.getValue()).intValue());
        int KodeOutlet = (((Integer)ftxtKodeOutlet.getValue()).intValue());
        int KodeJenis = (((Integer)ftxtKodeJenis.getValue()).intValue());
        Double JmlhLunas = (((Double)ftxtJmlhLunas.getValue()).doubleValue());
        Double GrandTotal = (((Double)ftxtGrandTotal.getValue()).doubleValue());
        
        try {
            trans.UpdateJmlhPembayaran(NoNota, JmlhLunas);
            trans.UpdateKodeJenis(NoNota, KodeJenis);
            DBConnector.getConnection().commit();
            if(JmlhLunas>=GrandTotal){
                trans.UpdateStatusPelunasan(NoNota, 1);
                DBConnector.getConnection().commit();
            }
            else if(JmlhLunas<GrandTotal){
                trans.UpdateStatusPelunasan(NoNota, 2);
                DBConnector.getConnection().commit();
            }
            
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui/Disimpan");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Menyimpan Pelunasan : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cboJenisPembayaranItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboJenisPembayaranItemStateChanged
        // TODO add your handling code here:
        if(cboJenisPembayaran.getSelectedIndex()==0){
            ftxtKodeJenis.setValue(new Integer(0));
        }
        else{
            String JnsPembayaran = (((String)cboJenisPembayaran.getSelectedItem()).toString());
            int Kode = JnsPembayaran.indexOf(' ');
            String KodeJenis = JnsPembayaran.substring(0, Kode);
            int KodeJns = Integer.valueOf(KodeJenis);
            ftxtKodeJenis.setValue(KodeJns);
        }
    }//GEN-LAST:event_cboJenisPembayaranItemStateChanged

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JComboBox<String> cboJenisPembayaran;
    private com.toedter.calendar.JDateChooser dchTglTransaksi;
    private javax.swing.JFormattedTextField ftxtBayar;
    private javax.swing.JFormattedTextField ftxtGrandTotal;
    private javax.swing.JFormattedTextField ftxtJmlhLunas;
    private javax.swing.JFormattedTextField ftxtKembali;
    private javax.swing.JFormattedTextField ftxtKodeBC;
    private javax.swing.JFormattedTextField ftxtKodeJenis;
    public javax.swing.JFormattedTextField ftxtKodeOutlet;
    private javax.swing.JFormattedTextField ftxtNoNota;
    private javax.swing.JFormattedTextField ftxtPPN;
    private javax.swing.JFormattedTextField ftxtSisaPembayaran;
    private javax.swing.JFormattedTextField ftxtSubTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblNamaSupplier;
    private javax.swing.JLabel lblNoFaktur;
    private javax.swing.JLabel lblNoNota;
    private javax.swing.JLabel lblPPN;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTglTransaksi;
    private javax.swing.JPanel pnlPelunasan;
    private javax.swing.JScrollPane scrlAlamat;
    private javax.swing.JScrollPane scrlFaktur;
    private javax.swing.JTable tblFaktur;
    private javax.swing.JTextArea txaAlamat;
    public javax.swing.JTextField txtJenisTransaksi;
    private javax.swing.JTextField txtNamaSupplier;
    private javax.swing.JTextField txtNoFaktur;
    private javax.swing.JTextField txtPembayaran;
    private javax.swing.JTextField txtStatusPelunasan;
    // End of variables declaration//GEN-END:variables
}
