/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi.gui;

import Util.BackgroundImage;

/**
 *
 * @author Yestin
 */
public class PoinBelanja extends javax.swing.JDialog {

    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form PoinBelanja
     */
    public PoinBelanja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Poin Belanja");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNoMember = new javax.swing.JLabel();
        txtNoMember = new javax.swing.JTextField();
        lblNamaMember = new javax.swing.JLabel();
        txtNamaMember = new javax.swing.JTextField();
        lblNoHPWA = new javax.swing.JLabel();
        txtNoHPWA = new javax.swing.JTextField();
        scrlPoin = new javax.swing.JScrollPane();
        tblPoin = new javax.swing.JTable();
        ftxtTotalPoin = new javax.swing.JFormattedTextField();
        lblTotalPoin = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();
        lblTglExpire = new javax.swing.JLabel();
        dchTglExpire = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(0, 51, 255));

        lblNoMember.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNoMember.setForeground(new java.awt.Color(0, 0, 255));
        lblNoMember.setText("No Member :");

        txtNoMember.setEditable(false);
        txtNoMember.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoMember.setForeground(new java.awt.Color(0, 0, 255));

        lblNamaMember.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaMember.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaMember.setText("Nama Member :");

        txtNamaMember.setEditable(false);
        txtNamaMember.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaMember.setForeground(new java.awt.Color(0, 0, 255));

        lblNoHPWA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNoHPWA.setForeground(new java.awt.Color(0, 0, 255));
        lblNoHPWA.setText("No HP/WA :");

        txtNoHPWA.setEditable(false);
        txtNoHPWA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoHPWA.setForeground(new java.awt.Color(0, 0, 255));

        scrlPoin.setViewportView(tblPoin);

        ftxtTotalPoin.setEditable(false);
        ftxtTotalPoin.setForeground(new java.awt.Color(0, 0, 255));
        ftxtTotalPoin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblTotalPoin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalPoin.setForeground(new java.awt.Color(0, 0, 255));
        lblTotalPoin.setText("Total Poin :");

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        lblTglExpire.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTglExpire.setForeground(new java.awt.Color(0, 0, 255));
        lblTglExpire.setText("Tgl Expire :");

        dchTglExpire.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlPoin, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotalPoin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftxtTotalPoin, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTutup)
                        .addGap(291, 291, 291))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNoMember)
                    .addComponent(lblNamaMember)
                    .addComponent(lblNoHPWA)
                    .addComponent(lblTglExpire))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNoMember)
                    .addComponent(txtNamaMember)
                    .addComponent(txtNoHPWA, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(dchTglExpire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoMember)
                    .addComponent(txtNoMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaMember)
                    .addComponent(txtNamaMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoHPWA)
                    .addComponent(txtNoHPWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchTglExpire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTglExpire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(scrlPoin, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtTotalPoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPoin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnTutup)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTutup;
    public com.toedter.calendar.JDateChooser dchTglExpire;
    public javax.swing.JFormattedTextField ftxtTotalPoin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNamaMember;
    private javax.swing.JLabel lblNoHPWA;
    private javax.swing.JLabel lblNoMember;
    private javax.swing.JLabel lblTglExpire;
    private javax.swing.JLabel lblTotalPoin;
    private javax.swing.JScrollPane scrlPoin;
    public javax.swing.JTable tblPoin;
    public javax.swing.JTextField txtNamaMember;
    public javax.swing.JTextField txtNoHPWA;
    public javax.swing.JTextField txtNoMember;
    // End of variables declaration//GEN-END:variables
}
