/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi.gui;

import Transaksi.BusinessContact;
import Transaksi.Member;
import Transaksi.Poin;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Yestin
 */
public class RegistrasiMember extends javax.swing.JFrame {

    BusinessContact BC = new BusinessContact();
    Member Mbr = new Member();
    Poin Poin = new Poin();
    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form RegistrasiMember
     */
    public RegistrasiMember() {
        initComponents();
        setTitle("Registrasi Member");
        try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlRegistrasiMember.setOpaque(false);
            Background.add(pnlRegistrasiMember,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        }
        catch (IOException e) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
        }
        txtNama.setText(new String());
        txtNama.setText(null);
        txtAlamat.setText(new String());
        txtAlamat.setText(null);
        txtKelurahan.setText(new String());
        txtKelurahan.setText(null);
        txtKecamatan.setText(new String());
        txtKecamatan.setText(null);
        txtKota.setText(new String());
        txtKota.setText(null);
        txtNoHP.setText(new String());
        txtNoHP.setText(null);
        ftxtDiskon.setValue(new Double(0.00));
        dchtTglExpire.setDateFormatString("dd-mm-yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistrasiMember = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        lblAlamat = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        lblKelurahan = new javax.swing.JLabel();
        txtKelurahan = new javax.swing.JTextField();
        lblKecamatan = new javax.swing.JLabel();
        txtKecamatan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboLevel = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        lblNoHP = new javax.swing.JLabel();
        txtNoHP = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        lblDiskon = new javax.swing.JLabel();
        ftxtDiskon = new javax.swing.JFormattedTextField();
        lblTglExpire = new javax.swing.JLabel();
        dchtTglExpire = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(0, 0, 255));
        lblNama.setText("Nama :");

        txtNama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(0, 0, 255));

        lblAlamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(0, 0, 255));
        lblAlamat.setText("Alamat :");

        txtAlamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(0, 0, 255));

        lblKelurahan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKelurahan.setForeground(new java.awt.Color(0, 0, 255));
        lblKelurahan.setText("Kelurahan/Desa :");

        txtKelurahan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKelurahan.setForeground(new java.awt.Color(0, 0, 255));

        lblKecamatan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKecamatan.setForeground(new java.awt.Color(0, 0, 255));
        lblKecamatan.setText("Kecamatan :");

        txtKecamatan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKecamatan.setForeground(new java.awt.Color(51, 0, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Level :");

        cboLevel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboLevel.setForeground(new java.awt.Color(0, 0, 255));
        cboLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -", "Biasa", "Semi Grosir", "Grosir" }));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Kabupaten/Kota :");

        txtKota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKota.setForeground(new java.awt.Color(0, 0, 255));

        lblNoHP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNoHP.setForeground(new java.awt.Color(0, 0, 255));
        lblNoHP.setText("No HP/WA :");

        txtNoHP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoHP.setForeground(new java.awt.Color(0, 0, 255));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        lblDiskon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiskon.setForeground(new java.awt.Color(0, 0, 255));
        lblDiskon.setText("Diskon (%) :");

        ftxtDiskon.setForeground(new java.awt.Color(0, 0, 255));
        ftxtDiskon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblTglExpire.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTglExpire.setForeground(new java.awt.Color(0, 0, 255));
        lblTglExpire.setText("Tanggal Expire :");

        javax.swing.GroupLayout pnlRegistrasiMemberLayout = new javax.swing.GroupLayout(pnlRegistrasiMember);
        pnlRegistrasiMember.setLayout(pnlRegistrasiMemberLayout);
        pnlRegistrasiMemberLayout.setHorizontalGroup(
            pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiMemberLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btnSimpan)
                .addGap(100, 100, 100)
                .addComponent(btnTutup)
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(pnlRegistrasiMemberLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNama)
                    .addComponent(lblAlamat)
                    .addComponent(lblKelurahan)
                    .addComponent(lblKecamatan)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblNoHP)
                    .addComponent(lblDiskon)
                    .addComponent(lblTglExpire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNama)
                    .addComponent(txtAlamat)
                    .addComponent(txtKelurahan)
                    .addComponent(txtKecamatan)
                    .addComponent(cboLevel, 0, 441, Short.MAX_VALUE)
                    .addComponent(txtKota)
                    .addComponent(txtNoHP)
                    .addComponent(ftxtDiskon)
                    .addComponent(dchtTglExpire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
        pnlRegistrasiMemberLayout.setVerticalGroup(
            pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiMemberLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlamat)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelurahan)
                    .addComponent(txtKelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKecamatan)
                    .addComponent(txtKecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoHP)
                    .addComponent(txtNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiskon)
                    .addComponent(ftxtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchtTglExpire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTglExpire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(pnlRegistrasiMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnTutup))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegistrasiMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNama.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Nama Belum Diisi!");
            return;
        }
        if(txtAlamat.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Alamat Belum Diisi!");
            return;
        }
        if(txtKelurahan.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Kelurahan/Desa Belum Diisi!");
            return;
        }
        if(txtKecamatan.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Kecamatan Belum Diisi");
            return;
        }
        if(txtKota.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Kabupaten/Kota Belum Diisi");
            return;
        }
        
        String Nama = (((String)txtNama.getText().trim()).toString());
        String Alamat = (((String)txtAlamat.getText().trim()).toString());
        String Kelurahan = (((String)txtKelurahan.getText().trim()).toString());
        String Kecamatan = (((String)txtKecamatan.getText().trim()).toString());
        String Kota = (((String)txtKota.getText().trim()).toString());
        String NoHP = (((String)txtNoHP.getText().trim()).toString());
        Double Diskon = (((Double)ftxtDiskon.getValue()).doubleValue());
        Calendar TglExpire = dchtTglExpire.getCalendar();
        
        try {
            BC.Simpan("", Nama, 2, Alamat, Kelurahan, Kecamatan, Kota, null, null, NoHP, null);
            
            int KodeBC = BC.getKodeBC();
            if(cboLevel.getSelectedIndex()==1){
                Mbr.Simpan("C"+KodeBC, KodeBC, "Biasa", Diskon, TglExpire);
                BC.UpdateNoMember(KodeBC, "C"+KodeBC+"");
            }
            else if(cboLevel.getSelectedIndex()==2){
                Mbr.Simpan("B"+KodeBC, KodeBC, "Semi Grosir", Diskon, TglExpire);
                BC.UpdateNoMember(KodeBC, "B"+KodeBC+"");
            }
            else if(cboLevel.getSelectedIndex()==3){
                Mbr.Simpan("A"+KodeBC, KodeBC, "Grosir", Diskon, TglExpire);
                BC.UpdateNoMember(KodeBC, "A"+KodeBC+"");
            }
            
            int LastKodeMember = Mbr.getLastKodeMember();
            String NoMbr = Mbr.getNoMember(LastKodeMember);
            
            Poin.setNoMember(NoMbr);
            Poin.setKodeBC(KodeBC);
            Poin.setJmlhPoint(0);
            Poin.setTglExpire(null);
            Poin.Simpan();
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            txtNama.setText(null);
            txtAlamat.setText(null);
            txtKelurahan.setText(null);
            txtKecamatan.setText(null);
            txtKota.setText(null);
            txtNoHP.setText(null);
            ftxtDiskon.setValue(new Double(0.00));
            dchtTglExpire.setCalendar(null);
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpsn");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Menyimpan Data Member : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JComboBox<String> cboLevel;
    private com.toedter.calendar.JDateChooser dchtTglExpire;
    private javax.swing.JFormattedTextField ftxtDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblKecamatan;
    private javax.swing.JLabel lblKelurahan;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoHP;
    private javax.swing.JLabel lblTglExpire;
    private javax.swing.JPanel pnlRegistrasiMember;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtKecamatan;
    private javax.swing.JTextField txtKelurahan;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHP;
    // End of variables declaration//GEN-END:variables
}
