/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi.gui;

import Transaksi.BusinessContact;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Yestin
 */
public class RegistrasiSupplier extends javax.swing.JFrame {

    BusinessContact BC = new BusinessContact();
    /**
     * Creates new form RegistrasiSupplier
     */
    public RegistrasiSupplier() {
        initComponents();
        setTitle("Registrasi Supplier");
         try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlRegistrasiSupplier.setOpaque(false);
            Background.add(pnlRegistrasiSupplier,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        }
        catch (IOException e) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistrasiSupplier = new javax.swing.JPanel();
        lblNamaSupplier = new javax.swing.JLabel();
        txtNamaSupplier = new javax.swing.JTextField();
        lblAlamat = new javax.swing.JLabel();
        scrlAlamat = new javax.swing.JScrollPane();
        txaAlamat = new javax.swing.JTextArea();
        lblKelurahan = new javax.swing.JLabel();
        txtKelurahan = new javax.swing.JTextField();
        lblKecamatan = new javax.swing.JLabel();
        txtKecamatan = new javax.swing.JTextField();
        lblKota = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        lblNoTelpon = new javax.swing.JLabel();
        txtNoTelpon1 = new javax.swing.JTextField();
        txtNoTelpon2 = new javax.swing.JTextField();
        lblNoHP = new javax.swing.JLabel();
        txtNoHP1 = new javax.swing.JTextField();
        txtNoHP2 = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNamaSupplier.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaSupplier.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaSupplier.setText("Nama Supplier :");

        txtNamaSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaSupplier.setForeground(new java.awt.Color(0, 0, 255));

        lblAlamat.setBackground(new java.awt.Color(255, 255, 255));
        lblAlamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(0, 0, 255));
        lblAlamat.setText("Alamat :");

        txaAlamat.setColumns(20);
        txaAlamat.setRows(5);
        scrlAlamat.setViewportView(txaAlamat);

        lblKelurahan.setBackground(new java.awt.Color(255, 255, 255));
        lblKelurahan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKelurahan.setForeground(new java.awt.Color(0, 0, 255));
        lblKelurahan.setText("Kelurahan/Desa :");

        txtKelurahan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKelurahan.setForeground(new java.awt.Color(0, 0, 255));

        lblKecamatan.setBackground(new java.awt.Color(255, 255, 255));
        lblKecamatan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKecamatan.setForeground(new java.awt.Color(0, 0, 255));
        lblKecamatan.setText("Kecamatan :");

        txtKecamatan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKecamatan.setForeground(new java.awt.Color(0, 0, 255));

        lblKota.setBackground(new java.awt.Color(255, 255, 255));
        lblKota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKota.setForeground(new java.awt.Color(0, 0, 255));
        lblKota.setText("Kabupaten/Kota :");

        txtKota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKota.setForeground(new java.awt.Color(0, 0, 255));

        lblNoTelpon.setBackground(new java.awt.Color(255, 255, 255));
        lblNoTelpon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNoTelpon.setForeground(new java.awt.Color(0, 0, 255));
        lblNoTelpon.setText("NoTelpon :");

        txtNoTelpon1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoTelpon1.setForeground(new java.awt.Color(0, 0, 255));

        txtNoTelpon2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblNoHP.setBackground(new java.awt.Color(255, 255, 255));
        lblNoHP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNoHP.setForeground(new java.awt.Color(0, 0, 255));
        lblNoHP.setText("No HP/WA :");

        txtNoHP1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoHP1.setForeground(new java.awt.Color(0, 0, 255));

        txtNoHP2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoHP2.setForeground(new java.awt.Color(0, 0, 255));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrasiSupplierLayout = new javax.swing.GroupLayout(pnlRegistrasiSupplier);
        pnlRegistrasiSupplier.setLayout(pnlRegistrasiSupplierLayout);
        pnlRegistrasiSupplierLayout.setHorizontalGroup(
            pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiSupplierLayout.createSequentialGroup()
                .addGroup(pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrasiSupplierLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaSupplier)
                            .addComponent(lblAlamat)
                            .addComponent(lblKelurahan)
                            .addComponent(lblKecamatan)
                            .addComponent(lblKota)
                            .addComponent(lblNoTelpon)
                            .addComponent(lblNoHP))
                        .addGap(68, 68, 68)
                        .addGroup(pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaSupplier)
                            .addComponent(scrlAlamat)
                            .addComponent(txtKelurahan)
                            .addComponent(txtKecamatan)
                            .addComponent(txtKota)
                            .addGroup(pnlRegistrasiSupplierLayout.createSequentialGroup()
                                .addComponent(txtNoTelpon1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNoTelpon2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegistrasiSupplierLayout.createSequentialGroup()
                                .addComponent(txtNoHP1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNoHP2))))
                    .addGroup(pnlRegistrasiSupplierLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnSimpan)
                        .addGap(76, 76, 76)
                        .addComponent(btnTutup)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        pnlRegistrasiSupplierLayout.setVerticalGroup(
            pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiSupplierLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaSupplier)
                    .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlamat)
                    .addComponent(scrlAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelurahan)
                    .addComponent(txtKelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKecamatan)
                    .addComponent(txtKecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKota)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoTelpon)
                    .addComponent(txtNoTelpon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoTelpon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoHP)
                    .addComponent(txtNoHP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoHP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(pnlRegistrasiSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnTutup))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegistrasiSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNamaSupplier.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Nama Supplier Belum Diisi");
            return;
        }
        if(txaAlamat.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Alamat Belum Diisi");
            return;
        }
        if(txtKelurahan.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Kelurahan/Desa Belum Diisi");
            return;
        }
        if(txtKecamatan.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Kecamatan Belum Diisi");
            return;
        }
        if(txtKota.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Kabupaten/Kota Belum Diisi");
            return;
        }
        
        String NamaSupplier = (((String)txtNamaSupplier.getText().trim()).toString());
        BC.setNamaBC(NamaSupplier);
        BC.setJenisKontak(1);
        String Alamat = (((String)txaAlamat.getText().trim()).toString());
        BC.setAlamat(Alamat);
        String Kelurahan = (((String)txtKelurahan.getText().trim()).toString());
        BC.setKelurahan(Kelurahan);
        String Kecamatan = (((String)txtKecamatan.getText().trim()).toString());
        BC.setKecamatan(Kecamatan);
        String Kota = (((String)txtKota.getText().trim()).toString());
        BC.setKota(Kota);
        String Telpon1 = (((String)txtNoTelpon1.getText().trim()).toString());
        if(txtNoTelpon1.getText().trim().length()==0 || txtNoTelpon1.getText().trim()==null || txtNoTelpon1.getText().trim()==""){
            BC.setTelpon1("");
        }
        else if(txtNoTelpon1.getText().trim().length()>0 || txtNoTelpon1.getText().trim()!=null || txtNoTelpon1.getText().trim()!=""){
            BC.setTelpon1(Telpon1);
        }
        String Telpon2 = (((String)txtNoTelpon2.getText().trim()).toString());
        if(txtNoTelpon2.getText().trim().length()==0 || txtNoTelpon2.getText().trim()==null || txtNoTelpon2.getText().trim()==""){
            BC.setTelpon2("");
        }
        else if(txtNoTelpon2.getText().trim().length()>0 || txtNoTelpon2.getText().trim()!=null || txtNoTelpon2.getText().trim()!=""){
            BC.setTelpon2(Telpon2);
        }
        String NoHP1 = (((String)txtNoHP1.getText().trim()).toString());
        if(txtNoHP1.getText().trim().length()==0 || txtNoHP1.getText().trim()==null || txtNoHP1.getText().trim()==""){
            BC.setNoHP1("");
        }
        else if(txtNoHP1.getText().trim().length()>0 || txtNoHP1.getText().trim()!=null || txtNoHP1.getText().trim()!=""){
            BC.setNoHP1(NoHP1);
        }
        String NoHP2 = (((String)txtNoHP2.getText().trim()).toString());
        if(txtNoHP2.getText().trim().length()==0 || txtNoHP2.getText().trim()==null || txtNoHP2.getText().trim()==""){
            BC.setNoHP2("");
        }
        else if(txtNoHP2.getText().trim().length()>0 || txtNoHP2.getText().trim()!=null || txtNoHP2.getText().trim()!=""){
            BC.setNoHP2(NoHP2);
        }
        
        try {
            BC.Simpan();
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Menyimpan Data Supplier");
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblKecamatan;
    private javax.swing.JLabel lblKelurahan;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblNamaSupplier;
    private javax.swing.JLabel lblNoHP;
    private javax.swing.JLabel lblNoTelpon;
    private javax.swing.JPanel pnlRegistrasiSupplier;
    private javax.swing.JScrollPane scrlAlamat;
    private javax.swing.JTextArea txaAlamat;
    private javax.swing.JTextField txtKecamatan;
    private javax.swing.JTextField txtKelurahan;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtNamaSupplier;
    private javax.swing.JTextField txtNoHP1;
    private javax.swing.JTextField txtNoHP2;
    private javax.swing.JTextField txtNoTelpon1;
    private javax.swing.JTextField txtNoTelpon2;
    // End of variables declaration//GEN-END:variables
}
