/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventori.gui;

import Inventori.Kategori;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.Table;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yestin
 */
public class DaftarKategori extends javax.swing.JFrame {

    Kategori Kat = new Kategori();
    Table Tab = new Table();
    int Left = SwingConstants.LEFT;
    int Center = SwingConstants.CENTER;
    int Right = SwingConstants.RIGHT;
    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form DaftarKategori
     */
    public DaftarKategori() {
        initComponents();
        setTitle("Daftar Kategori");
        BI.BackgroundJPanel(this, pnlDaftarKategori);
        Kat.getKategori(tblKategori);
        Tab.TableAlignment2(tblKategori, Center, Left, Center);
        Tab.setHeaderForegroundColor(tblKategori, Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDaftarKategori = new javax.swing.JPanel();
        lblNamaKategori = new javax.swing.JLabel();
        txtNamaKategori = new javax.swing.JTextField();
        scrlKategori = new javax.swing.JScrollPane();
        tblKategori = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNamaKategori.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaKategori.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaKategori.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaKategori.setText("Nama Kategori :");

        txtNamaKategori.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaKategori.setForeground(new java.awt.Color(0, 0, 255));
        txtNamaKategori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKategoriKeyPressed(evt);
            }
        });

        scrlKategori.setOpaque(false);

        tblKategori.setForeground(new java.awt.Color(0, 0, 255));
        scrlKategori.setViewportView(tblKategori);

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/Tutup.png"))); // NOI18N

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/Edit.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDaftarKategoriLayout = new javax.swing.GroupLayout(pnlDaftarKategori);
        pnlDaftarKategori.setLayout(pnlDaftarKategoriLayout);
        pnlDaftarKategoriLayout.setHorizontalGroup(
            pnlDaftarKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarKategoriLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblNamaKategori)
                .addGap(55, 55, 55)
                .addComponent(txtNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(scrlKategori, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDaftarKategoriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(46, 46, 46)
                .addComponent(btnEdit)
                .addGap(43, 43, 43)
                .addComponent(btnTutup)
                .addGap(45, 45, 45))
        );
        pnlDaftarKategoriLayout.setVerticalGroup(
            pnlDaftarKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarKategoriLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlDaftarKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaKategori)
                    .addComponent(txtNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(scrlKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(pnlDaftarKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDaftarKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btnRefresh))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDaftarKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDaftarKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaKategoriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKategoriKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_A || evt.getKeyCode()==KeyEvent.VK_B || evt.getKeyCode()==KeyEvent.VK_C ||
                evt.getKeyCode()==KeyEvent.VK_D || evt.getKeyCode()==KeyEvent.VK_E || evt.getKeyCode()==KeyEvent.VK_F ||
                evt.getKeyCode()==KeyEvent.VK_G || evt.getKeyCode()==KeyEvent.VK_H || evt.getKeyCode()==KeyEvent.VK_I ||
                evt.getKeyCode()==KeyEvent.VK_J || evt.getKeyCode()==KeyEvent.VK_K || evt.getKeyCode()==KeyEvent.VK_L ||
                evt.getKeyCode()==KeyEvent.VK_M || evt.getKeyCode()==KeyEvent.VK_N || evt.getKeyCode()==KeyEvent.VK_O ||
                evt.getKeyCode()==KeyEvent.VK_P || evt.getKeyCode()==KeyEvent.VK_Q || evt.getKeyCode()==KeyEvent.VK_R ||
                evt.getKeyCode()==KeyEvent.VK_S || evt.getKeyCode()==KeyEvent.VK_T || evt.getKeyCode()==KeyEvent.VK_U ||
                evt.getKeyCode()==KeyEvent.VK_V || evt.getKeyCode()==KeyEvent.VK_W || evt.getKeyCode()==KeyEvent.VK_X ||
                evt.getKeyCode()==KeyEvent.VK_Y || evt.getKeyCode()==KeyEvent.VK_Z || evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode()==KeyEvent.VK_SPACE || evt.getKeyCode()==KeyEvent.VK_0 || evt.getKeyCode()==KeyEvent.VK_1 ||
                evt.getKeyCode()==KeyEvent.VK_2 || evt.getKeyCode()==KeyEvent.VK_3 || evt.getKeyCode()==KeyEvent.VK_4 ||
                evt.getKeyCode()==KeyEvent.VK_5 || evt.getKeyCode()==KeyEvent.VK_6 || evt.getKeyCode()==KeyEvent.VK_7 ||
                evt.getKeyCode()==KeyEvent.VK_8 || evt.getKeyCode()==KeyEvent.VK_9){
            
            String NamaKategori = (((String)txtNamaKategori.getText().trim()).toString());
            Kat.getKategori(tblKategori, NamaKategori);
            
            Tab.TableAlignment2(tblKategori, Center, Left, Center);
            Tab.setHeaderForegroundColor(tblKategori, Color.BLUE);
        }
    }//GEN-LAST:event_txtNamaKategoriKeyPressed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        EditKategori EK = new EditKategori();
        
        DefaultTableModel dtm = (DefaultTableModel)tblKategori.getModel();
        int row = tblKategori.getSelectedRow();
        
        int KodeKategori = (((Integer)dtm.getValueAt(row, 0)));
        EK.ftxtKodeKategori.setValue(new Integer(KodeKategori));
        String NamaKetgori = Kat.getNamaKategori(KodeKategori);
        EK.txtNamaKategori.setText(new String(NamaKetgori));
        
        EK.setLocationRelativeTo(this);
        EK.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        if(txtNamaKategori.getText().trim().length()>0){
            String Nama = (((String)txtNamaKategori.getText().trim()).toString());
            Kat.getKategori(tblKategori, Nama);
        }
        else if(txtNamaKategori.getText().trim().length()==0){
            Kat.getKategori(tblKategori);
        }
        Tab.TableAlignment2(tblKategori, Center, Left, Center);
        Tab.setHeaderForegroundColor(tblKategori, Color.BLUE);
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel lblNamaKategori;
    private javax.swing.JPanel pnlDaftarKategori;
    private javax.swing.JScrollPane scrlKategori;
    private javax.swing.JTable tblKategori;
    private javax.swing.JTextField txtNamaKategori;
    // End of variables declaration//GEN-END:variables
}
