/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventori.gui;
import Inventori.Satuan;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
/**
 *
 * @author Yestin
 */
public class EditSatuan extends javax.swing.JFrame {

    Satuan Sat = new Satuan();
    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form EditSatuan
     */
    public EditSatuan() {
        initComponents();
        setTitle("Edit Satuan");
        try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlEditSatuan.setOpaque(false);
            Background.add(pnlEditSatuan,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        } 
        catch (IOException ex) {
            Logger.getLogger(RegistrasiKategori.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNamaSatuan.setText(new String());
        txtNamaSatuan.setText(null);
        ftxtKodeSatuan.setVisible(false);
        BI.BackgroundJPanel(this, pnlEditSatuan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEditSatuan = new javax.swing.JPanel();
        lblNamaSatuan = new javax.swing.JLabel();
        txtNamaSatuan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        ftxtKodeSatuan = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlEditSatuan.setForeground(new java.awt.Color(0, 0, 255));

        lblNamaSatuan.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaSatuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaSatuan.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaSatuan.setText("Nama Satuan :");

        txtNamaSatuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaSatuan.setForeground(new java.awt.Color(0, 0, 255));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        ftxtKodeSatuan.setEditable(false);
        ftxtKodeSatuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlEditSatuanLayout = new javax.swing.GroupLayout(pnlEditSatuan);
        pnlEditSatuan.setLayout(pnlEditSatuanLayout);
        pnlEditSatuanLayout.setHorizontalGroup(
            pnlEditSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditSatuanLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlEditSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNamaSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ftxtKodeSatuan))
                .addGroup(pnlEditSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditSatuanLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(txtNamaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEditSatuanLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btnTutup)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        pnlEditSatuanLayout.setVerticalGroup(
            pnlEditSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditSatuanLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pnlEditSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaSatuan)
                    .addComponent(txtNamaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(pnlEditSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditSatuanLayout.createSequentialGroup()
                        .addGroup(pnlEditSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditSatuanLayout.createSequentialGroup()
                        .addComponent(ftxtKodeSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNamaSatuan.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Nama Satuan Tidak Boleh Kosong");
            return;
        }
        
        int KodeSatuan = (((Integer)ftxtKodeSatuan.getValue()).intValue());
        String NamaSatuan = (((String)txtNamaSatuan.getText().trim()).toString());
        
        try {
            Sat.UpdateNamaSatuan(KodeSatuan, NamaSatuan);
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
            
            setVisible(false);
            dispose();
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Memperbarui Satuan : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    public javax.swing.JFormattedTextField ftxtKodeSatuan;
    private javax.swing.JLabel lblNamaSatuan;
    private javax.swing.JPanel pnlEditSatuan;
    public javax.swing.JTextField txtNamaSatuan;
    // End of variables declaration//GEN-END:variables
}
