/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventori.gui;

import Inventori.Items;
import Inventori.Satuan;
import Inventori.StokItem;
import Inventori.StokOpname;
import Transaksi.gui.DataTransaksi;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Yestin
 */
public class PengimputanStokOpname extends javax.swing.JFrame {

    Items Item = new Items();
    StokOpname StokOpname = new StokOpname();
    StokItem StokItem = new StokItem();
    Satuan Sat = new Satuan();
    BackgroundImage BI = new BackgroundImage();
    
    /**
     * Creates new form PengimputanStokOpname
     */
    public PengimputanStokOpname() {
        initComponents();
        setTitle("Pengimputan Stok Opname");
        dchTanggal.setCalendar(Calendar.getInstance());
        dchTanggal.setDateFormatString("dd-MM-yyyy");
        txtBarcode.setText(new String());
        txtBarcode.setText(null);
        txtNamaItem.setText(new String());
        txtNamaItem.setText(null);
        ftxtStokSistem.setValue(new Double(0.00));
        ftxtStokSistem.setValue(null);
        ftxtStokAktual.setValue(new Double(0.00));
        ftxtStokAktual.setValue(null);
        ftxtStokOpname.setValue(new Double(0.00));
        ftxtStokOpname.setValue(null);
        ftxtHargaModal.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                        new DecimalFormat("#,##0"))));
        ftxtHargaModal.setValue(new Double(0.00));
        ftxtKerugian.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
                        new DecimalFormat("#,##0"))));
        ftxtKerugian.setValue(new Double(0.00));
        
        BI.BackgroundJPanel(this, pnlPengimputanStokOpname);
        
        dchTanggal.setDateFormatString("dd-mm-yyyy");
        dchTanggal.setCalendar(Calendar.getInstance());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPengimputanStokOpname = new javax.swing.JPanel();
        dchTanggal = new com.toedter.calendar.JDateChooser();
        lblTanggal = new javax.swing.JLabel();
        lblBarcode = new javax.swing.JLabel();
        ftxtKodeOutlet = new javax.swing.JFormattedTextField();
        txtBarcode = new javax.swing.JTextField();
        btnDataItem = new javax.swing.JButton();
        lblNamaItem = new javax.swing.JLabel();
        txtNamaItem = new javax.swing.JTextField();
        ftxtKodeUser = new javax.swing.JFormattedTextField();
        ftxtKodeSatuan = new javax.swing.JFormattedTextField();
        lblSatuan = new javax.swing.JLabel();
        cboSatuan = new javax.swing.JComboBox<>();
        ftxtKodeStok = new javax.swing.JFormattedTextField();
        lblStokSistem = new javax.swing.JLabel();
        ftxtStokSistem = new javax.swing.JFormattedTextField();
        lblStokAktual = new javax.swing.JLabel();
        ftxtStokAktual = new javax.swing.JFormattedTextField();
        lblStokOpname = new javax.swing.JLabel();
        ftxtStokOpname = new javax.swing.JFormattedTextField();
        lblHargaModal = new javax.swing.JLabel();
        ftxtHargaModal = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        ftxtKerugian = new javax.swing.JFormattedTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        ftxtKodeSO = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPengimputanStokOpname.setForeground(new java.awt.Color(0, 0, 255));

        lblTanggal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(0, 0, 255));
        lblTanggal.setText("Tanggal :");

        lblBarcode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBarcode.setForeground(new java.awt.Color(0, 0, 255));
        lblBarcode.setText("Barcode :");

        ftxtKodeOutlet.setEditable(false);
        ftxtKodeOutlet.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtBarcode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBarcode.setForeground(new java.awt.Color(0, 0, 255));
        txtBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBarcodeKeyPressed(evt);
            }
        });

        btnDataItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/DataItem.png"))); // NOI18N
        btnDataItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataItemActionPerformed(evt);
            }
        });

        lblNamaItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaItem.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaItem.setText("Nama Item :");

        txtNamaItem.setEditable(false);
        txtNamaItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaItem.setForeground(new java.awt.Color(0, 0, 255));

        ftxtKodeUser.setEditable(false);
        ftxtKodeUser.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        ftxtKodeSatuan.setEditable(false);
        ftxtKodeSatuan.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeSatuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblSatuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSatuan.setForeground(new java.awt.Color(0, 0, 255));
        lblSatuan.setText("Satuan :");

        cboSatuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboSatuan.setForeground(new java.awt.Color(0, 0, 255));
        cboSatuan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSatuanItemStateChanged(evt);
            }
        });

        ftxtKodeStok.setEditable(false);
        ftxtKodeStok.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeStok.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblStokSistem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblStokSistem.setForeground(new java.awt.Color(0, 0, 255));
        lblStokSistem.setText("Stok Sistem :");

        ftxtStokSistem.setEditable(false);
        ftxtStokSistem.setForeground(new java.awt.Color(0, 0, 255));
        ftxtStokSistem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblStokAktual.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblStokAktual.setForeground(new java.awt.Color(0, 0, 255));
        lblStokAktual.setText("Stok Aktual :");

        ftxtStokAktual.setForeground(new java.awt.Color(0, 0, 255));
        ftxtStokAktual.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ftxtStokAktual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftxtStokAktualKeyPressed(evt);
            }
        });

        lblStokOpname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblStokOpname.setForeground(new java.awt.Color(0, 0, 255));
        lblStokOpname.setText("Stok Opname :");

        ftxtStokOpname.setEditable(false);
        ftxtStokOpname.setForeground(new java.awt.Color(0, 0, 255));
        ftxtStokOpname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblHargaModal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHargaModal.setForeground(new java.awt.Color(0, 0, 255));
        lblHargaModal.setText("Harga Modal :");

        ftxtHargaModal.setEditable(false);
        ftxtHargaModal.setForeground(new java.awt.Color(0, 0, 255));
        ftxtHargaModal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Kerugian :");

        ftxtKerugian.setEditable(false);
        ftxtKerugian.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKerugian.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        ftxtKodeSO.setEditable(false);
        ftxtKodeSO.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeSO.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlPengimputanStokOpnameLayout = new javax.swing.GroupLayout(pnlPengimputanStokOpname);
        pnlPengimputanStokOpname.setLayout(pnlPengimputanStokOpnameLayout);
        pnlPengimputanStokOpnameLayout.setHorizontalGroup(
            pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPengimputanStokOpnameLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPengimputanStokOpnameLayout.createSequentialGroup()
                        .addComponent(ftxtKodeOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtKodeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtKodeSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtKodeStok, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(lblTanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dchTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(pnlPengimputanStokOpnameLayout.createSequentialGroup()
                        .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBarcode)
                            .addComponent(lblNamaItem)
                            .addComponent(lblSatuan)
                            .addComponent(lblStokSistem)
                            .addComponent(lblStokAktual)
                            .addComponent(lblStokOpname)
                            .addComponent(lblHargaModal)
                            .addComponent(jLabel1))
                        .addGap(56, 56, 56)
                        .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPengimputanStokOpnameLayout.createSequentialGroup()
                                .addComponent(btnDataItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtKodeSO, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtBarcode)
                            .addComponent(txtNamaItem)
                            .addComponent(cboSatuan, 0, 473, Short.MAX_VALUE)
                            .addComponent(ftxtStokSistem)
                            .addComponent(ftxtStokAktual)
                            .addComponent(ftxtStokOpname)
                            .addComponent(ftxtHargaModal)
                            .addComponent(ftxtKerugian))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlPengimputanStokOpnameLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btnSimpan)
                .addGap(111, 111, 111)
                .addComponent(btnTutup)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlPengimputanStokOpnameLayout.setVerticalGroup(
            pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPengimputanStokOpnameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ftxtKodeOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftxtKodeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftxtKodeSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftxtKodeStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarcode)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDataItem)
                    .addComponent(ftxtKodeSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaItem)
                    .addComponent(txtNamaItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSatuan)
                    .addComponent(cboSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStokSistem)
                    .addComponent(ftxtStokSistem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStokAktual)
                    .addComponent(ftxtStokAktual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStokOpname)
                    .addComponent(ftxtStokOpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtHargaModal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHargaModal))
                .addGap(18, 18, 18)
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ftxtKerugian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(pnlPengimputanStokOpnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnTutup))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPengimputanStokOpname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPengimputanStokOpname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataItemActionPerformed
        // TODO add your handling code here:
        DataItems DI = new DataItems(this, true);
        DI.setLocationRelativeTo(this);
        DI.setVisible(true);
        
        Item = DI.getSelectedItems();
        
        Calendar Tanggal = dchTanggal.getCalendar();
        int KodeOutlet = (((Integer)ftxtKodeOutlet.getValue()).intValue());
        String Barcode = Item.getBarcode();
        txtBarcode.setText(new String(Barcode));
        String NamaItem = Item.getNamaItem(Barcode);
        txtNamaItem.setText(new String(NamaItem));
        int KodeUser = (((Integer)ftxtKodeUser.getValue()).intValue());
        StokItem.getSatuan(cboSatuan, Barcode, KodeOutlet);
        String NamaSatuan = ((String)cboSatuan.getSelectedItem()).toString();
        int KodeSatuan = Sat.getKodeSatuan(NamaSatuan);
        ftxtKodeSatuan.setValue(new Integer(KodeSatuan));
        int KodeStok = StokItem.getKodeStok(Barcode,KodeOutlet,KodeSatuan);
        ftxtKodeStok.setValue(new Integer(KodeStok));
        Double StokSistem = StokItem.getKuantitas(KodeStok);
        ftxtStokSistem.setValue(new Double(StokSistem));
        Double HargaModal = StokItem.getHargaModal(KodeStok);
        ftxtHargaModal.setValue(new Double(HargaModal));
        int LastKodeSO = StokOpname.getLastKodeSO(Barcode, KodeOutlet, KodeUser, KodeSatuan, Tanggal);
        ftxtKodeSO.setValue(LastKodeSO);
    }//GEN-LAST:event_btnDataItemActionPerformed

    private void txtBarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            String Barcode = (((String)txtBarcode.getText().trim()).toString());
            
            Calendar Tanggal = dchTanggal.getCalendar();
            String NamaItem = Item.getNamaItem(Barcode);
            txtNamaItem.setText(new String(NamaItem));
            int KodeOutlet = (((Integer)ftxtKodeOutlet.getValue()).intValue());
            int KodeUser = (((Integer)ftxtKodeUser.getValue()).intValue());
            StokItem.getSatuan(cboSatuan, Barcode, KodeOutlet);
            String NamaSatuan = ((String)cboSatuan.getSelectedItem()).toString();
            int KodeSatuan = Sat.getKodeSatuan(NamaSatuan);
            ftxtKodeSatuan.setValue(new Integer(KodeSatuan));
            int KodeStok = StokItem.getKodeStok(Barcode,KodeOutlet,KodeSatuan);
            ftxtKodeStok.setValue(new Integer(KodeStok));
            Double StokSistem = StokItem.getKuantitas(KodeStok);
            ftxtStokSistem.setValue(new Double(StokSistem));
            Double HargaModal = StokItem.getHargaModal(KodeStok);
            ftxtHargaModal.setValue(new Double(HargaModal));
            int LastKodeSO = StokOpname.getLastKodeSO(Barcode, KodeOutlet, KodeUser, KodeSatuan, Tanggal);
            ftxtKodeSO.setValue(LastKodeSO);
        }
    }//GEN-LAST:event_txtBarcodeKeyPressed

    private void cboSatuanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSatuanItemStateChanged
        // TODO add your handling code here:
        Calendar Tanggal = dchTanggal.getCalendar();
        int KodeOutlet = (((Integer)ftxtKodeOutlet.getValue()).intValue());
        int KodeUser = (((Integer)ftxtKodeUser.getValue()).intValue());
        String NamaSatuan = (((String)cboSatuan.getSelectedItem()).toString());
        int KodeSatuan = Sat.getKodeSatuan(NamaSatuan);
        ftxtKodeSatuan.setValue(KodeSatuan);
        String Barcode = (((String)txtBarcode.getText().trim()).toString());
        int KodeStok = StokItem.getKodeStok(Barcode,KodeOutlet,KodeSatuan);
        ftxtKodeStok.setValue(new Integer(KodeStok));
        Double StokSistem = StokItem.getKuantitas(KodeStok);
        ftxtStokSistem.setValue(new Double(StokSistem));
        Double HargaModal = StokItem.getHargaModal(KodeStok);
        ftxtHargaModal.setValue(new Double(HargaModal));
        int LastKodeSO = StokOpname.getLastKodeSO(Barcode, KodeOutlet, KodeUser, KodeSatuan, Tanggal);
        ftxtKodeSO.setValue(new Integer(LastKodeSO));
    }//GEN-LAST:event_cboSatuanItemStateChanged

    private void ftxtStokAktualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtStokAktualKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(txtBarcode.getText().trim().length()==0){
                JOptionPane.showMessageDialog(this, "Barcode Belum Discan atau Barang Belum Dipilih!");
                return;
            }
            
            Double StokSistem = (((Double)ftxtStokSistem.getValue()).doubleValue());
            String StokAktual = (((String)ftxtStokAktual.getText().trim()).toString());
            Double StokReal = Double.valueOf(StokAktual);
            ftxtStokAktual.setValue(new Double(StokReal));
            Double StokOpname = StokSistem - StokReal;
            ftxtStokOpname.setValue(new Double(StokOpname));
            Double HargaModal = (((Double)ftxtHargaModal.getValue()).doubleValue());
            Double Kerugian = StokOpname * HargaModal;
            ftxtKerugian.setValue(new Double(Kerugian));
        }
    }//GEN-LAST:event_ftxtStokAktualKeyPressed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(dchTanggal.getCalendar()==null){
            JOptionPane.showMessageDialog(this, "Tanggal Belum Diisi");
            return;
        }
        if(txtBarcode.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Barcode Belum Diisi");
            return;
        }
        if(ftxtStokAktual.getValue() instanceof Double){
            if(((Double)ftxtStokAktual.getValue()).doubleValue()==0.00 || ftxtStokAktual.getText().trim().length()==0){
                JOptionPane.showMessageDialog(this, "Stok Aktual Belum Diisi!");
                return;
            }
        }
        else if(ftxtStokAktual.getValue() instanceof Long){
            if(((Long)ftxtStokAktual.getValue()).doubleValue()==0.00 || ftxtStokAktual.getText().trim().length()==0){
                JOptionPane.showMessageDialog(this, "Stok Aktual Belum Diisi!");
                return;
            }
        }
        if(ftxtKerugian.getValue() instanceof Double){
            if(((Double)ftxtStokAktual.getValue()).doubleValue()==0.00 || ftxtStokAktual.getText().trim().length()==0){
                JOptionPane.showMessageDialog(this, "Kerugian Belum Dihitung!");
                return;
            }
        }
        else if(ftxtKerugian.getValue() instanceof Long){
            if(((Long)ftxtStokAktual.getValue()).doubleValue()==0.00 || ftxtStokAktual.getText().trim().length()==0){
                JOptionPane.showMessageDialog(this, "Kerugian Belum Dihitung!");
                return;
            }
        }
        String Barcode = (((String)txtBarcode.getText().trim()).toString());
        Calendar Tanggal = dchTanggal.getCalendar();
        int KodeOutlet = (((Integer)ftxtKodeOutlet.getValue()).intValue());
        int KodeUser = (((Integer)ftxtKodeUser.getValue()).intValue());
        int KodeSatuan = (((Integer)ftxtKodeSatuan.getValue()).intValue());
        int KodeStok = (((Integer)ftxtKodeStok.getValue()).intValue());
        int KodeSO = (((Integer)ftxtKodeSO.getValue()).intValue());
        
        Double StokSistem = (((Double)ftxtStokSistem.getValue()).doubleValue());
        Double StokAktual = (((Double)ftxtStokAktual.getValue()).doubleValue());
        Double Selisih = (((Double)ftxtStokOpname.getValue()).doubleValue());
        Double HrgModal = (((Double)ftxtHargaModal.getValue()).doubleValue());
        Double Kerugian = (((Double)ftxtKerugian.getValue()).doubleValue());
        
        try {
            if(KodeSO>0){
                StokOpname.UpdateStokSistem(KodeSO, StokSistem);
                StokOpname.UpdateStokAktual(KodeSO, StokAktual);
                StokOpname.TambahStokOpname(KodeSO, Selisih);
                StokOpname.TambahKerugian(KodeSO, Kerugian);
            }
            else if(KodeSO==0){
                StokOpname.Simpan(Barcode, KodeOutlet, KodeUser, KodeSatuan, Tanggal, StokSistem, StokAktual, Selisih, HrgModal, Kerugian);
            }
            StokItem.UpdateKuantitas(KodeStok, StokAktual);
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            Double StokReal = StokItem.getKuantitas(KodeStok);
            ftxtStokSistem.setValue(new Double(StokReal));;
        }
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Menyimpan Stok Opname : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataItem;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JComboBox<String> cboSatuan;
    private com.toedter.calendar.JDateChooser dchTanggal;
    private javax.swing.JFormattedTextField ftxtHargaModal;
    private javax.swing.JFormattedTextField ftxtKerugian;
    public javax.swing.JFormattedTextField ftxtKodeOutlet;
    public javax.swing.JFormattedTextField ftxtKodeSO;
    public javax.swing.JFormattedTextField ftxtKodeSatuan;
    public javax.swing.JFormattedTextField ftxtKodeStok;
    public javax.swing.JFormattedTextField ftxtKodeUser;
    private javax.swing.JFormattedTextField ftxtStokAktual;
    private javax.swing.JFormattedTextField ftxtStokOpname;
    private javax.swing.JFormattedTextField ftxtStokSistem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JLabel lblHargaModal;
    private javax.swing.JLabel lblNamaItem;
    private javax.swing.JLabel lblSatuan;
    private javax.swing.JLabel lblStokAktual;
    private javax.swing.JLabel lblStokOpname;
    private javax.swing.JLabel lblStokSistem;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JPanel pnlPengimputanStokOpname;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtNamaItem;
    // End of variables declaration//GEN-END:variables
}
