/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventori.gui;

import Inventori.Barang;
import Inventori.Items;
import Inventori.Kategori;
import Inventori.Merek;
import Inventori.Satuan;
import Inventori.StokItem;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import Util.Table;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Yestin
 */
public class RegistrasiItem extends javax.swing.JFrame {

    Items Item = new Items();
    Kategori Kat = new Kategori();
    Merek Merek = new Merek();
    Table Tab = new Table();
    Satuan Sat = new Satuan();
    StokItem StokItem = new StokItem();
    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form RegistrasiItem
     */
    public RegistrasiItem() {
        initComponents();
        setTitle("Registrasi Item");
        BI.BackgroundJPanel(this, pnlRegistrasiItem);
        txtBarcode.setText(new String());
        txtBarcode.setText(null);
        txtNamaItem.setText(new String());
        txtNamaItem.setText(null);
        ftxtKodeMerek.setValue(new Integer(0));
        ftxtKodeMerek.setVisible(false);
        ftxtKodeKategori.setValue(new Integer(0));
        ftxtKodeKategori.setVisible(false);
        Kat.getKategori(cboKategori);
        Merek.getMerek(cboMerek);
//        Sat.getSatuan(cboSatuan);
//        ftxtIsi.setValue(new Double(0.00));
//        ftxtIsi.setValue(null);
//        ftxtStokMax.setValue(new Double(0.00));
//        ftxtStokMax.setValue(null);
//        ftxtStokMin.setValue(new Double(0.00));
//        ftxtStokMin.setValue(null);
//        ftxtHargaModal.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
//                        new DecimalFormat("#,##0"))));
//        ftxtHargaModal.setValue(new Double(0.00));
//        ftxtHargaJual.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(
//                        new DecimalFormat("#,##0"))));
//        ftxtHargaJual.setValue(new Double(0.00));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistrasiItem = new javax.swing.JPanel();
        lblBarcode = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        lblNamaItem = new javax.swing.JLabel();
        txtNamaItem = new javax.swing.JTextField();
        lblJenisItem = new javax.swing.JLabel();
        cboJenisItem = new javax.swing.JComboBox<>();
        lblKategori = new javax.swing.JLabel();
        cboKategori = new javax.swing.JComboBox<>();
        lblMerek = new javax.swing.JLabel();
        cboMerek = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        ftxtKodeKategori = new javax.swing.JFormattedTextField();
        ftxtKodeMerek = new javax.swing.JFormattedTextField();
        btnRegistrasiKategori = new javax.swing.JButton();
        btnRegistrasiMerek = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBersihkan = new javax.swing.JButton();
        ftxtKodeSatuan = new javax.swing.JFormattedTextField();
        ftxtKodeOutlet = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlRegistrasiItem.setBackground(new java.awt.Color(255, 255, 255));

        lblBarcode.setBackground(new java.awt.Color(255, 255, 255));
        lblBarcode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBarcode.setForeground(new java.awt.Color(0, 0, 255));
        lblBarcode.setText("Barcode :");

        txtBarcode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBarcode.setForeground(new java.awt.Color(0, 0, 255));

        lblNamaItem.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaItem.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaItem.setText("Nama Item :");

        txtNamaItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaItem.setForeground(new java.awt.Color(0, 0, 255));

        lblJenisItem.setBackground(new java.awt.Color(255, 255, 255));
        lblJenisItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblJenisItem.setForeground(new java.awt.Color(0, 0, 255));
        lblJenisItem.setText("Jenis Item :");

        cboJenisItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboJenisItem.setForeground(new java.awt.Color(0, 0, 255));
        cboJenisItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -", "Barang", "Jasa" }));

        lblKategori.setBackground(new java.awt.Color(255, 255, 255));
        lblKategori.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKategori.setForeground(new java.awt.Color(0, 0, 255));
        lblKategori.setText("Kategori :");

        cboKategori.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboKategori.setForeground(new java.awt.Color(0, 0, 255));
        cboKategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKategoriItemStateChanged(evt);
            }
        });

        lblMerek.setBackground(new java.awt.Color(255, 255, 255));
        lblMerek.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMerek.setForeground(new java.awt.Color(0, 0, 255));
        lblMerek.setText("Merek :");

        cboMerek.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboMerek.setForeground(new java.awt.Color(0, 0, 255));
        cboMerek.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMerekItemStateChanged(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        ftxtKodeKategori.setEditable(false);
        ftxtKodeKategori.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeKategori.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        ftxtKodeMerek.setEditable(false);
        ftxtKodeMerek.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeMerek.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnRegistrasiKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/RegistrasiKategori.png"))); // NOI18N
        btnRegistrasiKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrasiKategoriActionPerformed(evt);
            }
        });

        btnRegistrasiMerek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/RegistrasiMerek.png"))); // NOI18N
        btnRegistrasiMerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrasiMerekActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnBersihkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Bersihkan2.png"))); // NOI18N
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        ftxtKodeSatuan.setEditable(false);
        ftxtKodeSatuan.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeSatuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        ftxtKodeOutlet.setEditable(false);
        ftxtKodeOutlet.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlRegistrasiItemLayout = new javax.swing.GroupLayout(pnlRegistrasiItem);
        pnlRegistrasiItem.setLayout(pnlRegistrasiItemLayout);
        pnlRegistrasiItemLayout.setHorizontalGroup(
            pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiItemLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrasiItemLayout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh)
                        .addGap(18, 18, 18)
                        .addComponent(btnBersihkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(btnTutup)
                        .addGap(63, 63, 63))
                    .addGroup(pnlRegistrasiItemLayout.createSequentialGroup()
                        .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBarcode)
                            .addComponent(lblNamaItem)
                            .addComponent(lblJenisItem)
                            .addComponent(lblKategori)
                            .addComponent(lblMerek))
                        .addGap(83, 83, 83)
                        .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBarcode)
                            .addComponent(txtNamaItem)
                            .addComponent(cboJenisItem, 0, 462, Short.MAX_VALUE)
                            .addComponent(cboKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboMerek, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlRegistrasiItemLayout.createSequentialGroup()
                                .addComponent(btnRegistrasiMerek)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtKodeMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtKodeSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegistrasiItemLayout.createSequentialGroup()
                                .addComponent(btnRegistrasiKategori)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtKodeKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtKodeOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlRegistrasiItemLayout.setVerticalGroup(
            pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiItemLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarcode)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaItem)
                    .addComponent(txtNamaItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboJenisItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJenisItem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKategori))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftxtKodeKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftxtKodeOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegistrasiKategori))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMerek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftxtKodeMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftxtKodeSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegistrasiMerek))
                .addGap(57, 57, 57)
                .addGroup(pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnTutup, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrasiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBersihkan)
                        .addComponent(btnRefresh)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboKategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKategoriItemStateChanged
        // TODO add your handling code here:

            String Kategori = ((String)cboKategori.getSelectedItem()).toString();
            int Kode = Kategori.indexOf(' ');
            String KodeKaetgori = Kategori.substring(0, Kode);
            int KodeKat = Integer.valueOf(KodeKaetgori);
            ftxtKodeKategori.setValue(new Integer(KodeKat));
        
    }//GEN-LAST:event_cboKategoriItemStateChanged

    private void btnRegistrasiKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrasiKategoriActionPerformed
        // TODO add your handling code here:
        RegistrasiKategori RK = new RegistrasiKategori();
        RK.setLocationRelativeTo(this);
        RK.setVisible(true);
        
        Kat.getKategori(cboKategori);
    }//GEN-LAST:event_btnRegistrasiKategoriActionPerformed

    private void cboMerekItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMerekItemStateChanged
        // TODO add your handling code here:
        
            String Merek = ((String)cboMerek.getSelectedItem()).toString();
            int Kode = Merek.indexOf(' ');
            String KodeMerek = Merek.substring(0, Kode);
            int KodeMrk = Integer.valueOf(KodeMerek);
            ftxtKodeMerek.setValue(new Integer(KodeMrk));
        
    }//GEN-LAST:event_cboMerekItemStateChanged

    private void btnRegistrasiMerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrasiMerekActionPerformed
        // TODO add your handling code here:
        RegistrasiMerek RM = new RegistrasiMerek();
        RM.setLocationRelativeTo(this);
        RM.setVisible(true);
        
        Merek.getMerek(cboMerek);
    }//GEN-LAST:event_btnRegistrasiMerekActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtBarcode.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Barcode Belum Diisi");
            return;
        }
        if(txtNamaItem.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Nama Item Belum Diisi");
            return;
        }
        if(cboJenisItem.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Jenis Item Belum Dipilih");
            return;
        }
//        if(ftxtIsi.getValue() instanceof Double){
//            if(((Double)ftxtIsi.getValue()).doubleValue()==0.00 || ftxtIsi.getText().trim().length()==0){
//                JOptionPane.showMessageDialog(this, "Stok Isi Belum Ditentukan!");
//                return;
//            }
//        }
//        else if(ftxtIsi.getValue() instanceof Long){
//            if(((Long)ftxtIsi.getValue()).doubleValue()==0.00 || ftxtIsi.getText().trim().length()==0){
//                JOptionPane.showMessageDialog(this, "Stok Isi Belum Ditentukan!");
//                return;
//            }
//        }
//        if(ftxtStokMax.getText().trim().length()==0){
//            JOptionPane.showMessageDialog(this, "Stok Maximum Belum Ditentukan!");
//            return;
//        }
//        if(ftxtStokMin.getText().trim().length()==0){
//                JOptionPane.showMessageDialog(this, "Stok Minimum Belum Ditentukan!");
//                return;
//        }
//        if(ftxtHargaModal.getText().trim().length()==0){
//            JOptionPane.showMessageDialog(this, "Stok Harga Modal Belum Ditentukan!");
//            return;
//            
//        }
//        if(ftxtHargaJual.getValue() instanceof Double){
//            if(((Double)ftxtHargaJual.getValue()).doubleValue()==0.00 || ftxtHargaJual.getText().trim().length()==0){
//                JOptionPane.showMessageDialog(this, "Stok Harga Jual Belum Ditentukan!");
//                return;
//            }
//        }
//        else if(ftxtHargaJual.getValue() instanceof Long){
//            if(((Long)ftxtHargaJual.getValue()).doubleValue()==0.00 || ftxtHargaJual.getText().trim().length()==0){
//                JOptionPane.showMessageDialog(this, "Stok Harga Jual Belum Ditentukan!");
//                return;
//            }
//        }
        
        String Barcode = (((String)txtBarcode.getText().trim()).toString());
        boolean KodeBarcode = Item.getKodeBarcode(Barcode);
        Item.setBarcode(Barcode);
        
        String NamaItem = (((String)txtNamaItem.getText().trim()).toString());
        Item.setNamaItem(NamaItem);
        
        int JenisItem = cboJenisItem.getSelectedIndex();
        if(cboJenisItem.getSelectedIndex()==1){
            Item.setJenisItem(1);
        }
        else if(cboJenisItem.getSelectedIndex()==2){
            Item.setJenisItem(2);
        }
        Integer KodeKategori = (((Integer)ftxtKodeKategori.getValue()).intValue());
        Item.setKodeKategori(new Integer(KodeKategori));
        Integer KodeMerek = (((Integer)ftxtKodeMerek.getValue()).intValue());
        Item.setKodeMerek(new Integer(KodeMerek));
        int KodeOutlet = (((Integer)ftxtKodeOutlet.getValue()).intValue());
        StokItem.setKodeOutlet(KodeOutlet);
//        int KodeSatuan = (((Integer)ftxtKodeSatuan.getValue()).intValue());
//        StokItem.setKodeSatuan(KodeSatuan);
//        Double Isi = (((Double)ftxtIsi.getValue()).doubleValue());
//        StokItem.setIsi(Isi);
//        Double StokMax = (((Double)ftxtStokMax.getValue()).doubleValue());
//        StokItem.setStokMax(StokMax);
//        Double StokMin = (((Double)ftxtStokMin.getValue()).doubleValue());
//        StokItem.setStokMin(StokMin);
        
        try {
//            if(!KodeBarcode ){
                Item.Simpan(Barcode, NamaItem, JenisItem, KodeKategori, KodeMerek);
//                if((ftxtHargaModal.getValue() instanceof Long) && (ftxtHargaJual.getValue() instanceof Long) ){
//                    Double HrgModal = (((Long)ftxtHargaModal.getValue()).doubleValue());
//                    StokItem.setHargaModal(HrgModal);
//                    Double HrgJual = (((Long)ftxtHargaJual.getValue()).doubleValue());
//                    StokItem.setHargaJual(HrgJual);
//                    StokItem.Simpan(Barcode, KodeOutlet, KodeSatuan, 0.00, Isi, StokMax, StokMin, HrgModal, HrgJual, 0.00);
//                }
//                else if((ftxtHargaModal.getValue() instanceof Long) && (ftxtHargaJual.getValue() instanceof Double)){
//                    Double HrgModal = (((Long)ftxtHargaModal.getValue()).doubleValue());
//                    StokItem.setHargaModal(HrgModal);
//                    Double HrgJual = (((Double)ftxtHargaJual.getValue()).doubleValue());
//                    StokItem.setHargaJual(HrgJual);
//                    StokItem.Simpan(Barcode, KodeOutlet, KodeSatuan, 0.00, Isi, StokMax, StokMin, HrgModal, HrgJual, 0.00);
//                }
//                else if((ftxtHargaModal.getValue() instanceof Double) && (ftxtHargaJual.getValue() instanceof Long)){
//                    Double HrgModal = (((Double)ftxtHargaModal.getValue()).doubleValue());
//                    StokItem.setHargaModal(HrgModal);
//                    Double HrgJual = (((Long)ftxtHargaJual.getValue()).doubleValue());
//                    StokItem.setHargaJual(HrgJual);
//                    StokItem.Simpan(Barcode, KodeOutlet, KodeSatuan, 0.00, Isi, StokMax, StokMin, HrgModal, HrgJual, 0.00);
//                }
//                else if((ftxtHargaModal.getValue() instanceof Double) && (ftxtHargaJual.getValue() instanceof Double)){
//                    Double HrgModal = (((Double)ftxtHargaModal.getValue()).doubleValue());
//                    StokItem.setHargaModal(HrgModal);
//                    Double HrgJual = (((Double)ftxtHargaJual.getValue()).doubleValue());
//                    StokItem.setHargaJual(HrgJual);
//                    StokItem.Simpan(Barcode, KodeOutlet, KodeSatuan, 0.00, Isi, StokMax, StokMin, HrgModal, HrgJual, 0.00);
//                }
//            }
//            else{
//                if((ftxtHargaModal.getValue() instanceof Long) && (ftxtHargaJual.getValue() instanceof Long) ){
//                    Double HrgModal = (((Long)ftxtHargaModal.getValue()).doubleValue());
//                    StokItem.setHargaModal(HrgModal);
//                    Double HrgJual = (((Long)ftxtHargaJual.getValue()).doubleValue());
//                    StokItem.setHargaJual(HrgJual);
//                    StokItem.Simpan(Barcode, KodeOutlet, KodeSatuan, 0.00, Isi, StokMax, StokMin, HrgModal, HrgJual, 0.00);
//                }
//                else if((ftxtHargaModal.getValue() instanceof Long) && (ftxtHargaJual.getValue() instanceof Double)){
//                    Double HrgModal = (((Long)ftxtHargaModal.getValue()).doubleValue());
//                    StokItem.setHargaModal(HrgModal);
//                    Double HrgJual = (((Double)ftxtHargaJual.getValue()).doubleValue());
//                    StokItem.setHargaJual(HrgJual);
//                    StokItem.Simpan(Barcode, KodeOutlet, KodeSatuan, 0.00, Isi, StokMax, StokMin, HrgModal, HrgJual, 0.00);
//                }
//                else if((ftxtHargaModal.getValue() instanceof Double) && (ftxtHargaJual.getValue() instanceof Long)){
//                    Double HrgModal = (((Double)ftxtHargaModal.getValue()).doubleValue());
//                    StokItem.setHargaModal(HrgModal);
//                    Double HrgJual = (((Long)ftxtHargaJual.getValue()).doubleValue());
//                    StokItem.setHargaJual(HrgJual);
//                    StokItem.Simpan(Barcode, KodeOutlet, KodeSatuan, 0.00, Isi, StokMax, StokMin, HrgModal, HrgJual, 0.00);
//                }
//                else if((ftxtHargaModal.getValue() instanceof Double) && (ftxtHargaJual.getValue() instanceof Double)){
//                    Double HrgModal = (((Double)ftxtHargaModal.getValue()).doubleValue());
//                    StokItem.setHargaModal(HrgModal);
//                    Double HrgJual = (((Double)ftxtHargaJual.getValue()).doubleValue());
//                    StokItem.setHargaJual(HrgJual);
//                    StokItem.Simpan(Barcode, KodeOutlet, KodeSatuan, 0.00, Isi, StokMax, StokMin, HrgModal, HrgJual, 0.00);
//                }
//            }
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Dismpan");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Registrasi Item : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        Kat.getKategori(cboKategori);
        Merek.getMerek(cboMerek);
//        Sat.getSatuan(cboSatuan);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        // TODO add your handling code here:
        txtBarcode.setText(null);
        txtNamaItem.setText(null);
        cboJenisItem.setSelectedIndex(0);
        Kat.getKategori(cboKategori);
        cboKategori.setSelectedIndex(0);
        Merek.getMerek(cboMerek);
        cboMerek.setSelectedIndex(0);
//        Sat.getSatuan(cboSatuan);
//        cboSatuan.setSelectedIndex(0);
//        ftxtIsi.setValue(null);
//        ftxtStokMax.setValue(null);
//        ftxtStokMin.setValue(null);
//        ftxtHargaModal.setValue(null);
//        ftxtHargaJual.setValue(null);
    }//GEN-LAST:event_btnBersihkanActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRegistrasiKategori;
    private javax.swing.JButton btnRegistrasiMerek;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JComboBox<String> cboJenisItem;
    private javax.swing.JComboBox<String> cboKategori;
    private javax.swing.JComboBox<String> cboMerek;
    private javax.swing.JFormattedTextField ftxtKodeKategori;
    private javax.swing.JFormattedTextField ftxtKodeMerek;
    public javax.swing.JFormattedTextField ftxtKodeOutlet;
    private javax.swing.JFormattedTextField ftxtKodeSatuan;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JLabel lblJenisItem;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblMerek;
    private javax.swing.JLabel lblNamaItem;
    private javax.swing.JPanel pnlRegistrasiItem;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtNamaItem;
    // End of variables declaration//GEN-END:variables
}
