/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventori.gui;

import Inventori.Satuan;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Yestin
 */
public class RegistrasiSatuan extends javax.swing.JFrame {

    Satuan Sat = new Satuan();
    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form RegistrasiSatuan
     */
    public RegistrasiSatuan() {
        initComponents();
        setTitle("Registrasi Satuan");
        txtNamaSatuan.setText(new String());
        txtNamaSatuan.setText(null);
        BI.BackgroundJPanel(this, pnlRegistrasiSatuan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistrasiSatuan = new javax.swing.JPanel();
        lblNamaSatuan = new javax.swing.JLabel();
        txtNamaSatuan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNamaSatuan.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaSatuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaSatuan.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaSatuan.setText("Nama Satuan :");

        txtNamaSatuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaSatuan.setForeground(new java.awt.Color(0, 0, 255));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrasiSatuanLayout = new javax.swing.GroupLayout(pnlRegistrasiSatuan);
        pnlRegistrasiSatuan.setLayout(pnlRegistrasiSatuanLayout);
        pnlRegistrasiSatuanLayout.setHorizontalGroup(
            pnlRegistrasiSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiSatuanLayout.createSequentialGroup()
                .addGroup(pnlRegistrasiSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrasiSatuanLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblNamaSatuan)
                        .addGap(62, 62, 62)
                        .addComponent(txtNamaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistrasiSatuanLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnSimpan)
                        .addGap(68, 68, 68)
                        .addComponent(btnTutup)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlRegistrasiSatuanLayout.setVerticalGroup(
            pnlRegistrasiSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiSatuanLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(pnlRegistrasiSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaSatuan)
                    .addComponent(txtNamaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(pnlRegistrasiSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnTutup))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegistrasiSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiSatuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNamaSatuan.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Satuan Belum Diisi");
            return;
        }
        
        String NamaSatuan = (((String)txtNamaSatuan.getText().trim()).toString());
        Sat.setNamaSatuan(NamaSatuan);
        
        try {
            Sat.Simpan(NamaSatuan);
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            txtNamaSatuan.setText(null);
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Menyimpan Satuan : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel lblNamaSatuan;
    private javax.swing.JPanel pnlRegistrasiSatuan;
    private javax.swing.JTextField txtNamaSatuan;
    // End of variables declaration//GEN-END:variables
}
