/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Financial.gui;

import Financial.Penyimpanan;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundPane;
import Util.Table;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.SwingConstants;

/**
 *
 * @author Yestin
 */
public class DataPenyimpanan extends javax.swing.JFrame {

    Penyimpanan Penyimpanan = new Penyimpanan();
    Table Tab = new Table();
    int Left = SwingConstants.LEFT;
    int Right = SwingConstants.RIGHT;
    int Center = SwingConstants.CENTER;
    /**
     * Creates new form DataPenyimpanan
     */
    public DataPenyimpanan() {
        initComponents();
        setTitle("Data Penyimpanan");
        try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlDataPenyimpanan.setOpaque(false);
            Background.add(pnlDataPenyimpanan,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        } 
        catch (IOException ex) {
            Logger.getLogger(RegistrasiKategori.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNamaPenyimpanan.setEnabled(false);
        txtNomor.setEnabled(false);
        Penyimpanan.getPenyimpanan(tblPenyimpanan);
        Tab.TableAlignment2(tblPenyimpanan, Center, Center, Center);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPenyimpanan = new javax.swing.ButtonGroup();
        pnlDataPenyimpanan = new javax.swing.JPanel();
        rbNomor = new javax.swing.JRadioButton();
        txtNomor = new javax.swing.JTextField();
        rbNamaPenyimpanan = new javax.swing.JRadioButton();
        txtNamaPenyimpanan = new javax.swing.JTextField();
        rbSemua = new javax.swing.JRadioButton();
        scrlPenyimpanan = new javax.swing.JScrollPane();
        tblPenyimpanan = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rbNomor.setBackground(new java.awt.Color(255, 255, 255));
        bgPenyimpanan.add(rbNomor);
        rbNomor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbNomor.setForeground(new java.awt.Color(0, 0, 255));
        rbNomor.setText("Nomor :");
        rbNomor.setOpaque(false);
        rbNomor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbNomorItemStateChanged(evt);
            }
        });

        txtNomor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomor.setForeground(new java.awt.Color(0, 0, 255));
        txtNomor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomorKeyPressed(evt);
            }
        });

        rbNamaPenyimpanan.setBackground(new java.awt.Color(255, 255, 255));
        bgPenyimpanan.add(rbNamaPenyimpanan);
        rbNamaPenyimpanan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbNamaPenyimpanan.setForeground(new java.awt.Color(0, 0, 255));
        rbNamaPenyimpanan.setText("Nama Penyimpanan :");
        rbNamaPenyimpanan.setOpaque(false);
        rbNamaPenyimpanan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbNamaPenyimpananItemStateChanged(evt);
            }
        });

        txtNamaPenyimpanan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaPenyimpanan.setForeground(new java.awt.Color(0, 0, 255));
        txtNamaPenyimpanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaPenyimpananKeyPressed(evt);
            }
        });

        rbSemua.setBackground(new java.awt.Color(255, 255, 255));
        bgPenyimpanan.add(rbSemua);
        rbSemua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbSemua.setForeground(new java.awt.Color(0, 0, 255));
        rbSemua.setSelected(true);
        rbSemua.setText("Semua");
        rbSemua.setOpaque(false);
        rbSemua.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSemuaItemStateChanged(evt);
            }
        });

        tblPenyimpanan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblPenyimpanan.setForeground(new java.awt.Color(0, 0, 255));
        scrlPenyimpanan.setViewportView(tblPenyimpanan);

        btnTutup.setBackground(new java.awt.Color(255, 255, 255));
        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N

        btnEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N

        javax.swing.GroupLayout pnlDataPenyimpananLayout = new javax.swing.GroupLayout(pnlDataPenyimpanan);
        pnlDataPenyimpanan.setLayout(pnlDataPenyimpananLayout);
        pnlDataPenyimpananLayout.setHorizontalGroup(
            pnlDataPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataPenyimpananLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(pnlDataPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSemua)
                    .addGroup(pnlDataPenyimpananLayout.createSequentialGroup()
                        .addGroup(pnlDataPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbNomor)
                            .addComponent(rbNamaPenyimpanan))
                        .addGap(42, 42, 42)
                        .addGroup(pnlDataPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomor)
                            .addComponent(txtNamaPenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(227, Short.MAX_VALUE))
            .addComponent(scrlPenyimpanan)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDataPenyimpananLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addGap(29, 29, 29)
                .addComponent(btnTutup)
                .addGap(44, 44, 44))
        );
        pnlDataPenyimpananLayout.setVerticalGroup(
            pnlDataPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataPenyimpananLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDataPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNomor)
                    .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDataPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNamaPenyimpanan)
                    .addComponent(txtNamaPenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rbSemua)
                .addGap(18, 18, 18)
                .addComponent(scrlPenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pnlDataPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDataPenyimpanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDataPenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSemuaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSemuaItemStateChanged
        // TODO add your handling code here:
        Penyimpanan.getPenyimpanan(tblPenyimpanan);
        txtNamaPenyimpanan.setEnabled(false);
        txtNomor.setEnabled(false);
    }//GEN-LAST:event_rbSemuaItemStateChanged

    private void txtNomorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomorKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_A || evt.getKeyCode()==KeyEvent.VK_B || evt.getKeyCode()==KeyEvent.VK_C ||
                evt.getKeyCode()==KeyEvent.VK_D || evt.getKeyCode()==KeyEvent.VK_E || evt.getKeyCode()==KeyEvent.VK_F ||
                evt.getKeyCode()==KeyEvent.VK_G || evt.getKeyCode()==KeyEvent.VK_H || evt.getKeyCode()==KeyEvent.VK_I ||
                evt.getKeyCode()==KeyEvent.VK_J || evt.getKeyCode()==KeyEvent.VK_K || evt.getKeyCode()==KeyEvent.VK_L ||
                evt.getKeyCode()==KeyEvent.VK_M || evt.getKeyCode()==KeyEvent.VK_N || evt.getKeyCode()==KeyEvent.VK_O ||
                evt.getKeyCode()==KeyEvent.VK_P || evt.getKeyCode()==KeyEvent.VK_Q || evt.getKeyCode()==KeyEvent.VK_R ||
                evt.getKeyCode()==KeyEvent.VK_S || evt.getKeyCode()==KeyEvent.VK_T || evt.getKeyCode()==KeyEvent.VK_U ||
                evt.getKeyCode()==KeyEvent.VK_V || evt.getKeyCode()==KeyEvent.VK_W || evt.getKeyCode()==KeyEvent.VK_X ||
                evt.getKeyCode()==KeyEvent.VK_Y || evt.getKeyCode()==KeyEvent.VK_Z || evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode()==KeyEvent.VK_SPACE || evt.getKeyCode()==KeyEvent.VK_0 || evt.getKeyCode()==KeyEvent.VK_1 ||
                evt.getKeyCode()==KeyEvent.VK_2 || evt.getKeyCode()==KeyEvent.VK_3 || evt.getKeyCode()==KeyEvent.VK_4 ||
                evt.getKeyCode()==KeyEvent.VK_5 || evt.getKeyCode()==KeyEvent.VK_6 || evt.getKeyCode()==KeyEvent.VK_7 ||
                evt.getKeyCode()==KeyEvent.VK_8 || evt.getKeyCode()==KeyEvent.VK_9){
            String Nomor = (((String)txtNomor.getText().trim()).toString());
            Penyimpanan.getPenyimpanan2(tblPenyimpanan, Nomor);
            Tab.TableAlignment2(tblPenyimpanan, Center, Center, Center);
        }
    }//GEN-LAST:event_txtNomorKeyPressed

    private void rbNomorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbNomorItemStateChanged
        // TODO add your handling code here:
        txtNomor.setEnabled(true);
        txtNamaPenyimpanan.setEnabled(false);
    }//GEN-LAST:event_rbNomorItemStateChanged

    private void rbNamaPenyimpananItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbNamaPenyimpananItemStateChanged
        // TODO add your handling code here:
        txtNomor.setEnabled(false);
        txtNamaPenyimpanan.setEnabled(true);
    }//GEN-LAST:event_rbNamaPenyimpananItemStateChanged

    private void txtNamaPenyimpananKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaPenyimpananKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_A || evt.getKeyCode()==KeyEvent.VK_B || evt.getKeyCode()==KeyEvent.VK_C ||
                evt.getKeyCode()==KeyEvent.VK_D || evt.getKeyCode()==KeyEvent.VK_E || evt.getKeyCode()==KeyEvent.VK_F ||
                evt.getKeyCode()==KeyEvent.VK_G || evt.getKeyCode()==KeyEvent.VK_H || evt.getKeyCode()==KeyEvent.VK_I ||
                evt.getKeyCode()==KeyEvent.VK_J || evt.getKeyCode()==KeyEvent.VK_K || evt.getKeyCode()==KeyEvent.VK_L ||
                evt.getKeyCode()==KeyEvent.VK_M || evt.getKeyCode()==KeyEvent.VK_N || evt.getKeyCode()==KeyEvent.VK_O ||
                evt.getKeyCode()==KeyEvent.VK_P || evt.getKeyCode()==KeyEvent.VK_Q || evt.getKeyCode()==KeyEvent.VK_R ||
                evt.getKeyCode()==KeyEvent.VK_S || evt.getKeyCode()==KeyEvent.VK_T || evt.getKeyCode()==KeyEvent.VK_U ||
                evt.getKeyCode()==KeyEvent.VK_V || evt.getKeyCode()==KeyEvent.VK_W || evt.getKeyCode()==KeyEvent.VK_X ||
                evt.getKeyCode()==KeyEvent.VK_Y || evt.getKeyCode()==KeyEvent.VK_Z || evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode()==KeyEvent.VK_SPACE || evt.getKeyCode()==KeyEvent.VK_0 || evt.getKeyCode()==KeyEvent.VK_1 ||
                evt.getKeyCode()==KeyEvent.VK_2 || evt.getKeyCode()==KeyEvent.VK_3 || evt.getKeyCode()==KeyEvent.VK_4 ||
                evt.getKeyCode()==KeyEvent.VK_5 || evt.getKeyCode()==KeyEvent.VK_6 || evt.getKeyCode()==KeyEvent.VK_7 ||
                evt.getKeyCode()==KeyEvent.VK_8 || evt.getKeyCode()==KeyEvent.VK_9){
            String NamaPenyimpanan = (((String)txtNamaPenyimpanan.getText().trim()).toString());
            Penyimpanan.getPenyimpanan1(tblPenyimpanan, NamaPenyimpanan);
            Tab.TableAlignment2(tblPenyimpanan, Center, Center, Center);
        }
    }//GEN-LAST:event_txtNamaPenyimpananKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPenyimpanan;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnTutup;
    private javax.swing.JPanel pnlDataPenyimpanan;
    private javax.swing.JRadioButton rbNamaPenyimpanan;
    private javax.swing.JRadioButton rbNomor;
    private javax.swing.JRadioButton rbSemua;
    private javax.swing.JScrollPane scrlPenyimpanan;
    private javax.swing.JTable tblPenyimpanan;
    private javax.swing.JTextField txtNamaPenyimpanan;
    private javax.swing.JTextField txtNomor;
    // End of variables declaration//GEN-END:variables
}
