/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Financial.gui;

import Financial.Penyimpanan;
import Financial.Penyimpanan;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Yestin
 */
public class RegistrasiPenyimpanan extends javax.swing.JFrame {

    Penyimpanan penyimpana = new Penyimpanan();
    /**
     * Creates new form RegistrasiPenyimpanan
     */
    public RegistrasiPenyimpanan() {
        initComponents();
        setTitle("Registrasi Penyimpanan");
        try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlRegistrasiPenyimpanan.setOpaque(false);
            Background.add(pnlRegistrasiPenyimpanan,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        } 
        catch (IOException ex) {
            Logger.getLogger(RegistrasiKategori.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomor.setText(new String());
        txtNomor.setText(null);
        txtNamaPenyimpanan.setText(new String());
        txtNamaPenyimpanan.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistrasiPenyimpanan = new javax.swing.JPanel();
        lblNamaPenyimpanan = new javax.swing.JLabel();
        lblNomor = new javax.swing.JLabel();
        txtNomor = new javax.swing.JTextField();
        txtNamaPenyimpanan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNamaPenyimpanan.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaPenyimpanan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaPenyimpanan.setForeground(new java.awt.Color(0, 0, 255));
        lblNamaPenyimpanan.setText("Nama Penyimpanan :");

        lblNomor.setBackground(new java.awt.Color(255, 255, 255));
        lblNomor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNomor.setForeground(new java.awt.Color(0, 0, 255));
        lblNomor.setText("Nomor :");

        txtNomor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomor.setForeground(new java.awt.Color(0, 0, 255));

        txtNamaPenyimpanan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaPenyimpanan.setForeground(new java.awt.Color(0, 0, 255));

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setBackground(new java.awt.Color(255, 255, 255));
        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("No Rekening Bank/Ovo/Dana/dll");

        javax.swing.GroupLayout pnlRegistrasiPenyimpananLayout = new javax.swing.GroupLayout(pnlRegistrasiPenyimpanan);
        pnlRegistrasiPenyimpanan.setLayout(pnlRegistrasiPenyimpananLayout);
        pnlRegistrasiPenyimpananLayout.setHorizontalGroup(
            pnlRegistrasiPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiPenyimpananLayout.createSequentialGroup()
                .addGroup(pnlRegistrasiPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrasiPenyimpananLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnSimpan)
                        .addGap(84, 84, 84)
                        .addComponent(btnTutup))
                    .addGroup(pnlRegistrasiPenyimpananLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(pnlRegistrasiPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomor)
                            .addComponent(lblNamaPenyimpanan))
                        .addGap(34, 34, 34)
                        .addGroup(pnlRegistrasiPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomor, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(txtNamaPenyimpanan)
                            .addComponent(jLabel1))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        pnlRegistrasiPenyimpananLayout.setVerticalGroup(
            pnlRegistrasiPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrasiPenyimpananLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(pnlRegistrasiPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomor)
                    .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(pnlRegistrasiPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaPenyimpanan)
                    .addComponent(txtNamaPenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134)
                .addGroup(pnlRegistrasiPenyimpananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSimpan)
                    .addComponent(btnTutup))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiPenyimpanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiPenyimpanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNomor.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Nomor Belum Diisi");
            return;
        }
        if(txtNamaPenyimpanan.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Nama Penyimpanan Belum Diisi");
            return;
        }
        
        String Nomor = (((String)txtNomor.getText().trim()).toString());
        String NamaPenyimpanan = (((String)txtNamaPenyimpanan.getText().trim()).toString());
        
        try {
            penyimpana.Simpan(NamaPenyimpanan, Nomor);
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            
            txtNomor.setText(null);
            txtNamaPenyimpanan.setText(null);
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Menyimpan data penyimpanan : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNamaPenyimpanan;
    private javax.swing.JLabel lblNomor;
    private javax.swing.JPanel pnlRegistrasiPenyimpanan;
    private javax.swing.JTextField txtNamaPenyimpanan;
    private javax.swing.JTextField txtNomor;
    // End of variables declaration//GEN-END:variables
}
