/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Orderan.gui;

import Orderan.Mobil;
import Transaksi.gui.DataTransaksi;
import Util.BackgroundPane;
import Util.Table;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yestin
 */
public class DataMobil extends javax.swing.JFrame {

    Mobil mbl = new Mobil();
    Table Tab = new Table();
    
    int Left = SwingConstants.LEFT;
    int Center = SwingConstants.CENTER;
    int Right = SwingConstants.RIGHT;
    /**
     * Creates new form DataMobil
     */
    public DataMobil() {
        initComponents();
        setTitle("Data Mobil");
        try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlDataMobil.setOpaque(false);
            Background.add(pnlDataMobil,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        }
        catch (IOException e) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
        }
        mbl.getMobil(tblMobil);
        Tab.TableAlignment5(tblMobil, Center, Center, Center, Center, Center, Center);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlDataMobil = new javax.swing.JPanel();
        scrlMobil = new javax.swing.JScrollPane();
        tblMobil = new javax.swing.JTable();
        txtNoPolisi = new javax.swing.JTextField();
        rbNoPolisi = new javax.swing.JRadioButton();
        rbJenisMobil = new javax.swing.JRadioButton();
        cboJenisMobil = new javax.swing.JComboBox<>();
        rbSemua = new javax.swing.JRadioButton();
        btnTutup = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblMobil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblMobil.setForeground(new java.awt.Color(0, 0, 255));
        scrlMobil.setViewportView(tblMobil);

        txtNoPolisi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoPolisi.setForeground(new java.awt.Color(0, 0, 255));
        txtNoPolisi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoPolisiKeyPressed(evt);
            }
        });

        rbNoPolisi.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbNoPolisi);
        rbNoPolisi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbNoPolisi.setForeground(new java.awt.Color(0, 0, 255));
        rbNoPolisi.setText("No Polisi :");
        rbNoPolisi.setOpaque(false);
        rbNoPolisi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbNoPolisiItemStateChanged(evt);
            }
        });

        rbJenisMobil.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbJenisMobil);
        rbJenisMobil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbJenisMobil.setForeground(new java.awt.Color(0, 0, 255));
        rbJenisMobil.setText("Jenis Mobil :");
        rbJenisMobil.setOpaque(false);
        rbJenisMobil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbJenisMobilItemStateChanged(evt);
            }
        });

        cboJenisMobil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboJenisMobil.setForeground(new java.awt.Color(0, 0, 255));
        cboJenisMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -", "Pick Up Open", "Pick Up Box", "Truk Box", "Truk Open" }));
        cboJenisMobil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboJenisMobilItemStateChanged(evt);
            }
        });

        rbSemua.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbSemua);
        rbSemua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbSemua.setForeground(new java.awt.Color(0, 0, 255));
        rbSemua.setSelected(true);
        rbSemua.setText("Semua");
        rbSemua.setOpaque(false);
        rbSemua.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSemuaItemStateChanged(evt);
            }
        });

        btnTutup.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDataMobilLayout = new javax.swing.GroupLayout(pnlDataMobil);
        pnlDataMobil.setLayout(pnlDataMobilLayout);
        pnlDataMobilLayout.setHorizontalGroup(
            pnlDataMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlMobil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
            .addGroup(pnlDataMobilLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(pnlDataMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSemua)
                    .addGroup(pnlDataMobilLayout.createSequentialGroup()
                        .addGroup(pnlDataMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbNoPolisi)
                            .addComponent(rbJenisMobil))
                        .addGap(43, 43, 43)
                        .addGroup(pnlDataMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNoPolisi)
                            .addComponent(cboJenisMobil, 0, 364, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDataMobilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(43, 43, 43)
                .addComponent(btnEdit)
                .addGap(36, 36, 36)
                .addComponent(btnTutup)
                .addGap(62, 62, 62))
        );
        pnlDataMobilLayout.setVerticalGroup(
            pnlDataMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataMobilLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlDataMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbNoPolisi))
                .addGap(18, 18, 18)
                .addGroup(pnlDataMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJenisMobil)
                    .addComponent(cboJenisMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rbSemua)
                .addGap(33, 33, 33)
                .addComponent(scrlMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pnlDataMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDataMobilLayout.createSequentialGroup()
                        .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(163, 163, 163))
                    .addGroup(pnlDataMobilLayout.createSequentialGroup()
                        .addGroup(pnlDataMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDataMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDataMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbNoPolisiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbNoPolisiItemStateChanged
        // TODO add your handling code here:
        txtNoPolisi.setEnabled(true);
        cboJenisMobil.setEnabled(false);
    }//GEN-LAST:event_rbNoPolisiItemStateChanged

    private void rbJenisMobilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbJenisMobilItemStateChanged
        // TODO add your handling code here:
        txtNoPolisi.setEnabled(false);
        cboJenisMobil.setEnabled(true);
    }//GEN-LAST:event_rbJenisMobilItemStateChanged

    private void rbSemuaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSemuaItemStateChanged
        // TODO add your handling code here:
        txtNoPolisi.setEnabled(false);
        cboJenisMobil.setEnabled(false);
        mbl.getMobil(tblMobil);
        Tab.TableAlignment5(tblMobil, Center, Center, Center, Center, Center, Center);
    }//GEN-LAST:event_rbSemuaItemStateChanged

    private void txtNoPolisiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPolisiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_A || evt.getKeyCode()==KeyEvent.VK_B || evt.getKeyCode()==KeyEvent.VK_C ||
                evt.getKeyCode()==KeyEvent.VK_D || evt.getKeyCode()==KeyEvent.VK_E || evt.getKeyCode()==KeyEvent.VK_F ||
                evt.getKeyCode()==KeyEvent.VK_G || evt.getKeyCode()==KeyEvent.VK_H || evt.getKeyCode()==KeyEvent.VK_I ||
                evt.getKeyCode()==KeyEvent.VK_J || evt.getKeyCode()==KeyEvent.VK_K || evt.getKeyCode()==KeyEvent.VK_L ||
                evt.getKeyCode()==KeyEvent.VK_M || evt.getKeyCode()==KeyEvent.VK_N || evt.getKeyCode()==KeyEvent.VK_O ||
                evt.getKeyCode()==KeyEvent.VK_P || evt.getKeyCode()==KeyEvent.VK_Q || evt.getKeyCode()==KeyEvent.VK_R ||
                evt.getKeyCode()==KeyEvent.VK_S || evt.getKeyCode()==KeyEvent.VK_T || evt.getKeyCode()==KeyEvent.VK_U ||
                evt.getKeyCode()==KeyEvent.VK_V || evt.getKeyCode()==KeyEvent.VK_W || evt.getKeyCode()==KeyEvent.VK_X ||
                evt.getKeyCode()==KeyEvent.VK_Y || evt.getKeyCode()==KeyEvent.VK_Z || evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode()==KeyEvent.VK_SPACE || evt.getKeyCode()==KeyEvent.VK_0 || evt.getKeyCode()==KeyEvent.VK_1 ||
                evt.getKeyCode()==KeyEvent.VK_2 || evt.getKeyCode()==KeyEvent.VK_3 || evt.getKeyCode()==KeyEvent.VK_4 ||
                evt.getKeyCode()==KeyEvent.VK_5 || evt.getKeyCode()==KeyEvent.VK_6 || evt.getKeyCode()==KeyEvent.VK_7 ||
                evt.getKeyCode()==KeyEvent.VK_8 || evt.getKeyCode()==KeyEvent.VK_9){
            String NoPolisi = (((String)txtNoPolisi.getText().trim()).toString());
            mbl.getMobil(tblMobil, NoPolisi);
            Tab.TableAlignment5(tblMobil, Center, Center, Center, Center, Center, Center);
        }
    }//GEN-LAST:event_txtNoPolisiKeyPressed

    private void cboJenisMobilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboJenisMobilItemStateChanged
        // TODO add your handling code here:
        if(cboJenisMobil.getSelectedIndex()==0){
            mbl.getMobil(tblMobil);
        }
        else if(cboJenisMobil.getSelectedIndex()==1){
            mbl.getMobil(tblMobil, 1);
        }
        else if(cboJenisMobil.getSelectedIndex()==2){
            mbl.getMobil(tblMobil, 2);
        }
        else if(cboJenisMobil.getSelectedIndex()==3){
            mbl.getMobil(tblMobil, 3);
        }
        else if(cboJenisMobil.getSelectedIndex()==4){
            mbl.getMobil(tblMobil, 4);
        }
        Tab.TableAlignment5(tblMobil, Center, Center, Center, Center, Center, Center);
    }//GEN-LAST:event_cboJenisMobilItemStateChanged

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        EditMobil Edit = new EditMobil();
        
        DefaultTableModel dtm = (DefaultTableModel)tblMobil.getModel();
        int row = tblMobil.getSelectedRow();
        int KodeMobil = (((Integer)dtm.getValueAt(row, 0)).intValue());
        Edit.ftxtKodeMobil.setValue(new Integer(KodeMobil));
        String NoPolisi = mbl.getNoPolisi(KodeMobil);
        Edit.txtNoPolisi.setText(new String(NoPolisi));
        String Merek = mbl.getMerek(KodeMobil);
        Edit.txtMerek.setText(new String(Merek));
        String Warna = mbl.getWarna(KodeMobil);
        Edit.txtWarna.setText(new String(Warna));
        
        Edit.setLocationRelativeTo(this);
        Edit.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        if(rbJenisMobil.isSelected()){
            if(cboJenisMobil.getSelectedIndex()==0){
                mbl.getMobil(tblMobil);
            }
            else if(cboJenisMobil.getSelectedIndex()==1){
                mbl.getMobil(tblMobil, 1);
            }
            else if(cboJenisMobil.getSelectedIndex()==2){
                mbl.getMobil(tblMobil, 2);
            }
            else if(cboJenisMobil.getSelectedIndex()==3){
                mbl.getMobil(tblMobil, 3);
            }
            else if(cboJenisMobil.getSelectedIndex()==4){
                mbl.getMobil(tblMobil, 4);
            }
        }
        else if(rbNoPolisi.isSelected()){
            String NoPolisi = (((String)txtNoPolisi.getText().trim()).toString());
            mbl.getMobil(tblMobil, NoPolisi);
        }
        else if(rbSemua.isSelected()){
            mbl.getMobil(tblMobil);
        }
        Tab.TableAlignment5(tblMobil, Center, Center, Center, Center, Center, Center);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTutup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboJenisMobil;
    private javax.swing.JPanel pnlDataMobil;
    private javax.swing.JRadioButton rbJenisMobil;
    private javax.swing.JRadioButton rbNoPolisi;
    private javax.swing.JRadioButton rbSemua;
    private javax.swing.JScrollPane scrlMobil;
    private javax.swing.JTable tblMobil;
    private javax.swing.JTextField txtNoPolisi;
    // End of variables declaration//GEN-END:variables
}
