/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Orderan.gui;

import Orderan.Mobil;
import Transaksi.gui.DataTransaksi;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Yestin
 */
public class EditMobil extends javax.swing.JFrame {

    Mobil Mobil = new Mobil();
    /**
     * Creates new form EditMobil
     */
    public EditMobil() {
        initComponents();
        setTitle("Edit Mobil");
        try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlEditMobil.setOpaque(false);
            Background.add(pnlEditMobil,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        }
        catch (IOException e) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEditMobil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ftxtKodeMobil = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNoPolisi = new javax.swing.JTextField();
        lblJenisMobil = new javax.swing.JLabel();
        cboJenisMobil = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMerek = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtWarna = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Kode Mobil :");

        ftxtKodeMobil.setEditable(false);
        ftxtKodeMobil.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeMobil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("No Polisi :");

        txtNoPolisi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoPolisi.setForeground(new java.awt.Color(0, 0, 255));

        lblJenisMobil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblJenisMobil.setForeground(new java.awt.Color(0, 0, 255));
        lblJenisMobil.setText("Jenis Mobil :");

        cboJenisMobil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboJenisMobil.setForeground(new java.awt.Color(0, 0, 255));
        cboJenisMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -", "Pick Up Open", "Pick Up Box", "Truk Box", "Truk Open" }));
        cboJenisMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboJenisMobilActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Merek :");

        txtMerek.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMerek.setForeground(new java.awt.Color(0, 0, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Warna :");

        txtWarna.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtWarna.setForeground(new java.awt.Color(0, 0, 255));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditMobilLayout = new javax.swing.GroupLayout(pnlEditMobil);
        pnlEditMobil.setLayout(pnlEditMobilLayout);
        pnlEditMobilLayout.setHorizontalGroup(
            pnlEditMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditMobilLayout.createSequentialGroup()
                .addGroup(pnlEditMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditMobilLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnlEditMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblJenisMobil)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(58, 58, 58)
                        .addGroup(pnlEditMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftxtKodeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboJenisMobil, 0, 353, Short.MAX_VALUE)
                            .addComponent(txtNoPolisi)
                            .addComponent(txtMerek)
                            .addComponent(txtWarna)))
                    .addGroup(pnlEditMobilLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnSimpan)
                        .addGap(54, 54, 54)
                        .addComponent(btnTutup)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        pnlEditMobilLayout.setVerticalGroup(
            pnlEditMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditMobilLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlEditMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ftxtKodeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlEditMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNoPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlEditMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblJenisMobil)
                    .addComponent(cboJenisMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlEditMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlEditMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(pnlEditMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboJenisMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboJenisMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboJenisMobilActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNoPolisi.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "No Polisi Belum Diisi");
            return;
        }
        if(txtMerek.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Merek Belum Diisi");
            return;
        }
        if(txtWarna.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Warna Belum Diisi");
            return;
        }
        
        int KodeMobil = (((Integer)ftxtKodeMobil.getValue()).intValue());
        String NoPolisi = (((String)txtNoPolisi.getText().trim()).toString());
        int JenisMobil = cboJenisMobil.getSelectedIndex();
        String Merek = (((String)txtMerek.getText().trim()).toString());
        String Warna = (((String)txtWarna.getText().trim()).toString());
        
        try {
            Mobil.UpdateNoPolisi(KodeMobil, NoPolisi);
            if(JenisMobil>0){
                Mobil.UpdateJenisMobil(KodeMobil, JenisMobil);
            }
            Mobil.UpdateMerek(KodeMobil, Merek);
            Mobil.UpdateWarna(KodeMobil, Warna);
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Memberbarui Data Mobil : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    public javax.swing.JComboBox<String> cboJenisMobil;
    public javax.swing.JFormattedTextField ftxtKodeMobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblJenisMobil;
    private javax.swing.JPanel pnlEditMobil;
    public javax.swing.JTextField txtMerek;
    public javax.swing.JTextField txtNoPolisi;
    public javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
