/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Orderan.gui;

import App.Outlet;
import HumanResource.Identitas;
import HumanResource.Pekerjaan;
import HumanResource.User;
import Orderan.Mobil;
import Orderan.TransferStok;
import Orderan.RincianTransfer;
import Transaksi.gui.DataTransaksi;
import Util.BackgroundPane;
import Util.NumberFormatTableAlignment;
import Util.Table;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yestin
 */
public class HistoriPemindahanStok extends javax.swing.JFrame {

    TransferStok TF = new TransferStok();
    Identitas Id = new Identitas();
    User Usr = new User();
    Pekerjaan Kerja = new Pekerjaan();
    Mobil Mbl = new Mobil();
    Outlet Outlet = new Outlet();
    RincianTransfer RT = new RincianTransfer();
    
    Table Tab = new Table();
    int Left = SwingConstants.LEFT;
    int Center = SwingConstants.CENTER;
    int Right = SwingConstants.RIGHT;
    NumberFormatTableAlignment nfta = new NumberFormatTableAlignment();
    /**
     * Creates new form HistoriPemindahanStok
     */
    public HistoriPemindahanStok() {
        initComponents();
        setTitle("Histori Pemindahan Stok");
         try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlHistoriPemindahan.setOpaque(false);
            Background.add(pnlHistoriPemindahan,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        }
        catch (IOException e) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
        }
        
        mchBulan.getComboBox().setForeground(Color.BLUE);
        TF.getTransferStok(tblHistoriPemindahanStok);
        Tab.TableAlignment11(tblHistoriPemindahanStok, Center, Left, Center, Left, Center, Center, Center, Center, Center, Right, Left, Center);
        tblHistoriPemindahanStok.getColumnModel().getColumn(9).setCellRenderer(nfta);
        tblHistoriPemindahanStok.getColumnModel().getColumn(10).setCellRenderer(nfta);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlHistoriPemindahan = new javax.swing.JPanel();
        rbHarian = new javax.swing.JRadioButton();
        dchTanggal = new com.toedter.calendar.JDateChooser();
        rbPertanggal = new javax.swing.JRadioButton();
        dchTglAwal = new com.toedter.calendar.JDateChooser();
        lblSD = new javax.swing.JLabel();
        dchTglAkhir = new com.toedter.calendar.JDateChooser();
        rbBulan = new javax.swing.JRadioButton();
        mchBulan = new com.toedter.calendar.JMonthChooser();
        ychTahun = new com.toedter.calendar.JYearChooser();
        scrlHistoriPemindahan = new javax.swing.JScrollPane();
        tblHistoriPemindahanStok = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();
        btnLihatRincian = new javax.swing.JButton();
        btnTampilkan = new javax.swing.JButton();
        rbSemua = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rbHarian.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbHarian);
        rbHarian.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbHarian.setForeground(new java.awt.Color(0, 0, 255));
        rbHarian.setText("Harian :");
        rbHarian.setOpaque(false);

        rbPertanggal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbPertanggal);
        rbPertanggal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbPertanggal.setForeground(new java.awt.Color(0, 0, 255));
        rbPertanggal.setText("Per Tanggal :");
        rbPertanggal.setOpaque(false);

        lblSD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSD.setForeground(new java.awt.Color(0, 0, 255));
        lblSD.setText("s/d");

        rbBulan.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbBulan);
        rbBulan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbBulan.setForeground(new java.awt.Color(0, 0, 255));
        rbBulan.setText("Bulan :");
        rbBulan.setOpaque(false);

        mchBulan.setForeground(new java.awt.Color(0, 0, 255));
        mchBulan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tblHistoriPemindahanStok.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblHistoriPemindahanStok.setForeground(new java.awt.Color(0, 0, 255));
        scrlHistoriPemindahan.setViewportView(tblHistoriPemindahanStok);

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N

        btnLihatRincian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/LihatRincian.png"))); // NOI18N
        btnLihatRincian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatRincianActionPerformed(evt);
            }
        });

        btnTampilkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tampilkan.png"))); // NOI18N
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbSemua);
        rbSemua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbSemua.setForeground(new java.awt.Color(0, 0, 255));
        rbSemua.setSelected(true);
        rbSemua.setText("Semua ");

        javax.swing.GroupLayout pnlHistoriPemindahanLayout = new javax.swing.GroupLayout(pnlHistoriPemindahan);
        pnlHistoriPemindahan.setLayout(pnlHistoriPemindahanLayout);
        pnlHistoriPemindahanLayout.setHorizontalGroup(
            pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlHistoriPemindahan)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHistoriPemindahanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLihatRincian)
                .addGap(59, 59, 59)
                .addComponent(btnTutup)
                .addGap(55, 55, 55))
            .addGroup(pnlHistoriPemindahanLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHistoriPemindahanLayout.createSequentialGroup()
                        .addComponent(rbSemua)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlHistoriPemindahanLayout.createSequentialGroup()
                        .addGroup(pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbHarian)
                            .addComponent(rbPertanggal)
                            .addComponent(rbBulan))
                        .addGap(30, 30, 30)
                        .addGroup(pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHistoriPemindahanLayout.createSequentialGroup()
                                .addGroup(pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dchTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(dchTglAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dchTglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlHistoriPemindahanLayout.createSequentialGroup()
                                .addComponent(mchBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ychTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, Short.MAX_VALUE)
                                .addComponent(btnTampilkan)
                                .addGap(270, 270, 270))))))
        );
        pnlHistoriPemindahanLayout.setVerticalGroup(
            pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoriPemindahanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbHarian, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPertanggal)
                    .addGroup(pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dchTglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dchTglAwal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mchBulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbBulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ychTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTampilkan))
                .addGap(10, 10, 10)
                .addComponent(rbSemua)
                .addGap(47, 47, 47)
                .addComponent(scrlHistoriPemindahan, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(pnlHistoriPemindahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTutup)
                    .addComponent(btnLihatRincian))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHistoriPemindahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHistoriPemindahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here:
        
        if(rbHarian.isSelected()){
            Calendar Tanggal = dchTanggal.getCalendar();
            TF.getTransferStok(tblHistoriPemindahanStok, Tanggal);
            Tab.TableAlignment11(tblHistoriPemindahanStok, Center, Left, Center, Left, Center, Center, Center, Center, Right, Right, Left, Center);
            tblHistoriPemindahanStok.getColumnModel().getColumn(9).setCellRenderer(nfta);
            tblHistoriPemindahanStok.getColumnModel().getColumn(10).setCellRenderer(nfta);
        }
        else if(rbPertanggal.isSelected()){
            Calendar TglAwal = dchTglAwal.getCalendar();
            Calendar TglAkhir = dchTglAkhir.getCalendar();
            TF.getTransferStok(tblHistoriPemindahanStok, TglAwal, TglAkhir);
            Tab.TableAlignment11(tblHistoriPemindahanStok, Center, Left, Center, Left, Center, Center, Center, Center, Right, Right, Left, Center);
            tblHistoriPemindahanStok.getColumnModel().getColumn(9).setCellRenderer(nfta);
            tblHistoriPemindahanStok.getColumnModel().getColumn(10).setCellRenderer(nfta);
        }
        else if(rbBulan.isSelected()){
            int Bulan = mchBulan.getMonth()+1;
            int Tahun = ychTahun.getYear();
            TF.getTransferStok(tblHistoriPemindahanStok, Bulan, Tahun);
            Tab.TableAlignment11(tblHistoriPemindahanStok, Center, Left, Center, Left, Center, Center, Center, Center, Right, Right, Left, Center);
            tblHistoriPemindahanStok.getColumnModel().getColumn(9).setCellRenderer(nfta);
            tblHistoriPemindahanStok.getColumnModel().getColumn(10).setCellRenderer(nfta);
        }
        else if(rbSemua.isSelected()){
            TF.getTransferStok(tblHistoriPemindahanStok);
            Tab.TableAlignment11(tblHistoriPemindahanStok, Center, Left, Center, Left, Center, Center, Center, Center, Right, Right, Left, Center);
            tblHistoriPemindahanStok.getColumnModel().getColumn(9).setCellRenderer(nfta);
            tblHistoriPemindahanStok.getColumnModel().getColumn(10).setCellRenderer(nfta);
        }
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnLihatRincianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatRincianActionPerformed
        // TODO add your handling code here:
        RincianTransferstok RTF = new RincianTransferstok();
        
        int row = tblHistoriPemindahanStok.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel)tblHistoriPemindahanStok.getModel();
        int KodeTF = ((Integer)dtm.getValueAt(row, 0)).intValue();
        RTF.ftxtKodeTF.setValue(new Integer(KodeTF));
        Calendar Tanggal = TF.getTanggal(KodeTF);
        RTF.dchTanggal.setCalendar(Tanggal);
        int KodeUser = TF.getKodeUser(KodeTF);
        String NoIdUser = Usr.getNoIdentitas(KodeUser);
        String NamaUser = Id.getNamaLengkap(NoIdUser);
        RTF.txtUser.setText(NamaUser);
        int KodeKerja = TF.getKodeKerja(KodeTF);
        String NoIdDriver = Kerja.getNoIdentitas(KodeKerja);
        String NamaDriver = Id.getNamaLengkap(NoIdDriver);
        RTF.txtDriver.setText(NamaDriver);
        int KodeMobil = TF.getKodeMobil(KodeTF);
        String NoPolisi = Mbl.getNoPolisi(KodeMobil);
        String MerekMobil = Mbl.getMerek(KodeMobil);
        int JenisMobil = Mbl.getJenisMobil(KodeMobil);
        
        if(JenisMobil==1){
            RTF.txtMobil.setText(NoPolisi+", Pick Up, "+MerekMobil);
        }
        else if(JenisMobil==2){
            RTF.txtMobil.setText(NoPolisi+", Box, "+MerekMobil);
        }
        int OutletAsal = TF.getOutletAsal(KodeTF);
        int KodeOutletAsal = Outlet.getKodeOutlet(OutletAsal);
        String NamaOutletAsal = Outlet.getNamaOutlet(KodeOutletAsal);
        RTF.txtOutletAsal.setText(NamaOutletAsal);
        int OutletTujuan = TF.getOutletTujuan(KodeTF);
        int KodeOutletTujuan = Outlet.getKodeOutlet(OutletTujuan);
        String NamaOutletTujuan = Outlet.getNamaOutlet(KodeOutletTujuan);
        RTF.txtOutletTujuan.setText(NamaOutletTujuan);
        int StatusDelivery = TF.getStatusDelivery(KodeTF);
        
        if(StatusDelivery==1){
            RTF.txtStatusDelivery.setText("Dikirim");
        }
        else if(StatusDelivery==2){
            RTF.txtStatusDelivery.setText("Diterima");
        }
        
        Double Biaya = TF.getBiaya(KodeTF);
        RTF.ftxtBiaya.setValue(new Double(Biaya));
        String Keterangan = TF.getKeterangan(KodeTF);
        RTF.txtKeterangan.setText(new String(Keterangan));
        int KodePenerima = TF.getKodePenerima(KodeTF);
        String NoIdPenerima = Usr.getNoIdentitas(KodePenerima);
        String Penerima = Id.getNamaLengkap(NoIdPenerima);
        RTF.txtPenerima.setText(Penerima);
        
        RT.getRincianTransfer(RTF.tblRincianTransfer, KodeTF);
        
        int Left = SwingConstants.LEFT;
        int Center = SwingConstants.CENTER;
        int Right = SwingConstants.RIGHT;
        
        Tab.TableAlignment6(RTF.tblRincianTransfer, Left, Left, Center, Center, Right, Right, Center);
        RTF.tblRincianTransfer.getColumnModel().getColumn(4).setCellRenderer(nfta);
        RTF.tblRincianTransfer.getColumnModel().getColumn(5).setCellRenderer(nfta);
        
        RTF.HitungGrandTotal();
        
        RTF.setLocationRelativeTo(this);
        RTF.setVisible(true);
    }//GEN-LAST:event_btnLihatRincianActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLihatRincian;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JButton btnTutup;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dchTanggal;
    private com.toedter.calendar.JDateChooser dchTglAkhir;
    private com.toedter.calendar.JDateChooser dchTglAwal;
    private javax.swing.JLabel lblSD;
    private com.toedter.calendar.JMonthChooser mchBulan;
    private javax.swing.JPanel pnlHistoriPemindahan;
    private javax.swing.JRadioButton rbBulan;
    private javax.swing.JRadioButton rbHarian;
    private javax.swing.JRadioButton rbPertanggal;
    private javax.swing.JRadioButton rbSemua;
    private javax.swing.JScrollPane scrlHistoriPemindahan;
    private javax.swing.JTable tblHistoriPemindahanStok;
    private com.toedter.calendar.JYearChooser ychTahun;
    // End of variables declaration//GEN-END:variables
}
