/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Orderan.gui;

import Orderan.Mobil;
import Transaksi.gui.DataTransaksi;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Yestin
 */
public class RegistrasiMobil extends javax.swing.JFrame {

    Mobil Mbl = new Mobil();
    /**
     * Creates new form RegistrasiMobil
     */
    public RegistrasiMobil() {
        initComponents();
        setTitle("Registrasi Mobil");
        try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlRegistrasiMobil.setOpaque(false);
            Background.add(pnlRegistrasiMobil,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        }
        catch (IOException e) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
        }
        txtNoPolisi.setText(new String());
        txtNoPolisi.setText(null);
        txtMerek.setText(new String());
        txtMerek.setText(null);
        txtWarna.setText(new String());
        txtWarna.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistrasiMobil = new javax.swing.JPanel();
        lblNoPolisi = new javax.swing.JLabel();
        txtNoPolisi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboJenisMobil = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtMerek = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtWarna = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNoPolisi.setBackground(new java.awt.Color(255, 255, 255));
        lblNoPolisi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNoPolisi.setForeground(new java.awt.Color(0, 0, 255));
        lblNoPolisi.setText("No Polisi :");

        txtNoPolisi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoPolisi.setForeground(new java.awt.Color(0, 0, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Jenis Mobil :");

        cboJenisMobil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboJenisMobil.setForeground(new java.awt.Color(0, 0, 255));
        cboJenisMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -", "Pick Up Open", "Pick Up Box", "Truk Box", "Truk Open" }));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Merek :");

        txtMerek.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMerek.setForeground(new java.awt.Color(0, 0, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Warna :");

        txtWarna.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtWarna.setForeground(new java.awt.Color(0, 0, 255));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrasiMobilLayout = new javax.swing.GroupLayout(pnlRegistrasiMobil);
        pnlRegistrasiMobil.setLayout(pnlRegistrasiMobilLayout);
        pnlRegistrasiMobilLayout.setHorizontalGroup(
            pnlRegistrasiMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiMobilLayout.createSequentialGroup()
                .addGroup(pnlRegistrasiMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrasiMobilLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(pnlRegistrasiMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNoPolisi)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(51, 51, 51)
                        .addGroup(pnlRegistrasiMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNoPolisi)
                            .addComponent(cboJenisMobil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMerek)
                            .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRegistrasiMobilLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnSimpan)
                        .addGap(59, 59, 59)
                        .addComponent(btnTutup)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        pnlRegistrasiMobilLayout.setVerticalGroup(
            pnlRegistrasiMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiMobilLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnlRegistrasiMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoPolisi)
                    .addComponent(txtNoPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlRegistrasiMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboJenisMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlRegistrasiMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlRegistrasiMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(pnlRegistrasiMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNoPolisi.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "No Polisi Belum Diisi");
            return;
        }
        if(cboJenisMobil.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Jenis Mobil Belum Dipilih");
            return;
        }
        if(txtMerek.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Merek Belum Diisi");
            return;
        }
        if(txtWarna.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Warna Belum Diisi");
            return;
        }
        
        String NoPolisi = (((String)txtNoPolisi.getText().trim()).toString());
        Mbl.setNoPolisi(NoPolisi);
        String Merek = (((String)txtMerek.getText().trim()).toString());
        Mbl.setMerek(Merek);
        String Warna = (((String)txtWarna.getText().trim()).toString());
        Mbl.setWarna(Warna);
        
        try {
            if(cboJenisMobil.getSelectedIndex()==1){
                Mbl.Simpan(NoPolisi, 1, Merek, Warna);
            }
            else if(cboJenisMobil.getSelectedIndex()==2){
                Mbl.Simpan(NoPolisi, 2, Merek, Warna);
            }
            else if(cboJenisMobil.getSelectedIndex()==3){
                Mbl.Simpan(NoPolisi, 3, Merek, Warna);
            }
            else if(cboJenisMobil.getSelectedIndex()==4){
                Mbl.Simpan(NoPolisi, 4, Merek, Warna);
            }
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            txtNoPolisi.setText(null);
            cboJenisMobil.setSelectedIndex(0);
            txtMerek.setText(null);
            txtWarna.setText(null);
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Registrasi Mobil : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JComboBox<String> cboJenisMobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNoPolisi;
    private javax.swing.JPanel pnlRegistrasiMobil;
    private javax.swing.JTextField txtMerek;
    private javax.swing.JTextField txtNoPolisi;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
