/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Orderan.gui;

import Transaksi.gui.DataTransaksi;
import Util.BackgroundPane;
import Util.DBConnector;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dialog;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.type.OrientationEnum;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Yestin
 */
public class RincianTransferstok extends javax.swing.JFrame {

    /**
     * Creates new form RincianTransferstok
     */
    public RincianTransferstok() {
        initComponents();
        setTitle("Rincian Pemindahan Stok");
        try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlRincianTransferstok.setOpaque(false);
            Background.add(pnlRincianTransferstok,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        }
        catch (IOException e) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
        }
        dchTanggal.setDateFormatString("dd-MM-yyyy");
        dchTanggal.getCalendarButton().setVisible(false);
        ((JTextFieldDateEditor)dchTanggal.getDateEditor()).setForeground(Color.BLUE);
        ((JTextFieldDateEditor)dchTanggal.getDateEditor()).setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRincianTransferstok = new javax.swing.JPanel();
        lblKodeTF = new javax.swing.JLabel();
        ftxtKodeTF = new javax.swing.JFormattedTextField();
        lblTanggal = new javax.swing.JLabel();
        dchTanggal = new com.toedter.calendar.JDateChooser();
        lblDriver = new javax.swing.JLabel();
        txtDriver = new javax.swing.JTextField();
        lblMobil = new javax.swing.JLabel();
        txtMobil = new javax.swing.JTextField();
        lblOutletAsal = new javax.swing.JLabel();
        txtOutletAsal = new javax.swing.JTextField();
        lblOutletTujuan = new javax.swing.JLabel();
        txtOutletTujuan = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        scrlRincianTransfer = new javax.swing.JScrollPane();
        tblRincianTransfer = new javax.swing.JTable();
        lblStatusDelivery = new javax.swing.JLabel();
        txtStatusDelivery = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ftxtBiaya = new javax.swing.JFormattedTextField();
        lblKeterangan = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        ftxtGrandTotalModal = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();
        lblPenerima = new javax.swing.JLabel();
        txtPenerima = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblKodeTF.setBackground(new java.awt.Color(255, 255, 255));
        lblKodeTF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKodeTF.setForeground(new java.awt.Color(0, 0, 255));
        lblKodeTF.setText("KodeTF :");

        ftxtKodeTF.setEditable(false);
        ftxtKodeTF.setForeground(new java.awt.Color(0, 0, 255));
        ftxtKodeTF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblTanggal.setBackground(new java.awt.Color(255, 255, 255));
        lblTanggal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(0, 0, 255));
        lblTanggal.setText("Tanggal :");

        lblDriver.setBackground(new java.awt.Color(255, 255, 255));
        lblDriver.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDriver.setForeground(new java.awt.Color(0, 0, 255));
        lblDriver.setText("Driver :");

        txtDriver.setEditable(false);
        txtDriver.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDriver.setForeground(new java.awt.Color(0, 0, 255));

        lblMobil.setBackground(new java.awt.Color(255, 255, 255));
        lblMobil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMobil.setForeground(new java.awt.Color(0, 0, 255));
        lblMobil.setText("Mobil :");

        txtMobil.setEditable(false);
        txtMobil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMobil.setForeground(new java.awt.Color(0, 0, 255));

        lblOutletAsal.setBackground(new java.awt.Color(255, 255, 255));
        lblOutletAsal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblOutletAsal.setForeground(new java.awt.Color(0, 0, 255));
        lblOutletAsal.setText("Outlet Asal :");

        txtOutletAsal.setEditable(false);
        txtOutletAsal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtOutletAsal.setForeground(new java.awt.Color(0, 0, 255));

        lblOutletTujuan.setBackground(new java.awt.Color(255, 255, 255));
        lblOutletTujuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblOutletTujuan.setForeground(new java.awt.Color(0, 0, 255));
        lblOutletTujuan.setText("Outlet Tujuan :");

        txtOutletTujuan.setEditable(false);
        txtOutletTujuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtOutletTujuan.setForeground(new java.awt.Color(0, 0, 255));

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 0, 255));
        lblUser.setText("Pengirim :");

        txtUser.setEditable(false);
        txtUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 0, 255));

        tblRincianTransfer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblRincianTransfer.setForeground(new java.awt.Color(0, 0, 255));
        scrlRincianTransfer.setViewportView(tblRincianTransfer);

        lblStatusDelivery.setBackground(new java.awt.Color(255, 255, 255));
        lblStatusDelivery.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblStatusDelivery.setForeground(new java.awt.Color(0, 0, 255));
        lblStatusDelivery.setText("Status Delivery :");

        txtStatusDelivery.setEditable(false);
        txtStatusDelivery.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtStatusDelivery.setForeground(new java.awt.Color(0, 0, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Biaya :");

        ftxtBiaya.setEditable(false);
        ftxtBiaya.setForeground(new java.awt.Color(0, 0, 255));
        ftxtBiaya.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblKeterangan.setBackground(new java.awt.Color(255, 255, 255));
        lblKeterangan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKeterangan.setForeground(new java.awt.Color(0, 0, 255));
        lblKeterangan.setText("Keterangan :");

        txtKeterangan.setEditable(false);
        txtKeterangan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKeterangan.setForeground(new java.awt.Color(0, 0, 255));

        ftxtGrandTotalModal.setEditable(false);
        ftxtGrandTotalModal.setForeground(new java.awt.Color(0, 0, 255));
        ftxtGrandTotalModal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Grand Total Modal :");

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N

        lblPenerima.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPenerima.setForeground(new java.awt.Color(0, 0, 255));
        lblPenerima.setText("Penerima :");

        txtPenerima.setEditable(false);
        txtPenerima.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPenerima.setForeground(new java.awt.Color(0, 0, 255));
        txtPenerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenerimaActionPerformed(evt);
            }
        });

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cetak.png"))); // NOI18N
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRincianTransferstokLayout = new javax.swing.GroupLayout(pnlRincianTransferstok);
        pnlRincianTransferstok.setLayout(pnlRincianTransferstokLayout);
        pnlRincianTransferstokLayout.setHorizontalGroup(
            pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRincianTransferstokLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRincianTransferstokLayout.createSequentialGroup()
                        .addComponent(lblKodeTF)
                        .addGap(29, 29, 29)
                        .addComponent(ftxtKodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dchTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(pnlRincianTransferstokLayout.createSequentialGroup()
                        .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRincianTransferstokLayout.createSequentialGroup()
                                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDriver)
                                    .addComponent(lblUser))
                                .addGap(85, 85, 85)
                                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtOutletTujuan, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                                    .addComponent(txtOutletAsal)
                                    .addComponent(txtMobil)
                                    .addComponent(txtDriver)
                                    .addComponent(txtUser)))
                            .addComponent(lblOutletTujuan)
                            .addComponent(lblOutletAsal)
                            .addComponent(lblMobil))
                        .addGap(57, 57, 57)
                        .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusDelivery)
                            .addComponent(jLabel2)
                            .addComponent(lblKeterangan)
                            .addComponent(lblPenerima))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStatusDelivery)
                            .addComponent(ftxtBiaya)
                            .addComponent(txtKeterangan)
                            .addComponent(txtPenerima))))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRincianTransferstokLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRincianTransferstokLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(ftxtGrandTotalModal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRincianTransferstokLayout.createSequentialGroup()
                        .addComponent(btnCetak)
                        .addGap(38, 38, 38)
                        .addComponent(btnTutup)
                        .addGap(65, 65, 65))))
            .addGroup(pnlRincianTransferstokLayout.createSequentialGroup()
                .addComponent(scrlRincianTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 1112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRincianTransferstokLayout.setVerticalGroup(
            pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRincianTransferstokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dchTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblKodeTF)
                        .addComponent(ftxtKodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTanggal)))
                .addGap(22, 22, 22)
                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatusDelivery)
                    .addComponent(txtStatusDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDriver)
                    .addComponent(txtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ftxtBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobil)
                    .addComponent(txtMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKeterangan)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutletAsal)
                    .addComponent(txtOutletAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPenerima)
                    .addComponent(txtPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutletTujuan)
                    .addComponent(txtOutletTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(scrlRincianTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtGrandTotalModal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(pnlRincianTransferstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTutup)
                    .addComponent(btnCetak))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRincianTransferstok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRincianTransferstok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPenerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenerimaActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        if(ftxtKodeTF.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "KodeTF Stok Belum Ada");
            return;
        }
        int KodeTF = (((Integer)ftxtKodeTF.getValue()).intValue());
        JasperPrint JP = null;
        String ReportPath = "\\E-POS\\Report\\";
        String ReportFileName = null;
        URL Resource = this.getClass().getResource(ReportPath);
        try {
            java.util.Map<String,Object> params = new java.util.HashMap<String,Object>();
            params.put("KodeTF", Integer.valueOf(KodeTF));
            
            ReportFileName = ReportPath + "SuratJalan2.jasper";
            JP = JasperFillManager.fillReport(ReportFileName, params, DBConnector.getConnection());
            
            JP.setOrientation(OrientationEnum.PORTRAIT);
            JasperViewer JV = new JasperViewer(JP, false);
            JV.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            JV.setVisible(true);
            JV.setFitPageZoomRatio();
        } 
        catch (JRException e) {
            e.printStackTrace();
            return;
        }
        catch (Exception e){
            e.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    public void HitungGrandTotal(){
        DefaultTableModel dtm = (DefaultTableModel)tblRincianTransfer.getModel();
        Double GrandTotal = 0.00;
        for(int i=0;i<dtm.getRowCount();i++){
            Double Total = ((Double)dtm.getValueAt(i, 5)).doubleValue();
            GrandTotal += Total;
        }
        
        ftxtGrandTotalModal.setValue(new Double(GrandTotal));
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTutup;
    public com.toedter.calendar.JDateChooser dchTanggal;
    public javax.swing.JFormattedTextField ftxtBiaya;
    public javax.swing.JFormattedTextField ftxtGrandTotalModal;
    public javax.swing.JFormattedTextField ftxtKodeTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblKodeTF;
    private javax.swing.JLabel lblMobil;
    private javax.swing.JLabel lblOutletAsal;
    private javax.swing.JLabel lblOutletTujuan;
    private javax.swing.JLabel lblPenerima;
    private javax.swing.JLabel lblStatusDelivery;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlRincianTransferstok;
    public javax.swing.JScrollPane scrlRincianTransfer;
    public javax.swing.JTable tblRincianTransfer;
    public javax.swing.JTextField txtDriver;
    public javax.swing.JTextField txtKeterangan;
    public javax.swing.JTextField txtMobil;
    public javax.swing.JTextField txtOutletAsal;
    public javax.swing.JTextField txtOutletTujuan;
    public javax.swing.JTextField txtPenerima;
    public javax.swing.JTextField txtStatusDelivery;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
