/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.gui;

import App.Outlet;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.Table;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.SwingConstants;

/**
 *
 * @author Yestin
 */
public class DaftarOutlet extends javax.swing.JFrame {

    Outlet cab = new Outlet();
    Table Tab = new Table();
    int Left = SwingConstants.LEFT;
    int Center = SwingConstants.CENTER;
    int Right = SwingConstants.RIGHT;
    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form DaftarOutlet
     */
    public DaftarOutlet() {
        initComponents();
        setTitle("Daftar Outlet");
        txtNamaOutlet.setText(new String());
        txtNamaOutlet.setText(null);
        BI.BackgroundJPanel(this, pnlDaftarOutlet);
        cab.getOutlet(tblOutlet);
        Tab.TableAlignment2(tblOutlet, Center, Right, Center);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDaftarOutlet = new javax.swing.JPanel();
        lblNamaOutlet = new javax.swing.JLabel();
        txtNamaOutlet = new javax.swing.JTextField();
        scrlOutlet = new javax.swing.JScrollPane();
        tblOutlet = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNamaOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaOutlet.setForeground(new java.awt.Color(51, 51, 255));
        lblNamaOutlet.setText("Nama Outlet :");

        txtNamaOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaOutlet.setForeground(new java.awt.Color(0, 0, 255));
        txtNamaOutlet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaOutletKeyPressed(evt);
            }
        });

        tblOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblOutlet.setForeground(new java.awt.Color(0, 0, 255));
        scrlOutlet.setViewportView(tblOutlet);

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDaftarOutletLayout = new javax.swing.GroupLayout(pnlDaftarOutlet);
        pnlDaftarOutlet.setLayout(pnlDaftarOutletLayout);
        pnlDaftarOutletLayout.setHorizontalGroup(
            pnlDaftarOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarOutletLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblNamaOutlet)
                .addGap(45, 45, 45)
                .addComponent(txtNamaOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
            .addComponent(scrlOutlet)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDaftarOutletLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addGap(50, 50, 50)
                .addComponent(btnTutup)
                .addGap(52, 52, 52))
        );
        pnlDaftarOutletLayout.setVerticalGroup(
            pnlDaftarOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarOutletLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlDaftarOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaOutlet)
                    .addComponent(txtNamaOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(scrlOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlDaftarOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDaftarOutlet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDaftarOutlet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaOutletKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaOutletKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_A || evt.getKeyCode()==KeyEvent.VK_B || evt.getKeyCode()==KeyEvent.VK_C ||
                evt.getKeyCode()==KeyEvent.VK_D || evt.getKeyCode()==KeyEvent.VK_E || evt.getKeyCode()==KeyEvent.VK_F ||
                evt.getKeyCode()==KeyEvent.VK_G || evt.getKeyCode()==KeyEvent.VK_H || evt.getKeyCode()==KeyEvent.VK_I ||
                evt.getKeyCode()==KeyEvent.VK_J || evt.getKeyCode()==KeyEvent.VK_K || evt.getKeyCode()==KeyEvent.VK_L ||
                evt.getKeyCode()==KeyEvent.VK_M || evt.getKeyCode()==KeyEvent.VK_N || evt.getKeyCode()==KeyEvent.VK_O ||
                evt.getKeyCode()==KeyEvent.VK_P || evt.getKeyCode()==KeyEvent.VK_Q || evt.getKeyCode()==KeyEvent.VK_R ||
                evt.getKeyCode()==KeyEvent.VK_S || evt.getKeyCode()==KeyEvent.VK_T || evt.getKeyCode()==KeyEvent.VK_U ||
                evt.getKeyCode()==KeyEvent.VK_V || evt.getKeyCode()==KeyEvent.VK_W || evt.getKeyCode()==KeyEvent.VK_X ||
                evt.getKeyCode()==KeyEvent.VK_Y || evt.getKeyCode()==KeyEvent.VK_Z || evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode()==KeyEvent.VK_SPACE || evt.getKeyCode()==KeyEvent.VK_0 || evt.getKeyCode()==KeyEvent.VK_1 ||
                evt.getKeyCode()==KeyEvent.VK_2 || evt.getKeyCode()==KeyEvent.VK_3 || evt.getKeyCode()==KeyEvent.VK_4 ||
                evt.getKeyCode()==KeyEvent.VK_5 || evt.getKeyCode()==KeyEvent.VK_6 || evt.getKeyCode()==KeyEvent.VK_7 ||
                evt.getKeyCode()==KeyEvent.VK_8 || evt.getKeyCode()==KeyEvent.VK_9){
            String NamaOutlet = (((String)txtNamaOutlet.getText().trim()).toString());
            cab.getOutlet(tblOutlet, NamaOutlet);
            Tab.TableAlignment2(tblOutlet, Center, Right, Center);
        }
    }//GEN-LAST:event_txtNamaOutletKeyPressed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel lblNamaOutlet;
    private javax.swing.JPanel pnlDaftarOutlet;
    private javax.swing.JScrollPane scrlOutlet;
    private javax.swing.JTable tblOutlet;
    private javax.swing.JTextField txtNamaOutlet;
    // End of variables declaration//GEN-END:variables
}
