/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package App.gui;

import Inventori.gui.PenerimaanBarangSupplier;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundPane;
import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import javax.swing.*;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import Util.BackgroundImage;
import java.awt.event.KeyEvent;
import java.awt.BorderLayout;

/**
 *
 * @author Yestin
 */
public class MainForm extends javax.swing.JFrame {

    BackgroundImage BI = new BackgroundImage();
    BackgroundPane BP = new BackgroundPane();
    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        setTitle("E-POS");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
//        ImageIcon ImgIcon = new ImageIcon("\\E-POS\\Background.jpeg");
//        
//        Dimension ScreenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        lblBackground.setBounds(0, 0, ScreenSize.width, ScreenSize.height);
//        Rectangle rect = lblBackground.getBounds();
//        Image ScaleImage = ImgIcon.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_SMOOTH);
//        ImgIcon = new ImageIcon(ScaleImage);
//        dpAplikasi.setBounds(0, 0, ScreenSize.width, ScreenSize.height);
//        dpAplikasi.setAlignmentX(CENTER_ALIGNMENT);
//        dpAplikasi.setAlignmentY(CENTER_ALIGNMENT);
//        lblBackground.setIcon(ImgIcon);
//        lblBackground.setAlignmentX(CENTER_ALIGNMENT);
//        lblBackground.setAlignmentY(CENTER_ALIGNMENT);
//        btnRegistrasiKategori.setSize(ScreenSize);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        tpFitur = new javax.swing.JTabbedPane();
        pnlInventori = new javax.swing.JPanel();
        pnlPenjualan = new javax.swing.JPanel();
        pnlAdministrasi = new javax.swing.JPanel();
        pnlUser = new javax.swing.JPanel();
        pnlData = new javax.swing.JPanel();
        btnRegistrasiKategori = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpFitur.setBackground(new java.awt.Color(51, 153, 255));
        tpFitur.setForeground(new java.awt.Color(0, 0, 255));
        tpFitur.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        pnlInventori.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout pnlInventoriLayout = new javax.swing.GroupLayout(pnlInventori);
        pnlInventori.setLayout(pnlInventoriLayout);
        pnlInventoriLayout.setHorizontalGroup(
            pnlInventoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2043, Short.MAX_VALUE)
        );
        pnlInventoriLayout.setVerticalGroup(
            pnlInventoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );

        tpFitur.addTab("Inventori", pnlInventori);

        pnlPenjualan.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout pnlPenjualanLayout = new javax.swing.GroupLayout(pnlPenjualan);
        pnlPenjualan.setLayout(pnlPenjualanLayout);
        pnlPenjualanLayout.setHorizontalGroup(
            pnlPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2043, Short.MAX_VALUE)
        );
        pnlPenjualanLayout.setVerticalGroup(
            pnlPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );

        tpFitur.addTab("Penjualan", pnlPenjualan);

        pnlAdministrasi.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout pnlAdministrasiLayout = new javax.swing.GroupLayout(pnlAdministrasi);
        pnlAdministrasi.setLayout(pnlAdministrasiLayout);
        pnlAdministrasiLayout.setHorizontalGroup(
            pnlAdministrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2043, Short.MAX_VALUE)
        );
        pnlAdministrasiLayout.setVerticalGroup(
            pnlAdministrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );

        tpFitur.addTab("Administrasi", pnlAdministrasi);

        pnlUser.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );

        tpFitur.addTab("User", pnlUser);

        pnlData.setBackground(new java.awt.Color(51, 153, 255));

        btnRegistrasiKategori.setText("jButton1");
        btnRegistrasiKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrasiKategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDataLayout = new javax.swing.GroupLayout(pnlData);
        pnlData.setLayout(pnlDataLayout);
        pnlDataLayout.setHorizontalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrasiKategori)
                .addContainerGap(1935, Short.MAX_VALUE))
        );
        pnlDataLayout.setVerticalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrasiKategori)
                .addContainerGap(1065, Short.MAX_VALUE))
        );

        tpFitur.addTab("Data", pnlData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpFitur)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpFitur, javax.swing.GroupLayout.PREFERRED_SIZE, 1146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrasiKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrasiKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrasiKategoriActionPerformed

//    public JDesktopPane getDesktopPane(){
////        return dpAplikasi;
//    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrasiKategori;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JPanel pnlAdministrasi;
    public javax.swing.JPanel pnlData;
    public javax.swing.JPanel pnlInventori;
    private javax.swing.JPanel pnlPenjualan;
    public javax.swing.JPanel pnlUser;
    public javax.swing.JTabbedPane tpFitur;
    // End of variables declaration//GEN-END:variables

}
