/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.gui;

import App.Outlet;
import Inventori.gui.RegistrasiKategori;
import Util.BackgroundImage;
import Util.BackgroundPane;
import Util.DBConnector;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Yestin
 */
public class RegistrasiOutlet extends javax.swing.JFrame {

    Outlet Outlet = new Outlet();
    BackgroundImage BI = new BackgroundImage();
    /**
     * Creates new form RegistrasiOutlet
     */
    public RegistrasiOutlet() {
        initComponents();
        setTitle("Registrasi Outlet");
        try {
            BackgroundPane Background = new BackgroundPane();
            Background.setBackground(ImageIO.read(new File("\\E-POS\\Green Background 37.jpeg")));
            Background.setLayout(new BorderLayout());
            pnlRegistrasiOutlet.setOpaque(false);
            Background.add(pnlRegistrasiOutlet,BorderLayout.CENTER);
            this.setLayout(new BorderLayout());
            this.add(Background, BorderLayout.CENTER);
        } 
        catch (IOException ex) {
            Logger.getLogger(RegistrasiKategori.class.getName()).log(Level.SEVERE, null, ex);
        }
        BI.BackgroundJPanel(this, pnlRegistrasiOutlet);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistrasiOutlet = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamaOutlet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        scrlAlamat = new javax.swing.JScrollPane();
        txaAlamat = new javax.swing.JTextArea();
        lblKelurahan = new javax.swing.JLabel();
        txtKelurahan = new javax.swing.JTextField();
        lblKecamatan = new javax.swing.JLabel();
        txtKecamatan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        lblProvinsi = new javax.swing.JLabel();
        txtProvinsi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Nama Outlet :");

        txtNamaOutlet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaOutlet.setForeground(new java.awt.Color(0, 0, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Alamat : ");

        txaAlamat.setColumns(20);
        txaAlamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txaAlamat.setForeground(new java.awt.Color(0, 0, 255));
        txaAlamat.setRows(5);
        scrlAlamat.setViewportView(txaAlamat);

        lblKelurahan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKelurahan.setForeground(new java.awt.Color(0, 0, 255));
        lblKelurahan.setText("Kelursahan/Desa :");

        txtKelurahan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKelurahan.setForeground(new java.awt.Color(0, 0, 255));

        lblKecamatan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKecamatan.setForeground(new java.awt.Color(0, 0, 255));
        lblKecamatan.setText("Kecamatan :");

        txtKecamatan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKecamatan.setForeground(new java.awt.Color(0, 0, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Kabupaten/Kota :");

        txtKota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKota.setForeground(new java.awt.Color(0, 0, 255));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Simpan2.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setBackground(new java.awt.Color(255, 255, 255));
        btnTutup.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tutup.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        lblProvinsi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProvinsi.setForeground(new java.awt.Color(0, 0, 255));
        lblProvinsi.setText("Provinsi :");

        txtProvinsi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtProvinsi.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlRegistrasiOutletLayout = new javax.swing.GroupLayout(pnlRegistrasiOutlet);
        pnlRegistrasiOutlet.setLayout(pnlRegistrasiOutletLayout);
        pnlRegistrasiOutletLayout.setHorizontalGroup(
            pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiOutletLayout.createSequentialGroup()
                .addGroup(pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrasiOutletLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblKelurahan)
                            .addComponent(lblKecamatan)
                            .addComponent(jLabel3)
                            .addComponent(lblProvinsi))
                        .addGap(31, 31, 31)
                        .addGroup(pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaOutlet)
                            .addComponent(scrlAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                            .addComponent(txtKelurahan)
                            .addComponent(txtKecamatan)
                            .addComponent(txtKota)
                            .addComponent(txtProvinsi)))
                    .addGroup(pnlRegistrasiOutletLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnSimpan)
                        .addGap(76, 76, 76)
                        .addComponent(btnTutup)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlRegistrasiOutletLayout.setVerticalGroup(
            pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrasiOutletLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamaOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(scrlAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelurahan)
                    .addComponent(txtKelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKecamatan)
                    .addComponent(txtKecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProvinsi)
                    .addComponent(txtProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(pnlRegistrasiOutletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnTutup))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiOutlet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrasiOutlet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNamaOutlet.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Nama Outlet Belum Diisi");
            return;
        }
        
        String NamaOutlet = (((String)txtNamaOutlet.getText().trim()).toString());
        Outlet.setNamaOutlet(NamaOutlet);
        String Alamat = (((String)txaAlamat.getText().trim()).toString());
        Outlet.setAlamat(Alamat);
        String Kelurahan = (((String)txtKelurahan.getText().trim()).toString());
        Outlet.setKelurahan(Kelurahan);
        String Kecamatan = (((String)txtKecamatan.getText().trim()).toString());
        Outlet.setKecamatan(Kecamatan);
        String Kota = (((String)txtKota.getText().trim()).toString());
        Outlet.setKota(Kota);
        String Provinsi = (((String)txtProvinsi.getText().trim()).toString());
        Outlet.setProvinsi(Provinsi);
        
        try {
            Outlet.Simpan();
            
            DBConnector.getConnection().commit();
            Toolkit.getDefaultToolkit().beep();
            txtNamaOutlet.setText(null);
            txaAlamat.setText(null);
            txtKelurahan.setText(null);
            txtKecamatan.setText(null);
            txtKota.setText(null);
            txtProvinsi.setText(null);
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
        } 
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Saat Menyimpan Data Outlet : "+e.getMessage(),
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblKecamatan;
    private javax.swing.JLabel lblKelurahan;
    private javax.swing.JLabel lblProvinsi;
    private javax.swing.JPanel pnlRegistrasiOutlet;
    private javax.swing.JScrollPane scrlAlamat;
    private javax.swing.JTextArea txaAlamat;
    private javax.swing.JTextField txtKecamatan;
    private javax.swing.JTextField txtKelurahan;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtNamaOutlet;
    private javax.swing.JTextField txtProvinsi;
    // End of variables declaration//GEN-END:variables
}
