/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.gui;


import static App.Main.m_mainForm;
//import App.Verifikasi;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import oshi.SystemInfo;
import oshi.hardware.*;
/**
 *
 * @author Yestin
 */
public class Verification extends javax.swing.JDialog {

//    Verifikasi Verify = new Verifikasi();
    /**
     * Creates new form ComputerIdentifier
     */
    public Verification(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Verifikasi");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerifikasi = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        KodeVerifikasi = new javax.swing.JLabel();
        txtVerificationCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnVerifikasi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnVerifikasi.setText("Verifikasi");
        btnVerifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifikasiActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        KodeVerifikasi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        KodeVerifikasi.setText("Kode Verifikasi :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtVerificationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(531, 531, 531)
                            .addComponent(btnVerifikasi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClose))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(KodeVerifikasi)
                            .addGap(599, 599, 599))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(KodeVerifikasi)
                .addGap(18, 18, 18)
                .addComponent(txtVerificationCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnVerifikasi))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifikasiActionPerformed
        // TODO add your handling code here:
        SystemInfo SystemInfo = new SystemInfo();
        HardwareAbstractionLayer HAL = SystemInfo.getHardware();
        ComputerSystem ComputerSystem = HAL.getComputerSystem();
        String HardwareId = ComputerSystem.getHardwareUUID();
        String Verification = String.valueOf(txtVerificationCode.getText().trim());
        
        if(HardwareId.equals(Verification)){
            m_mainForm = new MainForms();
            
            m_mainForm.mInventori.setVisible(false);
            m_mainForm.miRegistrasiKategori.setVisible(false);
            m_mainForm.miDaftarKategori.setVisible(false);
            m_mainForm.miRegistrasiMerek.setVisible(false);
            m_mainForm.miDaftarMerek.setVisible(false);
            m_mainForm.miRegistrasiSatuan.setVisible(false);
            m_mainForm.miDaftarSatuan.setVisible(false);
            m_mainForm.miRegistrasiItem.setVisible(false);
            m_mainForm.miDaftarItem.setVisible(false);
            m_mainForm.miPenerimaanBarangSupplier.setVisible(false);
//            m_mainForm.miPengecekanStokItem.setVisible(false);
            
            m_mainForm.mTransaksi.setVisible(false);
            m_mainForm.miPenjualanTunai.setVisible(false);
            m_mainForm.miSetKasAwal.setVisible(false);
            m_mainForm.miLaba.setVisible(false);
            m_mainForm.miDataTransaksi.setVisible(false);
            m_mainForm.miPelunasan.setVisible(false);
            
            m_mainForm.mAdministrasi.setVisible(false);
            m_mainForm.miPengimputanFakturPembelian.setVisible(false);
            m_mainForm.miRegistrasiSupplier.setVisible(false);
            m_mainForm.miDataSupplier.setVisible(false);
            m_mainForm.miPencetakanBarcode.setVisible(false);
            m_mainForm.miSetNamaBisnis.setVisible(false);
            m_mainForm.miRegistrasiOutlet.setVisible(false);
            m_mainForm.miRegistrasiJenisPembayaran.setVisible(false);
            m_mainForm.miDaftarJenisPembayaran.setVisible(false);
            m_mainForm.miTambahSift.setVisible(false);
            m_mainForm.miDaftarSift.setVisible(false);
            m_mainForm.miRegistrasiMobil.setVisible(false);
            m_mainForm.miDataMobil.setVisible(false);
            
            m_mainForm.mUser.setVisible(true);
            m_mainForm.miRegistrasiUser.setVisible(false);
            m_mainForm.miDaftarUser.setVisible(false);
            m_mainForm.miGantiUsernamePassword.setVisible(false);
            m_mainForm.miRegistrasiJenisIdentitas.setVisible(false);
            m_mainForm.miDaftarJenisIdentitas.setVisible(false);
            m_mainForm.miRegistrasiFitur.setVisible(false);
            m_mainForm.miDaftarFitur.setVisible(false);
            m_mainForm.miEditAkses.setVisible(false);
            m_mainForm.miRegistrasiJenisPekerjaan.setVisible(false);
            m_mainForm.miDaftarJenisPekerjaan.setVisible(false);
            m_mainForm.miDataPekerjaan.setVisible(false);
            m_mainForm.miLogin.setVisible(true);
            m_mainForm.miLogout.setVisible(false);
            
            m_mainForm.mFinancial.setVisible(false);
            m_mainForm.miRegistrasiAkun.setVisible(false);
            m_mainForm.miDataAkun.setVisible(false);
            m_mainForm.miPembuatanMutasi.setVisible(false);
            m_mainForm.miDataMutasi.setVisible(false);
            m_mainForm.miRegistrasiPenyimpanan.setVisible(false);
            m_mainForm.miDataPenyimpanan.setVisible(false);
            
            m_mainForm.setVisible(true);
            
            setVisible(false);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Kode Verifikasi Salah");
            return;
        }
    }//GEN-LAST:event_btnVerifikasiActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KodeVerifikasi;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnVerifikasi;
    private javax.swing.JTextField txtVerificationCode;
    // End of variables declaration//GEN-END:variables
}
