/*
-- Query: SELECT * FROM akses WHERE KodeUser=19
-- Date: 2023-10-30 17:13
*/
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (1,1,'User',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (2,1,'Registrasi User',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (3,1,'Daftar User',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (4,1,'Ganti Username & Password',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (5,1,'Registrasi Jenis Identitas',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (6,1,'Daftar Jenis Identitas',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (7,1,'Inventori',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (8,1,'Registrasi Kategori',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (9,1,'Daftar Kategori',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (10,1,'Registrasi Merek',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (11,1,'Daftar Merek',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (12,1,'Registrasi Satuan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (13,1,'Daftar Satuan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (14,1,'Registrasi Item',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (15,1,'Daftar Item',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (16,1,'Penerimaan Barang',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (17,1,'Data Stok Item',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (18,1,'Input Stok Opname',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (19,1,'Data Stok Opname',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (20,1,'Pengurangan Stok Item',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (21,1,'Transaksi',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (22,1,'Penjualan Item',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (23,1,'Set Kas Awal',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (24,1,'Laba',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (25,1,'Data Transaksi',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (26,1,'Pelunasan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (27,1,'Administrasi',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (28,1,'Pengimputan Faktur Pembelian',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (29,1,'Registrasi Business Contact',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (30,1,'Daftar Business Contact',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (31,1,'Pencetakan Barcode',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (32,1,'Set Nama Bisnis',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (33,1,'Registrasi Outlet',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (34,1,'Daftar Outlet',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (35,1,'Registrasi Jenis Pembayaran',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (36,1,'Daftar Jenis Pembayaran',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (37,1,'Financial',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (38,1,'Registrasi Akun',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (39,1,'Pembuatan Mutasi',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (40,1,'Data Akun',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (41,1,'Data Mutasi',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (42,1,'Registrasi Fitur',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (43,1,'Daftar Fitur',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (44,1,'Transfer Stok',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (45,1,'Edit Akses',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (46,1,'Registrasi Jenis Pekerjaan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (47,1,'Daftar Jenis Pekerjaan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (48,1,'Data Pekerjaan Pegawai',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (49,1,'Registrasi Mobil',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (50,1,'Data Mobil',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (51,1,'Registrasi Penyimpanan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (52,1,'Data Penyimpanan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (53,1,'Tambah Sift',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (54,1,'Data Sift',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (55,1,'Penjualan Kredit',1);
