/*
-- Query: SELECT * FROM akses WHERE KodeUser=19
-- Date: 2023-10-30 17:13
*/
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (739,19,'User',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (740,19,'Registrasi User',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (741,19,'Daftar User',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (742,19,'Ganti Username & Password',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (743,19,'Registrasi Jenis Identitas',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (744,19,'Daftar Jenis Identitas',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (745,19,'Inventori',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (746,19,'Registrasi Kategori',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (747,19,'Daftar Kategori',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (748,19,'Registrasi Merek',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (749,19,'Daftar Merek',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (750,19,'Registrasi Satuan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (751,19,'Daftar Satuan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (752,19,'Registrasi Item',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (753,19,'Daftar Item',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (754,19,'Penerimaan Barang',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (755,19,'Data Stok Item',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (756,19,'Input Stok Opname',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (757,19,'Data Stok Opname',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (758,19,'Pengurangan Stok Item',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (759,19,'Transaksi',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (760,19,'Penjualan Item',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (761,19,'Set Kas Awal',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (762,19,'Laba',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (763,19,'Data Transaksi',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (764,19,'Pelunasan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (765,19,'Administrasi',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (766,19,'Pengimputan Faktur Pembelian',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (767,19,'Registrasi Business Contact',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (768,19,'Daftar Business Contact',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (769,19,'Pencetakan Barcode',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (770,19,'Set Nama Bisnis',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (771,19,'Registrasi Outlet',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (772,19,'Daftar Outlet',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (773,19,'Registrasi Jenis Pembayaran',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (774,19,'Daftar Jenis Pembayaran',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (775,19,'Financial',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (776,19,'Registrasi Akun',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (777,19,'Pembuatan Mutasi',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (778,19,'Data Akun',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (779,19,'Data Mutasi',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (780,19,'Registrasi Fitur',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (781,19,'Daftar Fitur',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (820,19,'Transfer Stok',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (839,19,'Edit Akses',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (906,19,'Registrasi Jenis Pekerjaan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (926,19,'Daftar Jenis Pekerjaan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (1096,19,'Data Pekerjaan Pegawai',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (1170,19,'Registrasi Mobil',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (1194,19,'Data Mobil',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (1218,19,'Registrasi Penyimpanan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (1242,19,'Data Penyimpanan',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (1266,19,'Tambah Sift',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (1290,19,'Data Sift',1);
INSERT INTO `akses` (`KodeAkses`,`KodeUser`,`NamaFitur`,`Akses`) VALUES (1313,19,'Penjualan Kredit',1);
