/*
-- Query: SELECT * FROM shanur.fitur
-- Date: 2023-11-14 17:15
*/
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (1,'User');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (2,'Registrasi User');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (3,'Daftar User');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (4,'Ganti Username & Password');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (5,'Registrasi Jenis Identitas');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (6,'Daftar Jenis Identitas');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (7,'Inventori');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (8,'Registrasi Kategori');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (9,'Daftar Kategori');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (10,'Registrasi Merek');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (11,'Daftar Merek');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (12,'Registrasi Satuan');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (13,'Daftar Satuan');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (14,'Registrasi Item');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (15,'Daftar Item');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (16,'Penerimaan Barang Dari Supplier');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (17,'Data Stok Item');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (18,'Input Stok Opname');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (19,'Data Stok Opname');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (20,'Pengurangan Stok Item');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (21,'Transaksi');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (22,'Penjualan Item');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (23,'Set Kas Awal');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (24,'Laba');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (25,'Data Transaksi');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (26,'Pelunasan');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (27,'Administrasi');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (28,'Pengimputan Faktur Pembelian');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (29,'Registrasi Business Contact');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (30,'Daftar Business Contact');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (31,'Pencetakan Barcode');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (32,'Set Nama Bisnis');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (33,'Registrasi Outlet');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (34,'Daftar Outlet');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (35,'Registrasi Jenis Pembayaran');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (36,'Daftar Jenis Pembayaran');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (37,'Financial');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (38,'Registrasi Akun');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (39,'Pembuatan Mutasi');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (40,'Data Akun');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (41,'Data Mutasi');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (42,'Registrasi Fitur');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (43,'Daftar Fitur');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (44,'Tambah Sift');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (45,'Daftar Sift');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (46,'Penerimaan Barang Dari Gudang');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (56,'Transfer Stok');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (57,'Edit Akses');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (58,'Registrasi Jenis Pekerjaan');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (59,'Daftar Jenis Pekerjaan');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (60,'Data Pekerjaan');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (61,'Registrasi Mobil');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (62,'Data Mobil');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (63,'Registrasi Penyimpanan');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (64,'Data Penyimpanan');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (65,'Tambah Sift');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (66,'Data Sift');
INSERT INTO `fitur` (`KodeFitur`,`NamaFitur`) VALUES (67,'Penjualan Kredit');
