/*
-- Query: SELECT * FROM epos.identitas
-- Date: 2023-08-10 10:55
*/
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('2384983464692',1,'Jenny Suciadi',2,'Gowa','2000-03-22','JL. Sultan Hasanuddin Lr 7, No 13','002','001','Pattalassang','Somba Opu','Gowa','Kristen','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('384839883939392',1,'Jenni Suardi',2,'Maros','1999-09-30','JL. Pahlawan, Lr 7, No 13','003','004','Pattallassang','Somba Opu','Gowa','Islam','Lajang','Karyawan','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('3848949839484',1,'Nur Ahmadi',1,'Gowa','2001-01-26','JL. Usman Salangke No 32','001','003','Tamalayang','Bontonompo','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('4749984393999',1,'Yenni Sugianto',2,'Makassar','2000-10-01','JL. Sultan Hasanuddin No 13','001','002','Pattalassang','Somba Opu','Gowa','Kristen','Lajang','Tidak Ada','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('4757448499393',1,'Noer Wahida',2,'Jeneponto','2000-03-20','JL. Sirajuddin Rani No 32','003','003','Bonto Bontoa','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('4759494393',1,'Andi Nur Alang',2,'Gowa','2000-07-11','JL. Sultan Hasanuddin No 32','002','003','Pandang Pandang','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('475994749933',1,'Andi Arlianti',2,'Makassar','1999-07-20','JL. Sultan Alauddin No 32','004','002','Gunung Sari','Rappocini','Makassar','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('4885034844833',1,'Aswardi Yudistira',1,'Maros','2000-09-28','JL. Syech Yusuf Lr 5, No 32','002','003','Pattalassang','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('4889474748383',1,'Muliati Ibrahim',2,'Bantaeng','1999-06-29','JL. Sam Ratulangi Lr 19, No 22','003','001','Pattalassang','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('49483994848399',1,'Nur Firmansyah',1,'Gowa','2000-12-26','JL. Sultan Hasanuddin Lr 10, No 13','003','001','Pattalassang','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('548384473833929',1,'Nur Maya',2,'Makassar','2001-09-09','Jl. Mangka Dg Bombong Lr 3, No 10','003','002','Palantikang','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('56568848373783',1,'Sri Wahyuni',2,'Makassar','1998-07-30','JL. Palantikang Lr 1, No 10','003','002','Palantikang','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('5894977494939',1,'Yustina Permaini',2,'Gowa','1999-10-23','JL. Usman Salangke No 33','002','003','Pattalassang','Somba Opu','Gowa','Kristen','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('5894984844839488',1,'Asriani Juniwati',2,'Makassar','1998-07-31','Jl. Malengkeri No 32','002','001','Tamalate','Tamalate','Makassar','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('647939474733929',1,'Nurul Faidah',2,'Makassar','2001-10-25','JL. Sultan Hasanuddin Lr, 19 No 32','007','002','Pattalassang','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('73844939484839',1,'Ardi Maulana',1,'Takalar','1998-10-28','JL. Palantikang No 13','003','002','Pantikang','Pallangga','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('74749394439399',1,'Andi Rahman',1,'Gowa','1999-10-27','JL. Mustafa Dg Bunga, No 32, Gowa','003','004','Bonto Bontoa','Somba Opu','Gowa','Islam','Menikah','Dirver','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('74794947383929',1,'Agus Virga',1,'Makassar','1999-09-23','Jl. Mustafa Dg Buang Lr 2, No 19','003','002','Pattalassang','Somba Opu','Gowa','Katolik','Lajang','Programmer','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('75759393748333',1,'Yunita Marwan',2,'Gowa','1998-11-26','JL. Sirajuddin Rani Lr 2, No 8','003','001','Bonto Bontoa','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('7575994883939',1,'Siti Nur Haliza',2,'Makassar','2000-09-15','JL. Somba Opu No 13','001','003','Pattalasang','Pallangga','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('75794948393939',1,'Jurmiah Aswani',2,'Makassar','1992-09-23','JL. Monginsidi Baru, Lr 4, No 12','003','001','Manccini Baru','Makassar','Makassar','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('7847593948322',1,'Tri Junianty',2,'Gowa','2000-02-22','JL. Sirajuddin Rani No 32','001','003','Bonto Bontoa','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('84734848393888',1,'Jumriati Almiah',2,'Gowa','1993-09-16','JL. Yusuf Bauty, Lr 19, No 32','003','0002','Pattingalloang','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('84857848383939',1,'Amelia Juniarti',2,'Bantaeng','1999-06-16','JL. Sultan Hasanuddin No 19','002','001','Pandang Pandang','Somba Opu','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('8489494333848',1,'Yusriadi Ahmad',1,'Makassar','2001-11-20','JL. Pelita Raya Lr 7, No 19','001','003','Bara Baraya','Makassar','Makassar','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('858495584949332',1,'Siti Nur Hasnah',2,'Gowa','1990-07-10','JL. Baji Bicara No 32','002','003','Bontonompo','Bajeng','Gowa','Islam','Menikah','Pegawai Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('8594955494939',1,'Sri Cahyanti',2,'Gowa','1999-11-09','JL. Palantikang No 13','003','002','Pacerakkang','Pallangga','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('885398483832',1,'Nur Wahyuni',2,'Makassar','1999-07-30','JL. Kareng Bonto Lr 13, No 32','003','002','Tamalayang','Bontonompo','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
INSERT INTO `identitas` (`NoIdentitas`,`KodeJenis`,`NamaLengkap`,`JenisKelamin`,`TempatLahir`,`TglLahir`,`Alamat`,`RT`,`RW`,`Kelurahan`,`Kecamatan`,`Kabupaten`,`Agama`,`StatusPernikahan`,`Pekerjaan`,`Kewarganegaraan`) VALUES ('95748849393933',1,'Asriadi',1,'Maros','2000-07-09','JL. Usman Jafar No 32','001','002','Tamalayang','Bontonompo','Gowa','Islam','Lajang','Karyawan Swasta','Indonesia');
