SELECT 
	transferstok.`KodeTF` AS transferstok_KodeTF,
	transferstok.`KodeUser` AS transferstok_KodeUser,
	transferstok.`Tanggal` AS transferstok_Tanggal,
	transferstok.`KodeKerja` AS transferstok_KodeKerja,
	transferstok.`KodeMobil` AS transferstok_KodeMobil,
	transferstok.`OutletAsal` AS transferstok_OutletAsal,
	transferstok.`OutletTujuan` AS transferstok_OutletTujuan,     
	transferstok.`StatusDelivery` AS transferstok_StatusDelivery,
	transferstok.`Biaya` AS transferstok_Biaya,
	transferstok.`Keterangan` AS transferstok_Keterangan,
	transferstok.KodePenerima AS transferstok_KodePenerima,
    user.`KodeUser` AS user_KodeUser,
    user.`NoIdentitas` AS user_NoIdentitas,
    user.`KodeOutlet` AS user_KodeOutlet,
    user.`Username` AS user_Username,
    user.`Password` AS user_Password,
    IdUser.`NoIdentitas` AS NoIdentitasUser,
	IdUser.`KodeJenis` AS KodeJenisUser,
	IdUser.`NamaLengkap` AS NamaLengkapUser,
	IdUser.`JenisKelamin` AS JenisKelaminUser,
	IdUser.`TempatLahir` AS TempatLahirUser,
	IdUser.`TglLahir` AS TglLahirUser,
	IdUser.`Alamat` AS AlamatUser,
	IdUser.`RT` AS RTUser,
	IdUser.`RW` AS RWUser,
	IdUser.`Kelurahan` AS KelurahanUser,
	IdUser.`Kecamatan` AS KecamatanUser,
	IdUser.`Kabupaten` AS KabupatenUser,
	IdUser.`Agama` AS AgamaUser,
	IdUser.`StatusPernikahan` AS StatusPernikahanUser,
	IdUser.`Pekerjaan` AS PekerjaanUser,
	IdUser.`Kewarganegaraan` AS KewarganegaraanUser,
    pekerjaan.`KodeKerja` AS pekerjaan_KodeKerja,
	pekerjaan.`NoIdentitas` AS pekerjaan_NoIdentitas,
	pekerjaan.`KodeJob` AS pekerjaan_KodeJob,
	pekerjaan.`KodeOutlet` AS pekerjaan_KodeOutlet,
	pekerjaan.`JenisPembayaran` AS pekerjaan_JenisPembayaran,
	pekerjaan.`Gaji` AS pekerjaan_Gaji,
    IdDriver.`NoIdentitas` AS NoIdentitasDriver,
    IdDriver.`KodeJenis` AS KodeJenisDriver,
    IdDriver.`NamaLengkap` AS NamaLengkapDriver,
    IdDriver.`JenisKelamin` AS JenisKelaminDriver,
    IdDriver.`TempatLahir` AS TempatLahirDriver,
    IdDriver.`TglLahir` AS TglLahirDriver,
    IdDriver.`Alamat` AS AlamatDriver,
    IdDriver.`RT` AS RTDriver,
    IdDriver.`RW` AS RWDriver,
    IdDriver.`Kelurahan` AS KelurahanDriver,
    IdDriver.`Kecamatan` AS KecamatanDriver,
    IdDriver.`Kabupaten` AS KabupatenDriver,
    IdDriver.`Agama` AS AgamaDriver,
    IdDriver.`StatusPernikahan` AS StatusPernikahanDriver,
    IdDriver.`Pekerjaan` AS PekerjaanDriver,
    IdDriver.`Kewarganegaraan` AS KewarganegaraanDriver,
	IdPenerima.`NoIdentitas` AS NoIdentitasPenerima,
    IdPenerima.`KodeJenis` AS KodeJenisPenerima,
    IdPenerima.`NamaLengkap` AS NamaLengkapPenerima,
    IdPenerima.`JenisKelamin` AS JenisKelaminPenerima,
    IdPenerima.`TempatLahir` AS TempatLahirPenerima,
    IdPenerima.`TglLahir` AS TglLahirPenerima,
    IdPenerima.`Alamat` AS AlamatPenerima,
    IdPenerima.`RT` AS RTPenerima,
    IdPenerima.`RW` AS RWPenerima,
    IdPenerima.`Kelurahan` AS KelurahanPenerima,
    IdPenerima.`Kecamatan` AS KecamatanPenerima,
    IdPenerima.`Kabupaten` AS KabupatenPenerima,
    IdPenerima.`Agama` AS AgamaPenerima,
    IdPenerima.`StatusPernikahan` AS StatusPernikahanPenerima,
    IdPenerima.`Pekerjaan` AS PekerjaanPenerima,
    IdPenerima.`Kewarganegaraan` AS KewarganegaraanPenerima,
    OutletAsal.`KodeOutlet` AS KodeOutletAsal,
	OutletAsal.`NamaOutlet` AS NamaOutletAsal,
	OutletAsal.`Alamat` AS AlamatAsal,
	OutletAsal.`Kelurahan` AS KelurahanAsal,
	OutletAsal.`Kecamatan` AS KecamatanAsal,
	OutletAsal.`Kota` AS KotaAsal,
	OutletAsal.`Provinsi` AS ProvinsiAsal,
    OutletTujuan.`KodeOutlet` AS KodeOutletTujuan,
	OutletTujuan.`NamaOutlet` AS NamaOutletTujuan,
	OutletTujuan.`Alamat` AS AlamatTujuan,
	OutletTujuan.`Kelurahan` AS KelurahanTujuan,
	OutletTujuan.`Kecamatan` AS KecamatanTujuan,
	OutletTujuan.`Kota` AS KotaTujuan,
	OutletTujuan.`Provinsi` AS ProvinsiTujuan,
    rinciantransfer.`KodeRincian` AS rinciantransfer_KodeRincian,
	rinciantransfer.`KodeTF` AS rinciantransfer_KodeTF,
	rinciantransfer.`Barcode` AS rinciantransfer_Barcode,
	rinciantransfer.`Satuan` AS rinciantransfer_Satuan,
	rinciantransfer.`Kuantitas` AS rinciantransfer_Kuantitas,
	rinciantransfer.`HargaModal` AS rinciantransfer_HargaModal,
	rinciantransfer.`TotalModal` AS rinciantransfer_TotalModal,
	items.`Barcode` AS items_Barcode,
    items.`NamaItem` AS items_NamaItem,
    items.`JenisItem` AS items_JenisItem,
    items.`KodeKategori` AS items_KodeKategori,
    items.`KodeMerek` AS items_KodeMerek,
	mobil.`KodeMobil` AS mobil_KodeMobil,
    mobil.`NoPolisi` AS mobil_NoPolisi,
    CASE WHEN (mobil.JenisMobil=1) THEN 'Pick Up Open' 
	WHEN (mobil.JenisMobil=2) THEN 'Pick Up Box' 
	WHEN (mobil.JenisMobil=3) THEN 'Truk Box' 
	WHEN (mobil.JenisMobil=4) THEN 'Truk Open' END AS JenisMobil,
    mobil.`Merek` AS mobil_Merek,
    mobil.`Warna` AS mobil_Warna,
	UserPenerima.`KodeUser` AS KodeUserPenerima,
    UserPenerima.`NoIdentitas` AS NoIdentitasPenerima,
    UserPenerima.`KodeOutlet` AS KodeOutletPenerima,
    UserPenerima.`Username` AS UsernamePenerima,
    UserPenerima.`Password` AS PasswordPenerima 
    FROM transferstok transferstok INNER JOIN user UserPenerima INNER JOIN identitas IdPenerima
    INNER JOIN user user INNER JOIN identitas IdUser INNER JOIN pekerjaan pekerjaan INNER JOIN identitas IdDriver 
    INNER JOIN outlet OutletAsal INNER JOIN outlet OutletTujuan INNER JOIN rinciantransfer rinciantransfer INNER JOIN items items INNER JOIN mobil mobil ON  
    (transferstok.KodeUser=user.KodeUser AND IdUser.NoIdentitas=user.NoIdentitas AND transferstok.KodeKerja=pekerjaan.KodeKerja 
    AND pekerjaan.NoIdentitas=IdDriver.NoIdentitas AND transferstok.OutletAsal=OutletAsal.KodeOutlet AND 
    transferstok.OutletTujuan=OutletTujuan.KodeOutlet AND transferstok.KodeTF=rinciantransfer.KodeTF AND rinciantransfer.Barcode=items.Barcode 
	AND transferstok.KodeMobil=mobil.KodeMobil AND UserPenerima.NoIdentitas=IdPenerima.NoIdentitas AND transferstok.KodePenerima=UserPenerima.KodeUser) 
	WHERE transferstok.KodeTF=2;