SELECT
     user.`KodeUser` AS user_KodeUser,
     user.`NoIdentitas` AS user_NoIdentitas,
     user.`KodeOutlet` AS user_KodeOutlet,
     user.`Username` AS user_Username,
     user.`Password` AS user_Password,
     transferstok.`KodeTF` AS transferstok_KodeTF,
     transferstok.`KodeUser` AS transferstok_KodeUser,
     transferstok.`Tanggal` AS transferstok_Tanggal,
     transferstok.`KodeKerja` AS transferstok_KodeKerja,
     transferstok.`KodeMobil` AS transferstok_KodeMobil,
     transferstok.`OutletAsal` AS transferstok_OutletAsal,
     transferstok.`OutletTujuan` AS transferstok_OutletTujuan,
     transferstok.`StatusDelivery` AS transferstok_StatusDelivery,
     transferstok.`Biaya` AS transferstok_Biaya,
     transferstok.`Keterangan` AS transferstok_Keterangan,
     rinciantransfer.`KodeRincian` AS rinciantransfer_KodeRincian,
     rinciantransfer.`KodeTF` AS rinciantransfer_KodeTF,
     rinciantransfer.`Barcode` AS rinciantransfer_Barcode,
     rinciantransfer.`Satuan` AS rinciantransfer_Satuan,
     rinciantransfer.`Kuantitas` AS rinciantransfer_Kuantitas,
     rinciantransfer.`HargaModal` AS rinciantransfer_HargaModal,
     rinciantransfer.`TotalModal` AS rinciantransfer_TotalModal,
     identitas.`NoIdentitas` AS identitas_NoIdentitas,
     identitas.`KodeJenis` AS identitas_KodeJenis,
     identitas.`NamaLengkap` AS identitas_NamaLengkap,
     identitas.`JenisKelamin` AS identitas_JenisKelamin,
     identitas.`TempatLahir` AS identitas_TempatLahir,
     identitas.`TglLahir` AS identitas_TglLahir,
     identitas.`Alamat` AS identitas_Alamat,
     identitas.`RT` AS identitas_RT,
     identitas.`RW` AS identitas_RW,
     identitas.`Kelurahan` AS identitas_Kelurahan,
     identitas.`Kecamatan` AS identitas_Kecamatan,
     identitas.`Kabupaten` AS identitas_Kabupaten,
     identitas.`Agama` AS identitas_Agama,
     identitas.`StatusPernikahan` AS identitas_StatusPernikahan,
     identitas.`Pekerjaan` AS identitas_Pekerjaan,
     identitas.`Kewarganegaraan` AS identitas_Kewarganegaraan,
     items.`Barcode` AS items_Barcode,
     items.`NamaItem` AS items_NamaItem,
     items.`JenisItem` AS items_JenisItem,
     items.`KodeKategori` AS items_KodeKategori,
     items.`KodeMerek` AS items_KodeMerek,
     stokitem.`KodeStok` AS stokitem_KodeStok,
     stokitem.`Barcode` AS stokitem_Barcode,
     stokitem.`KodeOutlet` AS stokitem_KodeOutlet,
     stokitem.`KodeSatuan` AS stokitem_KodeSatuan,
     stokitem.`Kuantitas` AS stokitem_Kuantitas,
     stokitem.`Isi` AS stokitem_Isi,
     stokitem.`StokMax` AS stokitem_StokMax,
     stokitem.`StokMin` AS stokitem_StokMin,
     stokitem.`HargaModal` AS stokitem_HargaModal,
     stokitem.`HargaJual` AS stokitem_HargaJual,
     stokitem.`Diskon` AS stokitem_Diskon,
     stokbarang.`KodeStok` AS stokbarang_KodeStok,
     stokbarang.`Barcode` AS stokbarang_Barcode,
     stokbarang.`KodeOutlet` AS stokbarang_KodeOutlet,
     stokbarang.`KodeSatuan` AS stokbarang_KodeSatuan,
     stokbarang.`Tanggal` AS stokbarang_Tanggal,
     stokbarang.`StokMasuk` AS stokbarang_StokMasuk,
     stokbarang.`StokKeluar` AS stokbarang_StokKeluar,
     stokbarang.`SisaStok` AS stokbarang_SisaStok,
     stokbarang.`HargaModal` AS stokbarang_HargaModal,
     stokbarang.`TotalModal` AS stokbarang_TotalModal,
     stokbarang.`HargaJual` AS stokbarang_HargaJual,
     stokbarang.`TotalJual` AS stokbarang_TotalJual,
     outlet.`KodeOutlet` AS outlet_KodeOutlet,
     outlet.`NamaOutlet` AS outlet_NamaOutlet,
     outlet.`Alamat` AS outlet_Alamat,
     outlet.`Kelurahan` AS outlet_Kelurahan,
     outlet.`Kecamatan` AS outlet_Kecamatan,
     outlet.`Kota` AS outlet_Kota,
     outlet.`Provinsi` AS outlet_Provinsi,
     mobil.`KodeMobil` AS mobil_KodeMobil,
     mobil.`NoPolisi` AS mobil_NoPolisi,
     mobil.`JenisMobil` AS mobil_JenisMobil,
     mobil.`Merek` AS mobil_Merek,
     mobil.`Warna` AS mobil_Warna,
     pekerjaan.`KodeKerja` AS pekerjaan_KodeKerja,
     pekerjaan.`NoIdentitas` AS pekerjaan_NoIdentitas,
     pekerjaan.`KodeJob` AS pekerjaan_KodeJob,
     pekerjaan.`KodeOutlet` AS pekerjaan_KodeOutlet,
     pekerjaan.`JenisPembayaran` AS pekerjaan_JenisPembayaran,
     pekerjaan.`Gaji` AS pekerjaan_Gaji,
     jenispekerjaan.`KodeJob` AS jenispekerjaan_KodeJob,
     jenispekerjaan.`NamaPekerjaan` AS jenispekerjaan_NamaPekerjaan
FROM
     `user` user INNER JOIN 
     `transferstok` transferstok INNER JOIN 
     `rinciantransfer` rinciantransfer INNER JOIN 
     `identitas` identitas INNER JOIN 
     `items` items INNER JOIN 
     `stokitem` stokitem INNER JOIN 
     `stokbarang` stokbarang INNER JOIN 
     `outlet` outlet INNER JOIN 
     `mobil` mobil INNER JOIN 
     `pekerjaan` pekerjaan INNER JOIN 
     `jenispekerjaan` jenispekerjaan ON (user.NoIdentitas=identitas.NoIdentitas AND transferstok.KodeUser=user.KodeUser AND 
     transferstok.OutletAsal=outlet.KodeOutlet AND transferstok.OutletTujuan=outlet.KodeOutlet AND items.Barcode=stokitem.Barcode 
     AND items.Barcode=stokbarang.Barcode AND stokitem.KodeOutlet=outlet.KodeOutlet AND transferstok.KodeMobil=mobil.KodeMobil)